### PR TITLE
Manual_Level.md: Fix typo. read to rear

### PR DESCRIPTION
**Pull request by Haxk20**
Just a small commit fixing a tiny typo i noticed

### CODE REVIEW

**Comment by Haxk20** [comment]
@KevinOConnor I think this is fine to merge as it is.

**Comment by Sineos** [comment]
Change is fine.
Typically you need a signed-off line as per https://github.com/Klipper3d/klipper/blob/master/docs/CONTRIBUTING.md No 2.

For trivial changes @KevinOConnor can choose to commit under his signed off.

**Comment by Haxk20** [comment]
Signoff has been added as requested. (3 days ago. Forgot to comment. Sorry)

**Comment by Sineos** [comment]
Signed-Off requires your real name.

**Comment by Haxk20** [comment]
> Signed-Off requires your real name.

As you wish

**Comment by Sineos** [comment]
Thanks for your support. Appreciated.

@KevinOConnor from my side good to merge

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
