### PR TITLE
Add delta implementation of Z_OFFSET_APPLY_ENDSTOP

### PR DESCRIPTION
**Pull request by janherich**
Current Z_OFFSET_APPLY_ENDSTOP command only works for printers with cartesian architecture which have separate Z axis defined. But this functionality (persisting Z babystep value to endstops) is exactly as convinient for delta printers, therefore this PR implements it.

### CODE REVIEW

**Comment by manu7irl** [comment]
Hi I think this method is really useful I got 3 deltas and running a delta_calibration each time my offset is changed, is driving me nuts.
I think that implementing that should be done by doing a contional state to see which type of kinematic is in use, and them apply the same command method than for a cartesian printer, if I am correct your implementation adds a new command named, z_offset_delta_apply_endstop.
I think that's a bit too much for users to run, also this should cause problem as fluidd and mainsail will have to adapt their codes for it.
So better to use the same name and apply the values differently based on the kinematic in use.
Correct me if I am wrong.
@janherich

**Comment by janherich** [comment]
Hi @manu7irl this PR implements new command internally but it's hooked to the same GCODE command `Z_OFFSET_APPLY_ENDSTOP` exactly because of the reasons you listed, so UIs like Mainsail/Fluid don't have to bother with decision logic and no new code is required - from UI POV, it's the same functionality and printer architecture doesn't matter.

**Comment by manu7irl** [comment]
Ok so I will try it on my deltas and report, please sign it off as Kevin requested.

**Comment by janherich** [comment]
@KevinOConnor I signed off the commit as requested and also changed the logic to check for `delta` kinematics when registering the delta specific `Z_OFFSET_APPLY_ENDSTOP` gcode command

**Pull request merged**
