### PR TITLE
Fix GitHub case

### PR DESCRIPTION
**Pull request by MrBrain295**
Fix up version of #6189.

### CODE REVIEW

**Review by dingyifei — APPROVED** [review]
Changes LGTM, but you might want to add signed off lines.

**Comment by MrBrain295** [comment]
I signed off on the second one so when it is squashed it will be signed.

**Comment by KevinOConnor** [comment]
Alas, I still don't see a signed-off-by line.  The signed-off-by line is a text statement that indicates you agree to the terms at https://github.com/Klipper3d/klipper/blob/master/docs/developer-certificate-of-origin .  See the documentation on it at https://www.klipper3d.org/CONTRIBUTING.html .

-Kevin

**Comment by MrBrain295** [comment]
Oh, I thought I had to sign off the commit.

**Pull request closed without merging**
