### PR TITLE
Added Config for Creality Ender 5 Pro 2020

### PR DESCRIPTION
**Pull request by SyrasX**
Idk if there is a reason why there was none. Would have had an easier time setting up Klipper with it.

Signed-off-by:  Maxim Schessler <maxim.schessler@gmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
I'm not sure what the state of this PR is.  At a minimum, the config would need to follow the guidelines at: https://www.klipper3d.org/Example_Configs.html .

-Kevin

**Comment by SyrasX** [comment]
Removed the parts mentioned by @Fisheiyy. I added this config after getting my printer half a year ago and it works fine, Don't see anything not conforming with the guidlines after a short look. @KevinOConnor

**Review by Fisheiyy — APPROVED** [review]
Looks good to me

**Comment by KevinOConnor** [comment]
Thanks.  It looks fine, but the file should be added to printers.test (point 4 at https://www.klipper3d.org/Example_Configs.html ).

-Kevin

**Comment by SyrasX** [comment]
Done. @KevinOConnor

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
