### PR TITLE
scripts: update_chitu.py python env version

### PR DESCRIPTION
**Pull request by JamesH1978**
Change script to use Python 3 instead of Python 2, in line with changes to update_mks_robin.py

Thanks
James

Signed-off-by: James Hartley <james@hartleyns.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  I'm fine with the change, but have you (or someone else) confirmed it actually works on Python3?

-Kevin

**Comment by JamesH1978** [comment]
I have confirmed the scripts runs and outputs on both a pi and a ubuntu server build, but I have no chitu board to test it
image

Is that enough?

Thanks
James

**Comment by KevinOConnor** [comment]
Yes, thanks.

-Kevin

**Comment by mattaw** [comment]
If it is any comfort I compiled with python2 and 3 on my setup, and the md5sum's of both files were identical. I ran into this problem but chickened out of creating a PR as I was in a hurry, and just installed python2. Since I had both installed:

```bash
pi@mainsail:~/klipper $ md5sum ./out/update.cbd
1ca3065cebe7611299d2cbf1c785bb52  ./out/update.cbd
pi@mainsail:~/klipper $ md5sum ./out/update_py3.cbd
1ca3065cebe7611299d2cbf1c785bb52  ./out/update_py3.cbd
```

Nice work @JamesH1978 & @KevinOConnor

**Pull request merged**
