### PR TITLE
adding two additional pid control algorithms:  no_overshoot and ponm …

### PR DESCRIPTION
**Pull request by bjones14**
http://brettbeauregard.com/blog/2017/06/introducing-proportional-on-measurement/

https://github.com/KevinOConnor/klipper/issues/4427

### CODE REVIEW

**Comment by susisstrolch** [comment]
Doesn't work at all...
Steps to reproduce:
1. removed the pid sections from printer.cfg (SAVE_CONFIG)
2. set 'control: pid_ponm' for both extruder and heatbed
3. run PID_TUNE for extruder and heatbed

after running PID_TUNE 'control' was reset to 'pid' (by klipper).
So I manually set 'control' to 'ponm' for both extruder and heatbed (in the SAVE_CONFIG section of printer.cfg), restarted firmware and klipper and and tried heating with the new algorith.
Heating simply doesn't work - power stays at 0% - and klipper errors out.

**Comment by KevinOConnor** [comment]
Thanks.  I'm not sure I understand the "big picture" of this PR.  If a user wanted to use these methods, couldn't they just tweak their pid_Kp, pid_Ki, pid_Kd settings in the config?  What's the gain of altering the code?

-Kevin

**Comment by bjones14** [comment]
> Thanks. I'm not sure I understand the "big picture" of this PR. If a user wanted to use these methods, couldn't they just tweak their pid_Kp, pid_Ki, pid_Kd settings in the config? What's the gain of altering the code?
> 
> -Kevin

The big picture is the proportional on measurement PID method - it changes how the math is done in the PID algorithm - though you are correct in that the only different between the original two are the scaling/gains on the PID terms so it doesn't matter as much there - it was more for adding additional PID control types than anything, key one being PonM.

**Comment by bjones14** [comment]
> Doesn't work at all...
> Steps to reproduce:
> 
> 1. removed the pid sections from printer.cfg (SAVE_CONFIG)
> 2. set 'control: pid_ponm' for both extruder and heatbed
> 3. run PID_TUNE for extruder and heatbed
> 
> after running PID_TUNE 'control' was reset to 'pid' (by klipper).
> So I manually set 'control' to 'ponm' for both extruder and heatbed (in the SAVE_CONFIG section of printer.cfg), restarted firmware and klipper and and tried heating with the new algorith.
> Heating simply doesn't work - power stays at 0% - and klipper errors out.
> 
> General note:
> I'm missing doku about the usage and hints how to tune the ponm with klipper.

Running PID auto tune will run through the standard Z-N PID variables which will not be correct for PonM control - there is not an auto-tune function in place for this control type.

More documentation/info on PonM can be found here - http://brettbeauregard.com/blog/2017/06/introducing-proportional-on-measurement/

**Comment by KevinOConnor** [comment]
Thanks.  As high-level feedback, a merge of PONM support would need come after test results on a variety of printers demonstrating its utility.  I think key to obtaining that wouId be user documentation explaining how and when to utilize PONM.

So, if there is interest in pursuing this, I'd say the next steps would be to try and find testers and come up with a procedure that testers should run to quantify the overall impact.

FWIW, I'd be surprised that proportional on measurement would work well in a 3d printer as the amount of power required to heat to a particular temperature is not linear.  For example, heating to 120 degrees is not twice the power needed to heat to 60 degrees and not half the power needed to heat to 240 degrees.  Higher temperatures need significantly higher power to maintain.  Happy to be shown to be wrong though.

Cheers,
-Kevin

**Comment by bjones14** [comment]
> Thanks. As high-level feedback, a merge of PONM support would come after test results on a variety of printers demonstrating its utility. I think key to obtaining that wouId be user documentation explaining how and when to utilize PONM.
> 
> So, if there is interest in pursuing this, I'd say the next steps would be to try and find testers and come up with a procedure that testers should run to quantify the overall impact.
> 
> FWIW, I'd be surprised that proportional on measurement would work well in a 3d printer as the amount of power required to heat to a particular temperature is not linear. For example, heating to 120 degrees is not twice the power needed to heat to 60 degrees and not half the power needed to heat to 240 degrees. Higher temperatures need significantly higher power to maintain. Happy to be shown to be wrong though.
> 
> Cheers,
> -Kevin

I think that makes perfect sense, I'll work to provide and gather more information and tests to verify the impact.

You pointed out the exact reason why PonM is good - it's an integrating process.  That means that the heater output controls the rate of temperature change, but there is not a linear relationship to X power = X temperature, as we are always adding heat as it is taken away by ambient air, cooling fans, etc.

**Comment by acwest** [comment]
> Running PID auto tune will run through the standard Z-N PID variables which will not be correct for PonM control - there is not an auto-tune function in place for this control type.
> ... 
> More documentation/info on PonM can be found here - http://brettbeauregard.com/blog/2017/06/introducing-proportional-on-measurement/

Can you document HOW to determine the correct values for the PonM case, if autotune won't work?

**Comment by jwkicklighter** [comment]
If #4427 is definitely waiting on this ticket, can we open it back up?

**Pull request closed without merging**
