### PR TITLE
Adds Ender 2 Pro config

### PR DESCRIPTION
**Pull request by spuder**
Adds a default config for ender 2 pro. See [previous pull request](https://github.com/Klipper3d/klipper/pull/5037) for additional details.

I've tested this and it works for me.

Signed-off-by: Spencer Owen <owenspencer@gmail.com>

### CODE REVIEW

**Comment by spuder** [comment]
There are these 2 warnings in the fluidd gui. 

I'm optimizing for consistency here. Since no other example configs have these 2 values defined, I'm intentionally omitting them from this pull request. 

Screen Shot 2022-03-15 at 9 34 40 PM

**Review by Fisheiyy — CHANGES_REQUESTED** [review]
remove all the following lines unless they come stock on this printer and fix the USART pins.

- 28
- 29
- 53
- 54
- 70
- 82
- 103
- 104
- 116-130

**Comment by spuder** [comment]
Will do, thank you for reviewing.

Documenting for posterity. If anyone else stumbles on this and wants to add BLTouch, change the following settings (or look at my [specific settings here](https://github.com/spuder/klipper-ender2pro/blob/main/printer.cfg)

```
[stepper_x]
position_min: -11
position_endstop: -11

[stepper_z]
endstop_pin: probe:z_virtual_endstop
position_min: -5.0

[bltouch]
sensor_pin: ^PB1
control_pin: PB0
x_offset: -30
y_offset: 2
z_offset: 2

[safe_z_home]
home_xy_position: 83, 83 # Change coordinates to the center of your print bed
speed: 50
z_hop: 10
z_hop_speed: 10
```

**Review by Fisheiyy — APPROVED** [review]
You still need to add the [Signed-off-by line](https://github.com/Klipper3d/klipper/blob/master/docs/CONTRIBUTING.md) in your initial opening comment and need a blank newline at the end of your config otherwise the check will fail.

**Comment by spuder** [comment]
I've made the requested changes, squashed commits, fixed the Signed-off-by line and re-read the Contributing document.
I think this change is ready. Please let me know if I missed anything.

**Comment by Fisheiyy** [comment]
Looks good to me just need to wait for someone with the actual authority to merge this.

**Comment by KevinOConnor** [comment]
Thanks.  It looks fine to me, but please add it to the printers.test test cases (point 4 at https://www.klipper3d.org/Example_Configs.html ).

-Kevin

**Comment by spuder** [comment]
printers.test test cases added

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
