### PR TITLE
tmc2240

### PR DESCRIPTION
**Pull request by marsb007**
The TMC2240 driver works fine. Have been testing it for 2-3 weeks now on the SB2240 with no issues.

### CODE REVIEW

**Comment by JamesH1978** [comment]
Please clean up your whitespace and review https://github.com/Klipper3d/klipper/blob/master/docs/CONTRIBUTING.md paying particular attention to the signed-off-by line.

Thanks
James

**Comment by RenaatLO** [comment]
Dear all,

will this commit be available in the public release of klipper ?
The missing tmc2240 section is returning errors at this stage.

**Comment by JamesH1978** [comment]
If the contributor cleans up his build check errors, and conforms to the contribution rules, and then it is reviewed to be good code and a good fit for mainline, then yes.

Thanks
James

**Comment by leptun** [comment]
Hello @bigtreetech. Nice code you've got there. I couldn't help but notice that you are using my tmc2240 code from my fork (https://github.com/leptun/klipper/tree/tmc2240). Next time you take code from other people's repository without giving credit, could you at least use the latest version which has bugs fixed? You took my tmc2240 commit, stripped it of some features, rewrote a bit of the `TMC2240CurrentHelper` class (presumably since the commit you took was an older version of mine with bugs I've fixed in the meantime) and added unrelated code which doesn't look like something that should be in mainline klipper. I really hope you were not planning to make a PR to mainline klipper using code you took from me, without giving any credit. Please let me know if I understood this situation incorrectly. It's not clear to me what relation is between you and @marsb007 and if @marsb007 represents BTT.

@KevinOConnor @JamesH1978 The reason I have not made a PR with my changes yet is because my tmc2240 implementation is based on another commit of mine which expands some of the options for the other tmc drivers, something which was not really related directly to the tmc2240 itself. I would have preferred if I had that commit as a separate PR first and then focus on getting the tmc2240 merged into mainline as to not make a single PR with lots of changes. My commits also didn't have the Signed off and explanation in comments, so they would have been most likely rejected if I did end up opening a PR in the current state.
Another reason for which I didn't make a tmc2240 PR as of now is because there isn't really hardware available in the wild that can make use of the tmc2240 code. Sure, BTT seems to be actively developing boards for this new driver, but I don't think it's available for purchase yet. If you look for example on Mouser, the tmc2240 is still months away from being "in stock", the only hardware available at the moment being the EVAL boards of this driver.
Speaking of EVAL boards, I have been using two of those TMC2240_EVAL boards on my printer for X and Y for the past few months and they've been working great with my code. So for what it's worth, I confirm @marsb007's claim that my code works.
Is tmc2240 support in mainline klipper something of interest? If yes, I'd gladly get my code ready for a PR(s) (reword my commits, write documentation, etc...) and have the changes merged.

**Comment by katosabi** [comment]
Hi leptun, the tmc2240 is definitely something of interest due to the existence of the BTT SB2240 toolhead boards; some Voron owners are already using these with BTT's fork. 

I hope BTT/marsb007 clear up any misunderstandings with respect to your code; the way they handle this will definitely impact any future purchase I make with them.

**Comment by marsb007** [comment]
I have no relation to Bigtree. 

I just got annoyed that they released the SB2240 without official support for the tmc2240 and after a few weeks of staring at the invalid entry in klipper (for using the BTT fork), I pushed it to try and get them to push something themselves. I closed the request - once again, just did it to hopefully make them do something. It obviously wasn’t my intention to take your code (as until now I didn’t even know it was yours).

If you want to push your version, please do. I’ve been using it for about a month now without any issues that I can tell. There are several people on the Voron discord that you can speak with and none of us had any driver related issues. 

Hope this explanation helps.

**Comment by Sineos** [comment]
FWIW: https://github.com/bigtreetech/klipper/commits/tmc2240
@leptun No idea how much it might match your work

**Comment by KevinOConnor** [comment]
FYI, BTT did ship me a SB2240 board.  It's been in transit and will likely arrive in a few days.  One way or another, I do plan on adding tmc2240 support to mainline Klipper.

I'm not familiar with the background of the existing tmc2240 code, but for what it is worth, it did not seem to me that BTT had improper intentions.

Cheers,
-Kevin

**Comment by leptun** [comment]
I've prepared the TMC improvements PR. The tmc2240 code is based on these changes: https://github.com/Klipper3d/klipper/pull/6074. I'll start rebasing my tmc2240 changes on top of that branch soon.

**Comment by leptun** [comment]
And here is the PR for TMC2240 support: https://github.com/Klipper3d/klipper/pull/6076

**Pull request closed without merging**
