### PR TITLE
hc32f460: Add app address 0x10000

### PR DESCRIPTION
**Pull request by falk-h**
This is required for the Anycubic Kobra 2. See [this definition in Anycubic's newly released source code](https://github.com/ANYCUBIC-3D/Kobra2/blob/main/source/app/main.cpp#L15).

### CODE REVIEW

**Comment by KevinOConnor** [comment]
@SteveGotthardt - any comments on this?

-Kevin

**Review by AleksB27 — APPROVED** [review]
Successfully tested on Kobra2.

**Comment by ABDViciousOne** [comment]
> Successfully tested on Kobra2.

What settings did you use for building the firmware

**Comment by falk-h** [comment]
> What settings did you use for building the firmware

```
Micro-controller Architecture (Huada Semiconductor HC32F460)  --->
Communication interface (Serial (PA15 & PA09))  --->
Application Address (0x10000)  --->
Clock Speed (200 MHz)  --->
``` 

I'm not entirely sure that these settings are correct (especially the clock speed), but these are the last settings I used before I went back to the stock firmware. I ended up going back because I wasn't able to figure out which pins to use to talk to the stepper drivers over UART.

[Anycubic's source code](https://github.com/ANYCUBIC-3D/Kobra2/) seems to [run the stepper drivers in standalone mode](https://github.com/ANYCUBIC-3D/Kobra2/blob/7ae6dc54619e44344f48906f44f7e761bf4abdc2/source/Marlin/Configuration.h#L707), without UART communication, but they have only released the source code for v2.9.3 of the firmware at the time of writing. v3.0.2 has linear advance and input shaping, which iirc can't work without talking to the steppers over UART, but the source for v3.0.2 isn't released yet. I'm currently waiting for them to release that source before I continue trying to get Klipper to work on my printer.

**Comment by AleksB27** [comment]
I used 168mhz speed
Steppers are in stand-alone mode 100% - I checked all GPIO pins of controller and can provide a map (expect 3-4pins I was not able to found).

**Comment by falk-h** [comment]
@AleksB27 I think I had figured out most of the pins by looking at Anycubic's source (and some trial and error), but I'd very much appreciate a map :)

**Comment by AleksB27** [comment]
Sure
[Trigorilla Pro B CPU pinout.xlsx](https://github.com/Klipper3d/klipper/files/12237938/Trigorilla.Pro.B.CPU.pinout.xlsx)

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Comment by Coldarn** [comment]
> Successfully tested on Kobra2.

@AleksB27 Could you share the full printer.cfg you used? I'm trying to get my Kobra 2 working with Klipper but so far have been stumped by many unfamiliar settings. Here's the incomplete starting point I'm working from: https://drive.google.com/file/d/1pM1Jqvb7u2QWBPVBMnJPBVq0YINx-xez/view

**Comment by Coldarn** [comment]
Never mind, I found [this tutorial](https://function3d.xyz/en/how-to-install-klipper-on-anycubic-kobra-2/) included the configs I needed; here's a direct link to them for posterity: https://drive.google.com/file/d/1b9xOY9zppay2TfVpMH0pkc6hTFPuR4Y5/view?usp=drive_link

**Pull request merged**
