### PR TITLE
makefile: Handle path with name with spaces

### PR DESCRIPTION
**Pull request by sl1pkn07**
Fix https://github.com/Klipper3d/klipper/issues/5706

### CODE REVIEW

**Review by thijstriemstra — APPROVED** [review]

**Comment by thijstriemstra** [comment]
Nice. Make sure your commits follow(ed) this: https://github.com/Klipper3d/klipper/blob/master/docs/CONTRIBUTING.md#format-of-commit-messages

**Comment by sl1pkn07** [comment]
Hi. something like now?

greetings

**Comment by sl1pkn07** [comment]
i just follow this https://stackoverflow.com/a/30691137 but adapted to change from space to scaped space

i have tested quoted all KCONFIG_CONFIG in the makefile rules. but none of them works, in special https://github.com/Klipper3d/klipper/blob/40b4b34998c0708b2050c394feb383f901b76a0b/Makefile#L99 and https://github.com/Klipper3d/klipper/blob/40b4b34998c0708b2050c394feb383f901b76a0b/Makefile#L107

i'm not coder, so im certainly can make other alternative. but this PR simply works as spected

greetings

**Comment by sl1pkn07** [comment]
https://stackoverflow.com/questions/10571658/gnu-make-convert-spaces-to-colons

seems this also works

~~~patch
diff --git a/Makefile b/Makefile
index c112a832..8b037a1e 100644
--- a/Makefile
+++ b/Makefile
@@ -11,10 +11,7 @@ OUT=out/
 export KCONFIG_CONFIG     := $(CURDIR)/.config
 
 # Handle path with spaces
-null      :=
-SPACE     := $(null) $(null)
-ESC_SPACE := $(null)\ $(null)
-ESC_KCONFIG_CONFIG = $(subst $(SPACE),$(ESC_SPACE),$(KCONFIG_CONFIG))
+ESC_KCONFIG_CONFIG = $(subst $() $(),$()\ $(),$(KCONFIG_CONFIG))
 -include $(ESC_KCONFIG_CONFIG)
 
 # Common command definitions
~~~

is better?

greetings

**Comment by KevinOConnor** [comment]
Thanks.  I guess I'm still not sure on this.  It seems simpler to me to just install Klipper in a directory without spaces.  I'm also concerned about other tools and functionality that may break even if we fix this part of the build.

-Kevin

**Comment by eamaclean** [comment]
It seems unreasonable to me to expect users to not use valid paths on their filesystem.

**Comment by sl1pkn07** [comment]
with "other tools" you mean external tools? well, imo, then should be fixed in their respective tools

greetings

**Comment by sl1pkn07** [comment]
sad :(

**Pull request closed without merging**
