### PR TITLE
config: Add BigTreeTech Manta M4P & M8P board

### PR DESCRIPTION
**Pull request by bigtreetech**
Signed-off-by: Alan.Ma from BigTreeTech tech@biqu3d.com

### CODE REVIEW

**Comment by JamesH1978** [comment]
Can I ask why you are proposing removing flashing instructions from the SKR Mini E3 v3 file? These are still perfectly valid and as far as I know there is no other way to flash it, at least for the initial flash.

Thanks
James

**Comment by bigtreetech** [comment]
> Can I ask why you are proposing removing flashing instructions from the SKR Mini E3 v3 file? These are still perfectly valid and as far as I know there is no other way to flash it, at least for the initial flash.
> 
> Thanks James

According to the instructions [here](https://github.com/Klipper3d/klipper/pull/5596) 
From my personal point of view `make flash FLASH_DEVICE=/dev/serial/by-id/usb-Klipper_stm32g0b1xx` DFU updates are valid for `stm32g0b1`
If `removing flashing instructions from the SKR Mini E3 v3` will cause misunderstanding, I can restore it.

**Comment by JamesH1978** [comment]
Yes that option may be valid, but that only works once there has been an initial Klipper flash. For subsequent flashes it is perfectly valid. I do not believe this board ships with a default klipper flash therefore a klipper by-id will not be available. I am not entirely sure if the dfu flash will work using the default marlin by-id, or if a klipper flash is a prerequisite for this to work. I do not have this board to test. 

Thanks
James

**Comment by bigtreetech** [comment]
Yes, It need klipper running before use DFU.  I will restore it now

**Comment by KevinOConnor** [comment]
Thanks.  I committed this change and also added the two config files to the regression tests (commit 2d4ce1b9).

-Kevin

**Pull request merged**
