### PR TITLE
module: PCA9632, LED module for FlashForge Dreamer 3D printer

### PR DESCRIPTION
**Pull request by loop777**
Added PCA9632 LED module support using software I2C from MCP4018
modulo drive the LED strip of a FlashForge Dreamer 3D printer.
Based on the PCA9533 module. Configuration reference below:

 [pca9632 led_strip]
 scl_pin:
 \#   The SCL "clock" pin. This parameter must be provided.
 sda_pin:
 \#   The SDA "data" pin. This parameter must be provided.
 \#initial_RED: 0
 \#initial_GREEN: 0
 \#initial_BLUE: 0
 \#initial_WHITE: 0
 \#   PCA9632 supports individual LED PWM.
 \#   Values range from 0 to 255. The default is 0.
 \#   On the FlashForge Dreamer, the white led is not populated.
 \#   Use GCODE to modify led values after startup.
 \#   set_led led=led_strip red=255 green=255 blue=255

Signed-off-by: Ricardo Alcantara <ricardo@vulcanolabs.xyz>

### CODE REVIEW

**Comment by loop777** [comment]
I have modified Klipper to work with my FlashForge Dreamer without ruining the factory bootloader. It was not easy, but is partially working (meaning it is printing but missing the second extruder and the diplay functionality). The module commited here is very well tested and working. I hope to finish my integration and commit all the work to the main branch.

I'm not familiar with git and contributing to projects like this, so sorry if I make any mistakes.

**Comment by KevinOConnor** [comment]
Thanks.  Does this printer require that the PCA9632 be accessed via "bit banging"?  That is, the micro-controller doesn't have an i2c hardware block accessible on the pins wired to the PCA9632?

In general, the change looks fine with me.  However, there should also be an update to docs/Config_Reference.md with information on configuring the module.

Also, this change is something I'd look at merging after the v0.10.0 release.

-Kevin

**Comment by loop777** [comment]
Hi! Thanks for your review. Here are some considerations:

> That is, the micro-controller doesn't have an i2c hardware block accessible on the pins wired to the PCA9632?

Exactly this.

> However, there should also be an update to docs/Config_Reference.md with information on configuring the module.

Should I update it?

> Also, this change is something I'd look at merging after the v0.10.0 release.

Fine for me.

**Comment by KevinOConnor** [comment]
Yes - the documentation update should be in the same PR as the code update.  Otherwise, this change looks fine to me.

-Kevin

**Comment by KevinOConnor** [comment]
Thanks.  This "slipped" on my side.  The code looks fine to me.  Is it still worthwhile to merge this?

-Kevin

**Comment by loop777** [comment]
Yes, please!

**Comment by loop777** [comment]
Uhm.. ok. I'll take a look at that and change to keep standards. Should be done today.

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Comment by terrapinlogo** [comment]
The Ultimaker 2 also uses this LED driver for its LED ring around the click wheel. Problem is it has some hardware differences that are not compatible with the FlashForge Dreamer.

- The bus is shared with the ssd1306 display meaning it needs to use hardware i2c as well
- The chip used is the 10 pin variant that allows different addresses. The Ultimaker uses address 96
- The blue and green channels are swapped

How would be the best way to accommodate both printers? A flag for specifying hardware/software i2c and a mapping function for the colours or two different modules?

**Comment by KevinOConnor** [comment]
I'd probably do something like the following (untested as I don't have the hardware):
```diff
--- a/docs/Config_Reference.md
+++ b/docs/Config_Reference.md
@@ -2615,10 +2615,22 @@ PCA9632 LED support. The PCA9632 is used on the FlashForge Dreamer.
 
 ` ``
 [pca9632 my_pca9632]
-scl_pin:
-#   The SCL "clock" pin. This parameter must be provided.
-sda_pin:
-#   The SDA "data" pin. This parameter must be provided.
+#i2c_address: 98
+#   The i2c address that the chip is using on the i2c bus. The default
+#   is 98.
+#i2c_mcu:
+#i2c_bus:
+#i2c_speed:
+#   See the "common I2C settings" section for a description of the
+#   above parameters.
+#scl_pin:
+#sda_pin:
+#   Alternatively, if the pca9632 is not connected to a hardware I2C
+#   bus, then one may specify the "clock" (scl_pin) and "data"
+#   (sda_pin) pins. The default is to use hardware I2C.
+#color_order: RBGW
+#   Set the pixel order of the LED. Options are RBGW and RGBW. The
+#   default is RBGW.
 #initial_RED: 0.0
 #initial_GREEN: 0.0
 #initial_BLUE: 0.0
diff --git a/klippy/extras/pca9632.py b/klippy/extras/pca9632.py
index a5659cfe7..683954e03 100644
--- a/klippy/extras/pca9632.py
+++ b/klippy/extras/pca9632.py
@@ -3,7 +3,7 @@
 # Copyright (C) 2022  Ricardo Alcantara <ricardo@vulcanolabs.com>
 #
 # This file may be distributed under the terms of the GNU GPLv3 license.
-from . import mcp4018
+from . import bus, mcp4018
 
 BACKGROUND_PRIORITY_CLOCK = 0x7fffffff00000000
 
@@ -17,15 +17,23 @@ PCA9632_PWM3 = 0x05
 PCA9632_LEDOUT = 0x08
 
 LED_PWM = 0x02
-PCA9632_RED = 0x00
-PCA9632_GRN = 0x04
-PCA9632_BLU = 0x02
-PCA9632_WHT = 0x06
+PCA9632_LED0 = 0x00
+PCA9632_LED1 = 0x02
+PCA9632_LED2 = 0x04
+PCA9632_LED3 = 0x06
+
+COLOR_FORMATS = ["RBGW", "RGBW"]
 
 class PCA9632:
     def __init__(self, config):
         self.printer = printer = config.get_printer()
-        self.i2c = mcp4018.SoftwareI2C(config, 98)
+        if config.get("scl_pin", None) is not None:
+            self.i2c = mcp4018.SoftwareI2C(config, 98)
+        else:
+            self.i2c = bus.MCU_I2C_from_config(config, default_addr=98)
+        formats = {v: v for v in COLOR_FORMATS}
+        color_order = config.getchoice("color_order", formats, "RBGW")
+        self.color_map = [color_order.index(c) for c in "RGBW"]
         self.prev_regs = {}
         pled = printer.load_object(config, "led")
         self.led_helper = pled.setup_helper(config, self.update_leds, 1, True)
@@ -48,16 +56,17 @@ class PCA9632:
         if print_time is not None:
             minclock = self.i2c.get_mcu().print_time_to_clock(print_time)
 
-        red, green, blue, white = [int(v * 255. + .5) for v in led_state[0]]
-        self.reg_write(PCA9632_PWM0, red, minclock=minclock)
-        self.reg_write(PCA9632_PWM1, blue, minclock=minclock)
-        self.reg_write(PCA9632_PWM2, green, minclock=minclock)
-        self.reg_write(PCA9632_PWM3, white, minclock=minclock)
+        color = [int(v * 255. + .5) for v in led_state[0]]
+        led0, led1, led2, led3 = [color[idx] for idx in self.color_map]
+        self.reg_write(PCA9632_PWM0, led0, minclock=minclock)
+        self.reg_write(PCA9632_PWM1, led1, minclock=minclock)
+        self.reg_write(PCA9632_PWM2, led2, minclock=minclock)
+        self.reg_write(PCA9632_PWM3, led3, minclock=minclock)
 
-        LEDOUT = (LED_PWM << PCA9632_RED if red else 0)
-        LEDOUT |= (LED_PWM << PCA9632_GRN if green else 0)
-        LEDOUT |= (LED_PWM << PCA9632_BLU if blue else 0)
-        LEDOUT |= (LED_PWM << PCA9632_WHT if white else 0)
+        LEDOUT = (LED_PWM << PCA9632_LED0 if led0 else 0)
+        LEDOUT |= (LED_PWM << PCA9632_LED1 if led1 else 0)
+        LEDOUT |= (LED_PWM << PCA9632_LED2 if led2 else 0)
+        LEDOUT |= (LED_PWM << PCA9632_LED3 if led3 else 0)
         self.reg_write(PCA9632_LEDOUT, LEDOUT, minclock=minclock)
     def get_status(self, eventtime):
         return self.led_helper.get_status(eventtime)
```

If it works, let me know.
-Kevin

**Comment by terrapinlogo** [comment]
I can confirm that the above works on an Ultimaker 2. I don't have a FlashForge to test on so unable to confirm that.

**Pull request merged**
