### PR TITLE
hard_pwm: Add pin defs for STM32F070 and STM32F072

### PR DESCRIPTION
**Pull request by willpuckett**
When experimenting with the new "pwm_pin" last week, I discovered that my toolhead board, an STM32F072, didn't have hardware pwm defined in Klipper.

This PR attempts to reconcile the above issue, and also includes pwm pin definitions for ~~all processors in the STM32F0 family~~ STM32F070.

Tests with my laser are greatly improved.

I am still tentative about ST's nomenclature. I also am not deeply aware of any other concerns I may need to take into consideration, i.e. ensuring that defined pins don't conflict with another portion of Klipper somehow.

In the rare circumstance in which a pin had multiple timers defined on different GPIO functions, the lower numbered function was used.

I utilized pin definitions from the following data sheets:
- [STM32F031x4 STM32F031x6](https://www.st.com/resource/en/datasheet/stm32f031c4.pdf)
- [STM32F042x4 STM32F042x6](https://www.st.com/resource/en/datasheet/stm32f042f6.pdf)
- [STM32F070CB STM32F070RB STM32F070C6 STM32F070F6](https://www.st.com/resource/en/datasheet/stm32f070cb.pdf)
- [STM32F072x8 STM32F072xB](https://www.st.com/resource/en/datasheet/stm32f072cb.pdf)

Common pins have been unioned as much as possible.

### CODE REVIEW

**Comment by willpuckett** [comment]
Build tests failed for STM32F031 and STM32F042, so removed them from the pull request.

**Comment by KevinOConnor** [comment]
Thanks.  Commits need to have a signed-off-by line in order to be committed - see https://www.klipper3d.org/CONTRIBUTING.html .

Otherwise, the change looks fine to me.

Cheers,
-Kevin

**Comment by willpuckett** [comment]
Thanks so much!

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
