### PR TITLE
[Docs] Add PROBE_SPEED paramter to PROBE_ACCURACY

### PR DESCRIPTION
**Pull request by hatkyinc2**
Add `PROBE_SPEED` paramter to `PROBE_ACCURACY` documentation

image

### CODE REVIEW

**Comment by JamesH1978** [comment]
Thank you for submitting a PR, please refer to https://github.com/Klipper3d/klipper/blob/master/docs/CONTRIBUTING.md and make sure you have provided some context to your change and you have added signed off by line.

Also not sure this command has a LIFT_SPEED option that can be set on the gcode command line.

Thanks

James

**Comment by hatkyinc2** [comment]
image
@JamesH1978 Does this example usage image satisfy you that this is a working config option?

**Comment by hatkyinc2** [comment]
Sample of using all 4 options at the same time

image

**Comment by hatkyinc2** [comment]
I've added the signature in the commit message

**Comment by KevinOConnor** [comment]
Thanks.  The change looks fine, but I don't see a signed-off-by line - please see the documentation at https://www.klipper3d.org/CONTRIBUTING.html#format-of-commit-messages

-Kevin

**Pull request closed without merging**
