### PR TITLE
stm32g0: Disable internal pull-down resistors on UCPDx CCx pins, because klipper never uses UCPD

### PR DESCRIPTION
**Pull request by bigtreetech**
According to https://www.st.com/resource/en/datasheet/stm32g0b1cb.pdf page 55.

image

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  Seems fine to me.  I'll give a few days to see if there are any other comments.

-Kevin

**Comment by moggieuk** [comment]
Kevin, I just want to comment on the urgency of this.   With the launch of the ERCFv2 project we are advocating the use of the BTT MMB mcu.  This uses the stm32g0.  Without special instruction the default firmware install is causing all kinds of overheating problems with connected steppers.  We have burn out 5 steppers on the test team alone, one of which deformed the ABS mounts.  Many community members have also run into the problem.

Obviously we are trying to get the word out on the care need whilst setting up the mcu but obviously a fix in Klipper soon to minimize the exposure window for what is a safety concern.

Thanks for listening 🙏

**Comment by KevinOConnor** [comment]
Okay, thanks for the info.  I'll target this weekend for the merge.

-Kevin

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Comment by moggieuk** [comment]
Thank you :pray:

**Pull request merged**
