### PR TITLE
Important step for consistent 100mm/s

### PR DESCRIPTION
**Pull request by hernandez87v**
I followed directions but I only had consistent 100mm/s at beginning and end of print only.  99% of the print was printing at 46mm/s.

### CODE REVIEW

**Comment by dingyifei** [comment]
Please modify the commit to follow  https://www.klipper3d.org/CONTRIBUTING.html
Additionally, there are some typos in your commit, and "layer time" should be "minimum layer time"

**Comment by dewi-ny-je** [comment]
I agree on the suggestion, I also initially made the same mistake.

However, please reformat the lines you edited so that they are not longer than 80 characters.

**Review by dingyifei — COMMENTED** [review]
Looks good to me, you still need to modify the commit message. Perhaps squash two commits and edit the commit message directly in the process. 

https://www.klipper3d.org/CONTRIBUTING.html#format-of-commit-messages

**Review by hernandez87v — COMMENTED** [review]
docs: Add detail about minimum layer print time for required speed to be met.

Signed-off-by: Vlad Hernandez <hernandez87v@gmail.com>

**Comment by hernandez87v** [comment]
Created clean Pull request #5340

**Comment by hernandez87v** [comment]
Just wanted to bump this as I think it would help alot of ppl out. I created the new cleaned up pull request #5340

**Pull request closed without merging**
