### PR TITLE
toolchanger: Initial API documentation for review.

### PR DESCRIPTION
**Pull request by viesturz**
Setting up toolchangers with klipper is currently a free for all land of macros and plugins. This is an attempt to introduce some common structure that is generic enough to fit almost all use cases but still provide useful structure to make most configs look familiar.

https://github.com/TypQxQ/Klipper_ToolChanger is a capable implementation of something similar. This is trying to be significantly more minimalistic and less opinionated.

### CODE REVIEW

**Comment by JamesH1978** [comment]
I am not sure what you are trying to achieve here? there is no module called `toolchanger` or `tool` in klipper? is this tied to another PR that will introduce these modules? This might be better suited for the discourse server where it could be discussed further.

Thanks
James

**Comment by viesturz** [comment]
Thanks for the input. This is to discuss an API conceptually. The API here
seems to be the more tricky part, implementation is relatively straight
forward.
Yes Discord seems to be the right place to discuss, I posted this
yesterday, looking forward for feedback.


Ready to do the implementation once the API is ironed out.

**Comment by viesturz** [comment]
Pushed significant update. Getting rid of templates in favor of option to nest toolchangers.

Considering maybe adding per-toolchanger variables, would help with chaining multiple changers of same type, like AMS units, but seems too complex for first run.

**Comment by KevinOConnor** [comment]
I'm not sure what the status of this PR is or was.  If there is interest in discussing future Klipper development, I suggest using Klipper Discourse for that.  Note that Discourse is not the same as Discord.

-Kevin

**Comment by viesturz** [comment]
Hi, Discourse vs Discord is a good catch, I was wondering why Discord dev chat was not responsive.

**Pull request closed without merging**
