### PR TITLE
Update RPi_microcontroller.md (pwm-2chan)

### PR DESCRIPTION
**Pull request by FatalBulletHit**
Added a more detailed explanation for pwm-2chan.

### CODE REVIEW

**Comment by JamesH1978** [comment]
Thankyou for submitting a PR, please could you refer to point 3 in the "what to expect" section in https://github.com/Klipper3d/klipper/blob/master/docs/CONTRIBUTING.md and add a signed-off-by line.

Thanks
James

**Comment by FatalBulletHit** [comment]
RPi_microcontroller.md: Added a more detailed explanation for pwm-2chan

Signed-off-by: Alfie Batthullt <FatalBulletHit@gmail.com>

**Comment by KevinOConnor** [comment]
@mrvanes - do you have any comments on this?

-Kevin

**Comment by mrvanes** [comment]
It's been a while, but looks good to me. I don't have the hardware to actually test the instructions for the second pwm channel, but I trust them to have done their homework.

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
