### PR TITLE
config: Update printer-sovol-sv06-2022.cfg x_offset

### PR DESCRIPTION
**Pull request by bassamanator**
config: Update printer-sovol-sv06-2022.cfg x_offset

Signed-off-by: Bassam Husain bassamanator.2cj4t@simplelogin.com

### CODE REVIEW

**Comment by bassamanator** [comment]
Please note that [Sovol official's](https://github.com/Sovol3d/Sv06-Source-Code/blob/315aa28b5c1438b36ae17dc43500cfc70e7e24b0/Marlin/Configuration.h#L1183C4-L1183C4) probe offset's are completely wrong to begin with:

```c++
#define NOZZLE_TO_PROBE_OFFSET { 25, -25, 0 }
```

This error was only partially corrected by the creator of `printer-sovol-sv06-2022.cfg`, @spinixguy.

When you extrapolate the `x_offset` from the extruder model itself in CAD (find it [here](https://github.com/Sovol3d/SV06-Fully-Open-Source/blob/main/Assemblies%20step/JXHSV06-08000%20Extruder%20Component.step)), and physically measure it (with great difficulty), you find that it's closer to:

```
x_offset: 27
```

Screengrab from FreeCAD 0.21.1:

nozzle-offset

**Comment by JamesH1978** [comment]
Thanks for submitting the PR, do you have any real world evidence to corroborate this is a better number to use? Maybe a user of this printer to confirm using the steps in the documentation to manually calibrate this. https://github.com/Klipper3d/klipper/blob/master/docs/Probe_Calibrate.md#calibrating-probe-x-and-y-offsets

Thanks
James

**Comment by spinixguy** [comment]
@bassamanator Mine measures to the offset I placed in the config. This was also checked by measuring two other machines at the time. I do not doubt that there is some variance out there and I have zero issue in changing this from 28 to 27.

**Comment by bassamanator** [comment]
> Thanks for submitting the PR, do you have any real world evidence to corroborate this is a better number to use? Maybe a user of this printer to confirm using the steps in the documentation to manually calibrate this. https://github.com/Klipper3d/klipper/blob/master/docs/Probe_Calibrate.md#calibrating-probe-x-and-y-offsets

Unfortunately, whatever figure I come up with, it will be within the margin of error. I maintain the most popular Klipper config repo for the SV06, SV06-Plus, SV06-SKR-Mini-E3-V3.0, ([source](https://github.com/bassamanator/Sovol-SV06-firmware), [source](https://github.com/topics/sovol)), if there were issues, I would have heard about it.

Please note that the SV06/Plus and the SV07/Plus share the **exact same** *base* extruder assembly (the hotends differ, some of them have lights, etc.).

Sovol has corrected the probe offset values for the SV07. Here are the offset values sent to me from 2 users:
```
[probe]
pin:PD13
x_offset:27
y_offset:-20
```

Here is the full image that a *random* user pulled from the SV07 board showing the same figures: [source](https://github.com/MS1987/SOVOL_MKDEB/blob/c693083f636b6056b5cfaa147b0ff57f67f02726/home/mks/printer_data/config/printer.cfg#L337).

Having said all this, I do not think any user can be trusted. We must rely on the most substantive piece of data that we have, which is the 3D models provided by Sovol.

Here are some images of the SV06-Plus:
nozzle-offset-plus
sv06plus-extruder

SV06:
sv06-extruder

**Review by JamesH1978 — APPROVED** [review]
Fair enough, cant see an issue then,

Thanks
James

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
