### PR TITLE
stm32: add FDCAN support for STM32G0B1

### PR DESCRIPTION
**Pull request by bigtreetech**

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  I see this is marked as "draft".  What needs to be done for you to consider it ready for committing?

-Kevin

**Comment by bigtreetech** [comment]
> Thanks. I see this is marked as "draft". What needs to be done for you to consider it ready for committing?
> 
> -Kevin

Hello, Because the previous code style and some formats do not meet the PR requirements, so I marked it as "draft" . 
And I cleaned it up now. and this PR is ready to be reviewed and merged.

**Comment by bigtreetech** [comment]
> > Thanks. I see this is marked as "draft". What needs to be done for you to consider it ready for committing?
> > -Kevin
> 
> Hello, Because the previous code style and some formats do not meet the PR requirements, so I marked it as "draft" . And I cleaned it up now. and this PR is ready to be reviewed and merged.

**Comment by KevinOConnor** [comment]
Thanks.  It looks fine to me.  I'll give a few days to see if there are any other comments, and otherwise commit this change.

-Kevin

**Comment by zruncho3d** [comment]
A bunch of us are receiving these boards now, and to program them from mainline Klipper would be nice.  

@KevinOConnor  Checking back in on your message above, to merge if there are no comments.

**Comment by KevinOConnor** [comment]
Thanks.  I committed this with some minor build changes on top (commit 63affd70).

-Kevin

**Pull request merged**
