### PR TITLE
Customizable serial path for Klipper linux mcu

### PR DESCRIPTION
**Pull request by meteyou**
This PR adds the attribute "-I" to the Linux MCU. With this feature, you can move the serial path to the new Moonraker folder structure (for example, ~/printer_data/comms/host-mcu.serial). Furthermore, we updated the service from init.d to systemd. By default, I did not change the serial path to not have to edit too many docs.

Example for the new Moonraker structure:

Modify this line in the `/etc/systemd/system/klipper-mcu.service`:
```
Environment=KLIPPER_HOST_MCU_SERIAL=/tmp/klipper_host_mcu
```
to:
```
Environment=KLIPPER_HOST_MCU_SERIAL=/home/pi/printer_data/comms/host-mcu.serial
```
And then, you have to use this serial path in your `printer.cfg`:
```
[mcu host]
serial: ~/printer_data/comms/host-mcu.serial
```

### CODE REVIEW

**Review by zellneralex — CHANGES_REQUESTED** [review]
Should be:

sudo systemctl enable klipper-mcu.service

Forgot it I overseen the “green” sudo

**Review by zellneralex — APPROVED** [review]

**Comment by KevinOConnor** [comment]
Thanks.  In general, it looks fine to me.  The only thing I noticed is it looks like you have a whitespace error in the new klipper-mcu.service file (no newline at end of file).

-Kevin

**Comment by meteyou** [comment]
Thanks! I added the new line at the end of the file klipper-cmu.service.

**Comment by KevinOConnor** [comment]
Could you rebase this series and squash the fix into the appropriate commit.

-Kevin

**Comment by meteyou** [comment]
Rebased this branch and merged both commits of the klipper-mcu.service file. Is that exactly how you meant it?

**Comment by KevinOConnor** [comment]
Yes, thanks.

-Kevin

**Pull request merged**
