### PR TITLE
samd21: fix erroneous register bit reference.

### PR DESCRIPTION
**Pull request by mattthebaker**
Signed-off-by: Matt Baker <baker.matt.j@gmail.com>

### CODE REVIEW

**Comment by mattthebaker** [comment]
This needs some discussion, the original code was setting bits which are not correct or reserved by referencing the wrong defines. However, updating the code may change bus behavior. I believe the change reflects the original code intention.

**Comment by KevinOConnor** [comment]
Thanks.  Good catch.  I'd say it is probably safer to just remove those two erroneous bits.  It looks like I wrote the original code, but I don't know why I tried to include those two bits.  Since the code seems to be working without setting those bits, probably safer to avoid setting them now.

Maybe @FHeilmann has some comments on this.

-Kevin

**Comment by FHeilmann** [comment]
> Maybe @FHeilmann has some comments on this.

Thanks for the tag but unfortunately I have nothing to add to this.

Fh

**Comment by mattthebaker** [comment]
Agree, that would be the prudent choice. They appear related to automatic bus error or timeout recovery, I did not dig deep and it as awhile ago. Device is working without.

I force pushed with bits removed instead.

Matt

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
