### PR TITLE
add function display IP

### PR DESCRIPTION
**Pull request by EchoHeim**
Display the current host ip address on the 12864 for easy viewing

### CODE REVIEW

**Comment by Sineos** [comment]
Not sure reading the code correctly but it looks like a hard error when the IP could not be obtained. If true then this is not a robust solution. Apart from this I see no reason for my printer to contact Google DNS.

At minimum you need to follow https://www.klipper3d.org/CONTRIBUTING.html, especially the signed-off line

**Comment by EchoHeim** [comment]
The screen shows 0.0.0.0 when the ip cannot be obtained.
Google DNS is only used as a basis to verify whether the network is connected or not, and has no other role.

**Review by zellneralex — APPROVED** [review]
Tried it on my machine and looks good to me

**Comment by jschuh** [comment]
This doesn't feel like the right approach. Klipper doesn't interact with the network, so this is just sort of grabbing an arbitrary IPv4 address (which will usually be correct, but on some systems won't).

Unless I'm misunderstanding the goal, it seems like what you really want is for Moonraker to provide Klipper with the set of addresses it's listening on?

**Pull request closed without merging**
