### PR TITLE
rp2040: running without external flash

### PR DESCRIPTION
**Pull request by Sasasu**
Added a new option for rp2040, RP2040_FLASH_NOFLASH, to enable it to run without external flash. This option allows the rp2040 to boot from its internal bootloader and execute code directly from RAM.

With this build option, firmware must be loaded into rp2040 every time it is powered on or reset this can be done by using an external debugger via SWD or using USB to upload a U2F file into bootrom.

This commit also repurposes 6 IO pins that were originally reserved for QSPI to be used as GPIO pins.

### CODE REVIEW

**Comment by Sineos** [comment]
https://github.com/Klipper3d/klipper/pull/5889 the same?

**Comment by Sasasu** [comment]
> #5889 the same?

noop. this one runs without NOR flash connect to rp2040. #5889 boot from NOR flash and move code to SRAM.

**Comment by JamesH1978** [comment]
Please review https://github.com/Klipper3d/klipper/blob/master/docs/CONTRIBUTING.md paying particular attention to the signed-off-by line.

Thanks
James

**Comment by Sasasu** [comment]
image

the USB connection is much more stable than before :>.

**Comment by Arksine** [comment]
Someone with more experience with the rp2040 than I will need to review this, but one thing I am certain of is that reporting a UID that is not unique will break CAN.

**Comment by KevinOConnor** [comment]
Thanks.  As high-level feedback, this seems like a "neat hack" of the rp2040.  However, it's not clear to me how many people would use this in practice.  So, I'm not sure it is a good match for the main Klipper repository.

-Kevin

**Pull request closed without merging**
