### PR TITLE
An "advanced" tuning guide

### PR DESCRIPTION
**Pull request by KevinOConnor**
This adds a new tuning guide to the Klipper documentation.  It provides some hints for common tuning goals (reducing print times, increasing extrusion quality).  It's targeted towards expert users looking for some hints on how to go about tuning with Klipper.

Guides like this is are hard to write.  I'm hoping there is some value in it though.

Let me know of suggestions for improvement or other thoughts.
-Kevin

### CODE REVIEW

**Comment by vladbabii** [comment]
1. the wording on PID tuning should be a bit more strong, maybe as a basic requirement for the other tuning steps and put first in the list. It's also the easiest to do, just takes some time, and maybe that is how it should be described along the lines "a must have calibration, requires just running two commands and a little bit of time and does not require any printing". We tend to take it for granted, but i met people that thought it needs to be dialed in manually and calculate the 3 values and lots of math...

2. Not sure if this fits with the rest of the tuning guide (since it's a hardware modification), but a good way to decrease print time is to increase layer width by using a bigger nozzle and maybe this should be mentioned as an option. I had great results going from 0.4 to 0.6 nozzle and using 0.68 layer width in slicer settings.

**Comment by KevinOConnor** [comment]
Thanks for reviewing.

> the wording on PID tuning should be a bit more strong

I'll take a look at it.  The guide is targeted towards experts, so I'm too worried about a novice getting confused.  I'll try to word it so that's more clear.

> a good way to decrease print time is to increase layer width by using a bigger nozzle 

Yeah, I think I need to reword the whole "slicer layer height" section.  What I really want to say is "one can reduce print time by reducing the total number of moves emitted by the slicer" - which can be done by reducing infill, increasing layer height, increasing extrusion width, etc.

-Kevin

**Comment by Sineos** [comment]
Nice guide and well written. Especially the advanced tuning objects and Klipper's automated tuning aids are very useful IMO.
 
Some additional information on `microsteps` and `custom step duration` would be nice. May not directly reduce print times but can increase precision and /or lead to problems if print speed is higher than the combination of `microsteps` and `custom step duration` allows.

**Comment by KevinOConnor** [comment]
> Some additional information on microsteps and custom step duration would be nice. 

Thanks for reviewing.  I agree that adding a section on "stepper motor driver tuning" would be useful.  However, I'm not sure I actually know how tune them..  The general rule seems to be use 16 microsteps and sets the current to "high enough but not too high".

Cheers,
-Kevin

**Comment by Sineos** [comment]
> Thanks for reviewing. I agree that adding a section on "stepper motor driver tuning" would be useful. However, I'm not sure I actually know how tune them.. The general rule seems to be use 16 microsteps and set the current "high enough but not too high".

WRT to z-banding, I made good experience with higher microsteps. Maybe at least mentioning the `custom step duration` during `make menuconfig` and its relationship to the max permissible microsteps would be worthwhile.

**Comment by grigi** [comment]
Another useful thing to print faster was to increase the extrusion width wider than the nozzle.
e.g. Cura defaults to 0.4 for a 0.4 nozzle, but I can happily increase it to about 0.56 without causing problems. The prints are also very strong when I do that. 

I think CNC Kitchen had a video finding that optimal strength was around 140-150% extrusion width, so that could be a decent strategy to increase print speeds if the extruder/hot-end can keep up.

**Comment by KevinOConnor** [comment]
As per the guidelines in the updated CONTRIBUTING document, I'm no longer going to track this experiment here on the main Klipper3d github repo. I'm moving discussion to https://klipper.discourse.group/t/advanced-klipper-tuning-document/1686

-Kevin

**Pull request closed without merging**
