### PR TITLE
optionally setup ExtruderStepper.stepper as PrinterRail

### PR DESCRIPTION
**Pull request by naikymen**
The change is borrowed from manual_stepper.
The objective is to provide support for adding
endstops on an extruder stepper.
The use case for extruder homing is homing
syringe-based extruders for 3D-printing.
A suitable "extra" module can then be written
to home the extruder.

I hope you find this useful.

Signed-off-by: Nicolás Méndez

### CODE REVIEW

**Comment by KevinOConnor** [comment]
I agree it could be useful to "home" an extruder for certain hardware setups.  Changes to Klipper need to be "complete changes" that offer some real-world benefit to users though.  See the guide at https://www.klipper3d.org/CONTRIBUTING.html .  Also see the signed-off-by line requirements in that document.

Cheers,
-Kevin

**Comment by naikymen** [comment]
Hello Kevin,

Thanks for the interest, and for the Klipper project in general. I added my name to the PR above.

>  Changes to Klipper need to be "complete changes" that offer some real-world benefit to users though. 

I'm not sure if the exact criteria applies. This is not a user-facing change, it is meant for extension development.

> Is the Klipper documentation updated to reflect new changes?

I will gladly work on the applicable documentation items _if_ it would have the change merged.

Also: though the change is small and seemed reasonable, I do not know if it is the optimal one. It should be easy for someone more qualified than me to take over.

On a personal note, I'd really like to see this kind of extension-enabling features merged. They would make Klipper more adaptable, whilst keeping its focus on FFD printing.

Thanks again, and happy new year!

N.

**Comment by KevinOConnor** [comment]
Thanks for the feedback, and happy new year!

Klipper doesn't have an "extension interface" nor "plugin system".  The "extras" and "kinematics" directories are an internal interface intended to improve code modularity.  Klipper does have an "API Server" to promote integration with external code.

If you are ready to submit an internal module that utilizes the changes here then that is fine.  I'm leery of changing the code until all the associated code that utilizes it is ready for review.

Cheers,
-Kevin

**Comment by naikymen** [comment]
Hi!

First, an update: I found that I required an additional change to klippy's core (https://github.com/Klipper3d/klipper/pull/5950/commits/d313c8000d66c3be8cc05548e05116ba41b08191) to prevent an unwanted additional displacement after the stepper halted.

It consists of calling `extruder.update_move_time` near the end of a `drip_move` (more specifically, at the end of the `DripModeEndSignal` except clause).

I'd like to know if that change could be expected to cause any issues. My hardware tests pass, with no evident homing issues on any axis. :partying_face: 

----

> If you are ready to submit an internal module that utilizes the changes here then that is fine.

I'm not sure if I can go through the review process for a full module at the moment. The time I've invested in studying klippy's source is already more than I would have preferred for my current objective.

I was hoping to keep this pull request specific to the required/enabling changes in core klippy. I could, later on, start a separate pull request for the module.

> I'm leery of changing the code until all the associated code that utilizes it is ready for review.

The `extras` module I've been writing is [here](https://github.com/naikymen/klipper-homing-extruder/blob/pipetting/klippy/extras/extruder_home.py) (WIP), and the machine I'm working on is over [here](https://gitlab.com/pipettin-bot/pipettin-grbl/) (also WIP). I hope that by having a look at them you may find the PR less leerying.


> Klipper doesn't have an "extension interface" nor "plugin system".

That would be great though! :)

I'd love to see a repository of external modules to paste into extras.

**Pull request closed without merging**
