### PR TITLE
Fix error to get SRCDIR on debian installation

### PR DESCRIPTION
**Pull request by nbranquinho**

### CODE REVIEW

**Comment by dmbutyugin** [comment]
I'm afraid the change isn't quite correct. For example, if executed as
```
pi@octopi:~ $ klipper/scripts/install-debian.sh
```
it would detect SRCDIR incorrectly, wouldn't it? Can you describe the issue you are trying to resolve in more details?

**Review by nbranquinho — COMMENTED** [review]
Rectify the command for the correct command

**Comment by Sineos** [comment]
I wonder how you are actually calling the script to make the variable empty:

```
$ cat > test.sh
#!/bin/bash
echo "[$0] vs. [${BASH_SOURCE[0]}]"
```

Debian Stretch:
```
$ ./test.sh
[./test.sh] vs. [./test.sh]
$ bash test.sh
[test.sh] vs. [test.sh]
$ /home/pi/test.sh
[/home/pi/test.sh] vs. [/home/pi/test.sh]
$ . ./test.sh
[-bash] vs. [./test.sh]
```

Debian Buster:
```
$ ./test.sh
[./test.sh] vs. [./test.sh]
$ bash test.sh
[test.sh] vs. [test.sh]
$ /home/pi/test.sh
[/home/pi/test.sh] vs. [/home/pi/test.sh]
$ . ./test.sh
[-bash] vs. [./test.sh]
```

I can only get the variable to be empty when "sourcing" the script, i.e. calling it indirectly, which is not done in the standard installation way.

**Comment by nbranquinho** [comment]
Hello.

 

I have the 11 version (bullseye):

 

Distributor ID: Debian

Description:    Debian GNU/Linux 11 (bullseye)

Release:        11

Codename:       bullseye

 

 

I call the script directly and I did the test and I get no result:



 

Inside the file is:

 



 

I read something about empty value on BASH_SOURCE:

 

·         $BASH_SOURCE expands empty when bash does not know where the executing code comes from. Usually, this means the code is coming from standard input (e.g. ssh host 'somecode', or from an interactive session).

I don’t know if this is relevant or not… 

 

I’m connected through ssh to my VM machine running my Debian system… 

 

Com os melhores cumprimentos,

Nelson Branquinho

**Comment by Sineos** [comment]
```
root@bullseye:~# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@bullseye:~# /root/test.sh 
[/root/test.sh] vs. [/root/test.sh]
root@bullseye:~# ./test.sh 
[./test.sh] vs. [./test.sh]
root@bullseye:~# bash test.sh 
[test.sh] vs. [test.sh]
root@bullseye:~# . ./test.sh 
[-bash] vs. [./test.sh]
root@bullseye:~# 
```

Looks like a local problem on your installation.

**Comment by nbranquinho** [comment]
Hello.

The installation was done from scratch based on the debian ISO.

Regardless, and given that it works, reject the PR I did without any problem.

Best Regards

 

Com os melhores cumprimentos,

Nelson Branquinho

**Pull request closed without merging**
