### PR TITLE
stm32f401: support adc_temperature sensor

### PR DESCRIPTION
**Pull request by ayufan**
> The temperature sensor is internally connected to the ADC_IN18

> The TSVREFE bit must be set to enable the conversion of both internal channels: the ADC1_IN16 or ADC1_IN18 (temperature sensor) and the ADC1_IN17 (VREFINT).

Ref.: https://www.st.com/resource/en/reference_manual/dm00096844-stm32f401xb-c-and-stm32f401xd-e-advanced-arm-based-32-bit-mcus-stmicroelectronics.pdf

### CODE REVIEW

**Comment by ayufan** [comment]
@KevinOConnor I do have https://github.com/FYSETC/FYSETC-Cheetah-v2 (which uses f401) on my Voron 0.1. With the above change it does show reasonable values: between 25-50oC.

**Comment by KevinOConnor** [comment]
Okay.  This PR will still need a signed-off-by line.

-Kevin

**Comment by ayufan** [comment]
@KevinOConnor Sorry for delay. It is updated.

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Comment by DK-1989** [comment]
How do I add this in printer.cfg? 

[temperature_sensor MCU]
sensor_type: ADC_IN18
min_temp: 0
max_temp: 100

**Comment by ayufan** [comment]
@DK-1989 Update to latest klipper and just do:

```toml
[temperature_sensor cheetah_v2]
sensor_type: temperature_mcu
```

**Comment by ayufan** [comment]
@DK-1989 I'm missing what error do you see. The `cheetah_v2` is just a name. Nothing more.

**Comment by ayufan** [comment]
@DK-1989 

Did you update firmware on MCU?

**Comment by DK-1989** [comment]
mcu(stm32f401xc)
Versie: v0.10.0-408-g2c441b45

**Comment by DK-1989** [comment]
Okay thanx mate I got it working! reflashed klipper with sd card, now mcu is updated :)

**Comment by ayufan** [comment]
@DK-1989 Good :)

**Pull request merged**
