### PR TITLE
Support for USART5 on STM32G0B1

### PR DESCRIPTION
**Pull request by Florin-Popescu**
Hello!

I'm using an SKR mini E3 V3 board and I needed to access the USART5 pins which are on PD2, PD3.
Thought it would be as simple as extending that configuration in Kconfig with my combination of pins, but that didn't work.

Many headaches later, turns out that the bits to enable/reset USART5 & 6 do not follow the rule from `stm32g0.c` regarding the offset from APBPERIPH_BASE, but needed to be added as exceptions similar to the USB and others.

While I've fixed the RCC bits for USART6 as well, I was only able to test the configuration I needed, USART5 on PD2, PD3. That's why I only included this in the Kconfig.

Hoping this saves other people some time.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  Adding support for USART5 seems useful.  Commits need to have a signed-off-by line though - see: https://www.klipper3d.org/CONTRIBUTING.html

-Kevin

**Comment by Sineos** [comment]
Any updates @Florin-Popescu?

**Comment by Florin-Popescu** [comment]
Fixed! Sorry about that.

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
