### PR TITLE
Skew_Correction.md typo

### PR DESCRIPTION
**Pull request by streetgt**
Fix typo

### CODE REVIEW

**Comment by JamesH1978** [comment]
Thank you for submitting a PR, pleas refer to point 3 in "What to expect in a review" in https://github.com/Klipper3d/klipper/blob/master/docs/CONTRIBUTING.md and provide a signed off by line.

Thanks
James

**Review by thijstriemstra — APPROVED** [review]
thanks!

> Thank you for submitting a PR, pleas refer to point 3 in "What to expect in a review

good point

**Comment by streetgt** [comment]
> thanks!
> 
> > Thank you for submitting a PR, pleas refer to point 3 in "What to expect in a review
> 
> good point

The PR is self explenatory and is no harmfull to the codebase, I don't see any point of justification when it's just a typo....

**Comment by thijstriemstra** [comment]
> provide a signed off by line.

is what I meant

**Comment by streetgt** [comment]
Do whatever you guys want, not going to waste time on this and any other Klipper contribution, jesus.

**Comment by KevinOConnor** [comment]
I made the corresponding change to the docs (commit 9a940ffc).

-Kevin

**Pull request closed without merging**
