### PR TITLE
Add spi_flash board definition for Mellow FLY Gemini V2

### PR DESCRIPTION
**Pull request by s6t**
Just a board configuration for Mellow FLY Gemini V2 to be able to flash via sd card.

### CODE REVIEW

**Comment by Sineos** [comment]
Thanks. At a minimum, this would need a signed-off line. See https://www.klipper3d.org/CONTRIBUTING.html#what-to-expect-in-a-review No 3

Please also confirm that the flash process works fully automatically, i.e. the board is reset after a successful flash and no manual intervention is needed.

**Comment by Arksine** [comment]
Thanks, the change looks ok to me.  Before I can approve it the commit needs a signature acknowledging the acceptance of the DCO per the [contribution guidelines](https://www.klipper3d.org/CONTRIBUTING.html#format-of-commit-messages).

**Comment by s6t** [comment]
Here is the console output from successful flash
`
$ ./scripts/flash-sdcard.sh /dev/ttyACM0 fly-gemini-v2
Flashing /opt/klipper/klipper/out/klipper.bin to /dev/ttyACM0
Checking FatFS CFFI Build...
Connecting to MCU...Connected
Checking Current MCU Configuration...Done
MCU needs restart: is_config=1, is_shutdown=0
Attempting MCU Reset...Done
Waiting for device to reconnect....Done
Connecting to MCU...Connected
Initializing SD Card and Mounting file system...

SD Card Information:
Version: 2.0
SDHC/SDXC: True
Write Protected: False
Sectors: 15486976
manufacturer_id: 159
oem_id: TI
product_name: 00000
product_revision: 0.0
serial_number: 00009232
manufacturing_date: 11/2020
capacity: 7.4 GiB
fs_type: FAT32
volume_label: b''
volume_serial: 1718239260
Uploading Klipper Firmware to SD Card...Done
Validating Upload...Done
Firmware Upload Complete: firmware.bin, Size: 26364, Checksum (SHA1): 4BB779BF932369D3CA309D2D94B7DD6920909599
Attempting MCU Reset...Done
Waiting for device to reconnect...........Done
Connecting to MCU...Connected
Verifying Flash...Version matched...Done
Firmware Flash Successful
Current Firmware: v0.10.0-525-ge9c83d66-dirty-20220720_122958-voron0
Attempting MCU Reset...Done
SD Card Flash Complete
`

**Comment by gielbloks** [comment]
pls help me.. being working on putting sd cards in out changing klipper.bin into firmware.bin on 10 different sd cards formatted to 32 k clusters.. everything by the book.. i can not get it to flash... 

Gemini 2 board new out of the box.. 
the intergrated h5 sbc is 20 minutes off work..but connection to the stm32f4 is a nightmare..

flipped the dip switches also between every try.. 
but ziltch nothing... 

if somebody can talk me through i have a nice thing in reward for it!!! (working on it dor 2 years and first prototype is ready..)

**Comment by Sineos** [comment]
@gielbloks, please open a thread on https://klipper.discourse.group. This is the wrong place

**Comment by gielbloks** [comment]
thanks already done that 🙂

groeten/regards

Giel Bloks

Vergert 81
6662DX ELST
________________________________

**Comment by s6t** [comment]
@gielbloks, haven't found the thread on discourse, maybe you can share a link

**Comment by gielbloks** [comment]
going to ship ít back ànd goin for btt manta board. mellow is just not as tough as bigtreetech is ..



groeten/regards

Giel Bloks

Vergert 81
6662DX ELST
________________________________

**Comment by gielbloks** [comment]
it seems the mcú is déad

groeten/regards

Giel Bloks

Vergert 81
6662DX ELST
________________________________

**Pull request merged**
