### PR TITLE
Update generic-bigtreetech-skr-mini-e3-v3.0.cfg

### PR DESCRIPTION
**Pull request by MilesTheGOAT**
SKR Mini E3 V3 Config Corrections

I have made some changes to the current SKR Mini E3 V3 config example that helps to eliminate some troubles I was facing after installation, and using the sample config:

- Removed stealth from the extruder motor to stop under-extrusion issues
- Changed bed sensor to correct stock Ender 3 sensor

Signed-off-by: Miles Pawar slab.paged-0p@icloud.com

### CODE REVIEW

**Comment by JamesH1978** [comment]
Thank you for submitting a PR, please provide a signed off by line as outlined in https://github.com/Klipper3d/klipper/blob/master/docs/CONTRIBUTING.md

Changes look fine, but please remove the comments

Thanks
James

**Comment by MilesTheGOAT** [comment]
> Thank you for submitting a PR, please provide a signed off by line as outlined in https://github.com/Klipper3d/klipper/blob/master/docs/CONTRIBUTING.md
> 
> Changes look fine, but please remove the comments
> 
> Thanks James

Hi James,

Updated the config and removed the comments and reformatted the request.

Miles

**Review by JamesH1978 — APPROVED** [review]
Looks fine to me, user might not want stealth, and spread is default, and as this is a board primarily meant for ender replacement, then they stock ender thermistor makes sense.

Thanks
James

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
