### PR TITLE
config: Add Anycubic Kobra Plus

### PR DESCRIPTION
**Pull request by dkaser**
This adds support for the Anycubic Kobra Plus, based on the HC32F460 microcontroller.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  In general it seems fine to me.  The config file should use `:` instead of `=` syntax though - see https://www.klipper3d.org/Example_Configs.html point 7d.

Also, I'm a little leery of listing manufacturer product names in the test scripts.  Perhaps use a filename of `test/configs/hc32f460-serial-PA3PA2.config` (or something similar).

-Kevin

**Review by JamesH1978 — COMMENTED** [review]
unfortunately I do not think a configuration that recommends a hard modification to the print board is a good fit for klipper, we like to make sure people have the choice to return to stock, so i am not sure this modification is one the average user will want to perform or have to reverse. @KevinOConnor can you weigh in on this one?

Thanks
James

**Comment by dkaser** [comment]
I made the requested updates to the files.

As for the hard modification, I agree that it's not ideal, but as long as users know the modification and its consequences (which are described in the comments to the config file) I think it's OK to give them the choice if they want to do it or not.

**Comment by JamesH1978** [comment]
fair enough then :) i will review

Thanks
James

**Review by JamesH1978 — APPROVED** [review]
Looks fine to me,

Thanks
James

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
