### PR TITLE
Update printer-anycubic-vyper-2021.cfg

### PR DESCRIPTION
**Pull request by JackyHe398**
Add beeper, LED support, change homing speed

module: printer-anycubic-vyper-2021.cfg

Add LED and beeper support

Signed-off-by: He King Hung hekinghung@gmail.com

### CODE REVIEW

**Comment by ld3300** [comment]
You should probably remove all of the other changes your file is making to the existing commit so only the beeper part get pulled.

**Comment by JackyHe398** [comment]
> You should probably remove all of the other changes your file is making to the existing commit so only the beeper part get pulled.

maybe I simply remove the virtual SD card part and change the headline. The value I edit is following the suggested value of anycubic/ the tested value. If it is a really big problem then pls tell me. I will change it. But if not, just simply leave it there~ Thank you for your advice

**Review by Fisheiyy — CHANGES_REQUESTED** [review]
Everything needs to be changed back to default except for the [output_pin BEEPER_PIN] section

**Comment by JackyHe398** [comment]
> Everything needs to be changed back to default except for the [output_pin BEEPER_PIN] section

ok

**Review by Fisheiyy — APPROVED** [review]
Good, now we wait to see if Kevin will merge this or not

**Comment by KevinOConnor** [comment]
It's fine with me, but:
1. Commits need to have a signed-off-by line containing your full real name: https://www.klipper3d.org/CONTRIBUTING.html
2. Example configs should not explicitly set values to their defaults: https://www.klipper3d.org/Example_Configs.html point 7f.

@cryd-s - do you have any comments on this?

-Kevin

**Comment by JackyHe398** [comment]
module: printer-anycubic-vyper-2021.cfg

Add LED and beeper support

Signed-off-by: He King Hung hekinghung@gmail.com

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
