### PR TITLE
Exclude Objects

### PR DESCRIPTION
**Pull request by troy-jacobson**

### CODE REVIEW

**Comment by troy-jacobson** [comment]
This is a cleaned up branch which replaces https://github.com/Klipper3d/klipper/pull/4716

**Comment by Arksine** [comment]
I'll take a look this when I get a chance, I'm currently swamped.  FWIW the, tests should probably be in their own commit, and it appears that they are failing.

**Comment by Arksine** [comment]
I will be reviewing this, however it will need to pass CI first.

**Comment by CODeRUS** [comment]
sorry to bother, but what the progress here? :D

**Comment by TheSeven** [comment]
I tried to look into this a while ago and couldn't find an obvious problem by just staring at the code. I.e. I couldn't find a reason why the tests behaved the way they did (they just seemed to completely ignore exclusion.)
On real hardware this appears to be working just fine. Not sure what the deal is. Suspecting some kind of issue with the test itself, but I'm not familiar enough with this project to figure out what.

**Comment by maz0r** [comment]
> sorry to bother, but what the progress here? :D

check the other  pr #5413

**Pull request closed without merging**
