### PR TITLE
Add mixing extruder support

### PR DESCRIPTION
**Pull request by matyay**
This PR adds support for color mixing extruders. It is a continuation of https://github.com/KevinOConnor/klipper/pull/3920 with fixed bugs and added features.

It especially adds automatic retraction processing for mixing extruders as it requires special handling to be done correctly.

### CODE REVIEW

**Comment by binarylefmart** [comment]
Hi @matyay, i tested the Branch but when i put the sample macro on my printer.cfg, this kill my mcu communication, i the nothing on klippy.log.
Have an idea ?

**Comment by matyay** [comment]
@binarylefmart Hmm, Can you attach your config and `klippy.log`? When does the communication with MCU breaks? right from the beginning or when you issue some commands?

**Comment by binarylefmart** [comment]
https://paste.ofcode.org/DkdYWRHdGPKkvVExP2xxix

here is the file,it's weird it is like klipper lost the serial or have wrong script.

**Comment by binarylefmart** [comment]
always have the same issue, and have one too when i enable the extended g1 line.

**Comment by binarylefmart** [comment]
PrtScr capture
PrtScr capture_2
PrtScr capture_3

**Comment by matyay** [comment]
@binarylefmart Yeay, try removing the `extended_g1` option completely. It shouldn't be there.

**Comment by binarylefmart** [comment]
When i remove it like i said, have the mcu issue

**Comment by KevinOConnor** [comment]
Thanks.  My high-level feedback at this time is that we need to implement some architectural changes to Klipper's treatment of extruder stepper motors before we can add enhancements in this area.  Currently the klipper `extruder` config section defines the parameters to a hotend, a heater, a temperature sensor, and an extruder stepper motor.  I think we need a more clear abstraction so that it is possible to better control "extruder stepper motors".  That work should improve future mixing extruder support as it would not require the user to define multiple dummy "extruder" sections.

-Kevin

**Comment by KevinOConnor** [comment]
FYI, this architectural work also effects #4489, #4082, and #3920.

-Kevin

**Comment by KevinOConnor** [comment]
Thanks.  I'm not sure what the state of this PR is.  If there is still interest in this topic then the PR will need to be updated and a reviewer will need to volunteer to review it ( https://www.klipper3d.org/CONTRIBUTING.html ).  Unfortunately, due to time constraints on my side it is unlikely I will be reviewing this PR.

A good place to discuss this PR, get testers, and engage a reviewer is on the Klipper Discourse server ( https://www.klipper3d.org/Contact.html ).

-Kevin

**Comment by matyay** [comment]
Hi, I'm willing to continue the work on this feature but I'm short on time right now. Besides that I need to do some work on my 3D printer which has the mixing hotend, otherwise I won't be able to test the code.

**Comment by ETE-Design** [comment]
@matyay Good to hear that your back, and can work on again mabye in a not so far away future... Really would like to have this feature added to Klipper

**Comment by KevinOConnor** [comment]
FYI, #5143 makes it possible to call SET_EXTRUDER_STEP_DISTANCE on extruder_stepper objects, which may make it possible to implement mixing extruders via extruder_stepper objects.

-Kevin

**Pull request closed without merging**
