### PR TITLE
resonance_tester: Fix chips selection, add accel_per_hz selection

### PR DESCRIPTION
**Pull request by MRX8024**
-The current code does not have the option to "live" select a non-adxl345 `chips` when running `TEST_RESONANCES`, since it adds the adxl prefix by default.
-Added the ability to "live" select `accel_per_hz` when running `TEST_RESONANCES`.
-Minor fixes in the documentation.

Signed-off-by: Maksim Bolgov maksim8024@gmail.com

### CODE REVIEW

**Comment by nefelim4ag** [comment]
Every commit is expected to have a sign-off line.
PR on the other hand can just have a basic description, arguing, and description of a problem:
why it is a problem and how you are trying to solve it.

Also, take a look at: https://www.klipper3d.org/CONTRIBUTING.html
Specifically the commit format.

Thanks.

**Comment by MRX8024** [comment]
Thanks for the tip, I think I fixed the formatting of the commits

**Comment by dmbutyugin** [comment]
Thanks. I think this makes sense. However, given that this is a not a backwards-compatible change, I think it should be mentioned in `docs/Config_Changes.md` that the `CHIPS=` parameter for `TEST_RESONANCES` and `SHAPER_CALIBRATE` commands must specify the full accelerometer name(s).

**Comment by MRX8024** [comment]
> the full accelerometer name(s).

Do you want me to add a straight `CHIPS=<full_chip_name>`, or just description?
The doc already mentions: "for example `CHIPS="adxl345, adxl345 rpi"`".
Thanks

**Comment by dmbutyugin** [comment]
I think the G-Codes documentation is OK already. But since this is a change that will break any existing usages of `CHIPS` parameter, it is better to document this in `docs/Config_Changes.md` (it says 'config', however breaking gcode changes are also documented there).

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
