### PR TITLE
Bugfix: z_tilt: Do not adjust motors when tolerance is met.

### PR DESCRIPTION
**Pull request by DxCx**
Hey!

So i noted that after tolerance is met, motors are being adjusted one last time and not always really fix the tilt but make it worse. (and also, not being checked right after) with this patch im getting much better bed meshes after z_tilt adjust is done.

### CODE REVIEW

**Comment by legend069** [comment]
can you upload the log or the z movement adjustments?

**Comment by DxCx** [comment]
yeah but mainly i noted that if i do Z_TILT_ADJUST right after it wont change anything just tell me im good under tolerance for 2-3 times until there is what seems to be related to probe accuracy and then it will tilt again (but it starts very close), while without this fix it will adjust motors each time i run Z_TILT_ADJUST usually the first one will be off already.
when i get back to the printer i'll repeat the tests and upload log

**Comment by DxCx** [comment]
also im not familiar with other tilt mechanizem in klipper, i just know they are there, but i think they might want to do something similar as well, i just cant test it so i didnt touch it..

**Comment by DxCx** [comment]
```
05:29:42
Retries: 0/10 Probed points range: 0.001563 tolerance: 0.009000
05:29:42
probe at 460.000,60.000 is z=0.804146
05:29:41
probe at 460.000,60.000 is z=0.803208
05:29:39
probe at 460.000,60.000 is z=0.801021
05:29:33
probe at 285.000,470.000 is z=0.803521
05:29:32
probe at 285.000,470.000 is z=0.803833
05:29:31
probe at 285.000,470.000 is z=0.798521
05:29:24
probe at 60.000,60.000 is z=0.805083
05:29:23
probe at 60.000,60.000 is z=0.804771
05:29:22
probe at 60.000,60.000 is z=0.804146
05:29:18
Z_TILT_ADJUST
05:29:00
Retries: 0/10 Probed points range: 0.003125 tolerance: 0.009000
05:29:00
probe at 460.000,60.000 is z=0.805708
05:28:59
probe at 460.000,60.000 is z=0.805396
05:28:58
probe at 460.000,60.000 is z=0.801646
05:28:51
probe at 285.000,470.000 is z=0.806958
05:28:50
probe at 285.000,470.000 is z=0.808521
05:28:49
probe at 285.000,470.000 is z=0.804771
05:28:43
probe at 60.000,60.000 is z=0.803833
05:28:41
probe at 60.000,60.000 is z=0.804146
05:28:40
probe at 60.000,60.000 is z=0.802896
05:28:36
Z_TILT_ADJUST
05:28:31
Retries: 0/10 Probed points range: 0.005313 tolerance: 0.009000
05:28:31
probe at 460.000,60.000 is z=0.806021
05:28:30
probe at 460.000,60.000 is z=0.803521
05:28:29
probe at 460.000,60.000 is z=0.799771
05:28:22
probe at 285.000,470.000 is z=0.807271
05:28:21
probe at 285.000,470.000 is z=0.808208
05:28:20
probe at 285.000,470.000 is z=0.803833
05:28:14
probe at 60.000,60.000 is z=0.809771
05:28:12
probe at 60.000,60.000 is z=0.808833
05:28:11
probe at 60.000,60.000 is z=0.808833
05:28:07
Z_TILT_ADJUST
05:28:02
Retries: 2/10 Probed points range: 0.007812 tolerance: 0.009000
05:28:02
probe at 460.000,60.000 is z=0.809771
05:28:01
probe at 460.000,60.000 is z=0.807271
05:28:00
probe at 460.000,60.000 is z=0.803521
05:27:53
probe at 285.000,470.000 is z=0.811646
05:27:52
probe at 285.000,470.000 is z=0.811021
05:27:51
probe at 285.000,470.000 is z=0.808833
05:27:45
probe at 60.000,60.000 is z=0.804771
05:27:43
probe at 60.000,60.000 is z=0.803208
05:27:42
probe at 60.000,60.000 is z=0.801646
05:27:36
Making the following Z adjustments:
stepper_z = 0.010672
stepper_z1 = -0.009458
stepper_z2 = 0.001298
05:27:36
Retries: 1/10 Probed points range: 0.016875 tolerance: 0.009000
05:27:36
probe at 460.000,60.000 is z=0.801727
05:27:35
probe at 460.000,60.000 is z=0.801102
05:27:34
probe at 460.000,60.000 is z=0.797664
05:27:27
probe at 285.000,470.000 is z=0.791727
05:27:26
probe at 285.000,470.000 is z=0.791727
05:27:25
probe at 285.000,470.000 is z=0.787352
05:27:19
probe at 60.000,60.000 is z=0.809227
05:27:17
probe at 60.000,60.000 is z=0.808602
05:27:16
probe at 60.000,60.000 is z=0.807352
05:27:10
Making the following Z adjustments:
stepper_z = 0.179534
stepper_z1 = 0.102336
stepper_z2 = 0.183838
05:27:10
Retries: 0/10 Probed points range: 0.066562 tolerance: 0.009000
05:27:10
probe at 460.000,60.000 is z=0.976875
05:27:09
probe at 460.000,60.000 is z=0.975625
05:27:08
probe at 460.000,60.000 is z=0.972500
05:27:01
probe at 285.000,470.000 is z=0.909062
05:27:00
probe at 285.000,470.000 is z=0.909375
05:26:59
probe at 285.000,470.000 is z=0.909062
05:26:53
probe at 60.000,60.000 is z=0.973125
05:26:51
probe at 60.000,60.000 is z=0.972187
05:26:50
probe at 60.000,60.000 is z=0.970312
05:26:47
Z_TILT_ADJUST
```

This is after my patch, without it, if i Z_TILT_ADJUST one after another, it will adjust motors all the time and not keep the correct form, while now, as u can see, it tilted couple of times to get to position, and since then because its on position it wont need to adjust anything further

**Comment by DxCx** [comment]
> I think the same problem applies to QGL
> 
> ```
> Retries: 1/5 Probed points range: 0.007500 tolerance: 0.007500
> Making the following Z adjustments:
> stepper_z = 0.001050
> stepper_z1 = 0.011025
> stepper_z2 = -0.011025
> stepper_z3 = -0.001050
> Average: 7.495950
> Actuator Positions:
> z: 7.494900 z1: 7.484925 z2: 7.506975 z3: 7.497000
> Gantry-relative probe points:
> 0: 7.494700 1: 7.492200 2: 7.499700 3: 7.497200
> ```

i tend to agree, i can see here that it will adjust and then do the check for tolorance (without remeasure), meaning the positions which met the tolorance are now changed, i wrote above that probably other tilting mechanizem are also suffering from this bug, but i could not test this properly on all of them as i have only z_tilt configured and avial on my system..
if i would be told which tilt stuff should be effected i can try and fix them all but i'll need help with confirming the fix.. i know that z_tilt had this issue and now its ok =)
also looks like this PR doesnt get attention from klipper developer(s) altough its bugfix and not new feature :\

**Comment by KevinOConnor** [comment]
All PRs will need a reviewer to perform a review - see https://www.klipper3d.org/CONTRIBUTING.html .

This isn't something I'll take up reviewing at this time.  I can say at a minimum that this involves a user facing change and thus would need to be documented in docs/Config_Changes.md .  It's also not clear to me the high-level benefit to this change - it seems to me to be a different behavior, but not necessarily an improved behavior.

-Kevin

**Comment by DxCx** [comment]
> All PRs will need a reviewer to perform a review - see https://www.klipper3d.org/CONTRIBUTING.html .
> 
> This isn't something I'll take up reviewing at this time. I can say at a minimum that this involves a user facing change and thus would need to be documented in docs/Config_Changes.md . It's also not clear to me the high-level benefit to this change - it seems to me to be a different behavior, but not necessarily an improved behavior.
> 
> -Kevin

Hey @KevinOConnor, first of all, thanks for your time, i was leading opensource project in my past i know how time consuming it is and how life just need to come first..
Secondly, i worked with klipper docs in the past, totally missed this contribution page,
 ill look into it and add the relevant .md.. 

Ill explain the bug better so it will be more clear.
Code today will:
1. Measure Z height
2. Make the caculation of required "motor adjustment"
3. Motor adjust
4. Check if tolorence is met, stop the process with success, if too many retries/fail probes it will fail.

Now the problem with that is that step 3 is only trying to make adjustment better, but sometimes it will give results which are worse then before, and tolerance is not being checked again right after this final adjustment.

I am using very small tolorence on my system, and can say that most of the times this final adjustment is just taking me back.
So after investigation, i understood the easiest solution will be to replace step 3 and 4, adjust motors only if going for retry. This way if tolorence is met motors are untouched from this point.

My main concern is that there is more than one tiliting mechanizem, i have configured and working only z_tilt, but i had gutt feelings that others have the same bug and @profknivre 
Shows i was right.

I want to put the needed time into this PR and take it into completion but:
A. Ill need someone from your side to help with reviewing process and by telling me which more mechanizem might be effected.
B. I dont mind blindlessly fix every place i think i should by grepping for adjust motors, but i dont like untested code and i have only z_tilt to test upon.

**Comment by KevinOConnor** [comment]
I understand what you are reporting.  To wit, "I've measured the bed, it's in tolerance, and I don't want to make any further adjustments".

However, another approach is also valid - "I've measured an error in the bed, I wish to correct that error, and I'm confident the remaining error will be vanishing small so I do not wish to probe again".

Neither approach is defective.  They are just different.

I'm not prepared to make a judgement call on which of the above is "better".  There are thousands of printers running with the current algorithm. (It's used by both Z_TILT_ADJUST and QUAD_GANTRY_LEVEL.)  If I had to make a call, I'd say "leave current behavior as it is until there is overwhelming evidence of a benefit from a different approach".

If this is something that you think will provide a significant benefit, I think you'll probably want to raise awareness with the Klipper community (eg, https://www.klipper3d.org/Contact.html ).  Since there are thousands of printers using this tool, if you can provide a mechanism to measure a significant improvement, you should certainly be able to find many people willing to test and provide feedback.  Since this code was written by the Voron team (and used on many Voron printers) you may also wish to raise it there.

-Kevin

**Comment by legend069** [comment]
if i may make a suggestion,
a beta change could be implemented, the user would just need to insert the "z_tilt_beta " into their printer.cfg as it would default to false, any user wanting to try the "new feature" they can simply add the new line into their config to try it.

i would be happy to try it, as i have the tools to confirm adjustments.


```
verboosetypes = {'True': 'True', 'False': 'False'}
self.z_tilt_beta = config.getchoice('z_tilt_beta ', verboosetypes, 'False')

if self.z_tilt_beta == 'True':
       if result == "retry":
            self.z_helper.adjust_steppers(adjustments, speed)
        return self.z_status.check_retry_result(result)
else:
        self.z_helper.adjust_steppers(adjustments, speed)
        return self.z_status.check_retry_result(
        self.retry_helper.check_retry([p[2] for p in positions]))
```

**Comment by DxCx** [comment]
> I understand what you are reporting. To wit, "I've measured the bed, it's in tolerance, and I don't want to make any further adjustments".
> 
> However, another approach is also valid - "I've measured an error in the bed, I wish to correct that error, and I'm confident the remaining error will be vanishing small so I do not wish to probe again".
> 
> Neither approach is defective. They are just different.
> 
> I'm not prepared to make a judgement call on which of the above is "better". There are thousands of printers running with the current algorithm. (It's used by both Z_TILT_ADJUST and QUAD_GANTRY_LEVEL.) If I had to make a call, I'd say "leave current behavior as it is until there is overwhelming evidence of a benefit from a different approach".
> 
> If this is something that you think will provide a significant benefit, I think you'll probably want to raise awareness with the Klipper community (eg, https://www.klipper3d.org/Contact.html ). Since there are thousands of printers using this tool, if you can provide a mechanism to measure a significant improvement, you should certainly be able to find many people willing to test and provide feedback. Since this code was written by the Voron team (and used on many Voron printers) you may also wish to raise it there.
> 
> -Kevin

As someone who ran opensource project in my past and was part of apollo graphql core contributer, i totally understand where are u coming from.
With that said, today im a key engineer in big company, and just to get to open this PR it took me around 3 months, i don't have time to push the idea through the community and all i wanted as someone who believes in opensource is to contribute back.
I did like @legend069 (Thanks! Also for wanting to try it) solution though, this can be totally added as opt in option (skip_final_adjust for example) and then we can see how people react to it..
Wdyt about this direction? Also, which other tilt mechanisms might benift from this in your opinion? I can try to refine stuff over the weekend..

**Comment by dewi-ny-je** [comment]
It is in principle possible that the current approach "I measure an error, I want to correct it" leads to a worse error. Some systems may be nonlinear, or maybe the current setup has been achieved via methods which are more accurate and more complex than what is being used to probe. In these cases a correction can worsen the results.

While in principle possible, I'm surprised it happens with simple situation as a bed leveling. I would like to see practical examples...

Besides introducing an optional parameter "initial tolerance" which skips adjustment altogether, another option would be to provide a function "measure_tilt" which only probes and provides feedback. Maybe it could even be implemented as a macro, asking the probe to probe in different locations and output the results, since Jinja2 can also perform calculations on data, if needed.

Then based on the result the user (or an automatic macro) could call the original adjustment procedure.

**Comment by DxCx** [comment]
> While in principle possible, I'm surprised it happens with simple situation as a bed leveling. I would like to see practical setup leading to this case: I see the data above, but which system, which probes, which bed are in it?
> 

I am using v-core 3 (500x500), it has its bed mounted over 3 motors, the probe im using today and was used with this log is superpinda but when i originally did this patch i was using bltouch.

as i saw it, the algorithem is measuring points, calc differance, and only if differance is above tolerance it should adjust, but i am totally fine with how @KevinOConnor is looking at this, and i dont mind change it into any other optional behavior that will be acceptable by him, i think `skip_final_adjust` is the cleanest solution but i am waiting for him to reply before changing anything..

**Comment by KevinOConnor** [comment]
I'd guess that `skip_final_adjust` may be difficult to meet the project's goal that all config/command options are "high impact" - https://www.klipper3d.org/CONTRIBUTING.html#what-to-expect-in-a-review .

-Kevin

**Comment by DxCx** [comment]
> I'd guess that `skip_final_adjust` may be difficult to meet the project's goal that all config/command options are "high impact" - https://www.klipper3d.org/CONTRIBUTING.html#what-to-expect-in-a-review .
> 
> -Kevin

as you said on eralier comment, there are 2 different aproaches, one is safe, if tolrance is met, im good enough do not adjust any further, one is greedy, altough tolerance is met, i am confident enough to apply final adjusment anyway. 

where im coming from usually the safe option is the default option and the greedy one is there to enable further optimization by user demand.

you claimed that this is default for long time and it works for most systems, and that u dont want to change default, i get that.
so it was suggested to be in config option, optional in, maybe `skip_final_adjust` is a bad name, but i do think this option brings high impact as it gives the ability to trust the z_tilt algo results.

if this is not acceptable change, even as optional in (i am talking about the concept, we can define how to expose that at second stage), then please let me know and i'll just close the PR,
locally i enjoy it for some time now and it does wonders, and all i wanted is to contribute that back, but if its rejected then what can i do..

**Comment by dewi-ny-je** [comment]
If an additional config option is not acceptable, why not adding a command z_tilt_verify which can be run only by those interested in it before running the z_tilt_adjust?
The only downside is that probing takes place twice: for verification and then again for correction

**Comment by dewi-ny-je** [comment]
@5402 this seems to go nowhere, any luck you can rewrite it as macro, as I suggested above?

**Comment by DxCx** [comment]
> @DxCx this seems to go nowhere, any luck you can rewrite it as macro, as I suggested above?

I guess i can simply add dry_run parameter to z_tilt_adjust macro / add macro of z_tilt_verify but not sure how will that help and why would that be accepted..

**Pull request closed without merging**
