### PR TITLE
ledstrip support

### PR DESCRIPTION
**Pull request by csch0**
Wanted a way to setup a LED-Strip as easy as a neopixel.

```
[ledstrip my_ledstrip]
pin_RED: PB6
pin_GREEN: PB7
pin_BLUE: PB5

cycle_time: 0.01
hardware_pwm: false

initial_RED: 0
initial_GREEN: 0
initial_BLUE: 0
```

Afterwards you can use the `SET_LED LED=my_ledstrip red=1` command to control it.

This is my first submit to the project, so if I missed something please be gentle. ;)

### CODE REVIEW

**Comment by ld3300** [comment]
Hi @csch0,
I'm not smart enough to comment on the code.  However, you do need to add a "Signed-off-by:" statement to your commit comment.  You can see the format [here](https://www.klipper3d.org/CONTRIBUTING.html#format-of-commit-messages).
Best,
-David

**Comment by csch0** [comment]
> Hi @csch0, I'm not smart enough to comment on the code. However, you do need to add a "Signed-off-by:" statement to your commit comment. You can see the format [here](https://www.klipper3d.org/CONTRIBUTING.html#format-of-commit-messages). Best, -David

Thanks, changed it.

**Comment by mental405** [comment]
Might also consider renaming it to RGB_LED_Strip or something to avoid confusion.

**Comment by KevinOConnor** [comment]
Thanks.  PR #5374 implemented support for pwm controlled LEDs.

-Kevin

**Pull request closed without merging**
