### PR TITLE
Create printer-bq-prusa-i3-hephestos-2014.cfg

### PR DESCRIPTION
**Pull request by rcarmo**
This is a working config with full LCD and stepper settings (only thing missing is the kill switch, which did not appear to work)

### CODE REVIEW

**Comment by rcarmo** [comment]
I've since added and tested the kill pin, and defined a set of bed leveling points that still allow access to the screws on the stock bed.

**Comment by rcarmo** [comment]
Hello, I've done a self-review and this appears to tick all the boxes (also, it is my current working config). What else is needed?

**Comment by KevinOConnor** [comment]
Thanks.  Commits need to have a signed-off-by line containing your full real name - see https://www.klipper3d.org/CONTRIBUTING.html .

Also, I fear a name of "bq-prusa-i3" will lead to a ton of confusion as users with a "prusa i3" may look there first.  I think some file name that doesn't contain "prusa" would be needed.

-Kevin

**Comment by KevinOConnor** [comment]
For an old printer like this, maybe just call it `printer-hephestos-2014.cfg` and place the full name and wiki link in the comments at the top of the file?

-Kevin

**Comment by rcarmo** [comment]
Done. I left "bq" in the name sinceother configs also refer to the manufacturer, and "bq hephestos" returns a much nicer set of Google matches than the plain model name, so this might be easier to find that way.

**Comment by KevinOConnor** [comment]
Unfortunately, I had to revert this change.  The original commit did not add the config to the regression test cases and I could not simply add it myself as the config is not complete (at a minimum the mcu section is missing and the extruder pid settings are missing).

The config will need to be added to the regression test cases in order for it to be added to Klipper - see point 4 at https://www.klipper3d.org/Example_Configs.html .

-Kevin

**Comment by rcarmo** [comment]
Oh, ok. I’ll try to get those in later in the weekend.

**Pull request merged**
