### PR TITLE
Weight_scale: Enables load cells to weigh spools and other objects

### PR DESCRIPTION
**Pull request by clearchris**
Weight_scale: Enables load cells to weigh spools and other objects

Contains two extras modules and documentation.

weight_scale.py:
Configure a load cell adc as a weight scale. Filament or other
objects can be weighed and reported.  It handles all weighing
functions including calibration, scale tare and reading the
weight. This interface can not be used for load cell based homing.

arduino_adc.py:
Configure klipper to receive readings over i2c from an arduino
that is not configured as a Klipper MCU.  This is useful to get
readings from sensors and chips that are difficult to integrate
into klipper. One example is the HX711 load cell amplifier.

I have already completed integration to mainsail which adds a
scale display and tare function to the Miscellaneous panel.  A
mainsail PR is ready be sent pending this additon.  A screenshot is
in the Links section.

My specific target audience is anyone building the Valkyrie high
temperature printer (successor to the v-king by Roy) which contains
an integrated dry box and spool load cell.

The general target audience is anyone who has looked at a spool of
filament and wondered: "Is this print going to make it with the
filament I have left?"  Perhaps fewer people have looked at their
desiccant and wanted to weight it for water saturation, but I
plan on doing that also. I am looking forward to seeing how others
use it.

Another target audience is anyone looking to quickly integrate a sensor
into klipper that currently isn't supported, or can't be supported
easily.  The arduino_adc provides a generic module to easily import a
reading to klipper from devices which do have support by the very large
arduino ecosystem.

**Links:**

**Valkryie Scope Doc**
https://vkingprinter.com/project-valkyrie/
**Roy's Youtube Channel, with videos of the Valkyrie**
https://www.youtube.com/c/PRO3DESIGN
**Picture of Mainsail Load Cell Integration:**
https://drive.google.com/file/d/19ZtCDI5RWX6maxSyBihxYoMspzT_4sJR/view?usp=sharing

Signed-off-by: Chris Lombardi <clearchris@hotmail.com>

### CODE REVIEW

**Comment by clearchris** [comment]
Mainsail integration:  https://github.com/mainsail-crew/mainsail/pull/745

**Comment by KevinOConnor** [comment]
Thanks.  As high-level feedback, I'm not sure this is a good project direction for Klipper.  We can certainly add support for force and weight sensors to Klipper.  However, this PR seems to implement a new protocol interface with 3rd party code.  It's not clear that new protocol is widely used (or will be widely used).

In general, I think there are two other possible implementation paths that should be considered:
1. Directly implement force/weight sensors in Klipper (thus not requiring 3rd party code).
2. Or, use Klipper's existing API Server ( https://www.klipper3d.org/API_Server.html ) to interact with 3rd party code.  (Both 3rd party host and arduino code, and thus not requiring code changes to Klipper.)

-Kevin

**Comment by clearchris** [comment]
Working on some directly implemented adcs.  Closing for now.

**Comment by Sineos** [comment]
Might make sense to join efforts. See https://klipper.discourse.group/t/strain-gauge-load-cell-based-endstops/2134/33

**Comment by clearchris** [comment]
Thx, I was already in contact with one of them, and someone else found me because of opening this PR.  We are making pretty good progress.

**Pull request closed without merging**
