### PR TITLE
Add TronXY D01 Plus V2 Direct Drive Printer

### PR DESCRIPTION
**Pull request by mcowger**
Add TronXY D01 Plus V2 Direct Drive Printer

### CODE REVIEW

**Comment by JamesH1978** [comment]
If someone were to purchase a TronXY D01 Plus V2 would this have direct drive as standard, or is this a mod you have added yourself? 

Thanks
James

**Comment by mcowger** [comment]
The printer is available in 2 (relevant) variants:  With a direct drive or with Bowden style. 

There are no modifications to the printer that i have made.

**Comment by JamesH1978** [comment]
excellent, then someone will review it and make comment. We only allow stock printer configs so as not to confuse other users with same printer

Thanks
James

**Review by JamesH1978 — COMMENTED** [review]
Hi,

Apologies for the bot, i thought i had assigned myself.

Ok you have missed a couple of things, please review https://github.com/Klipper3d/klipper/blob/master/docs/CONTRIBUTING.md paying attention to the signed off by line, and we need you to check your submission conforms to the guidelines in https://github.com/Klipper3d/klipper/blob/master/docs/Example_Configs.md and you commit a change for the print regression test as layed out in that document.

Thanks
James

**Pull request closed without merging**
