### PR TITLE
config: Add Sovol SV06 Plus

### PR DESCRIPTION
**Pull request by hjmcnew**
config: Add printer-sovol-sv06-plus-2023.config

Add a configuration for the Sovol SV06 Plus. 

Signed-off-by:  Herb McNew <herb.mcnew@gmail.com>

### CODE REVIEW

**Comment by JamesH1978** [comment]
Thank you for submitting a PR, I have just one question why do you have a uart_address for each driver when they all use different uart pins, Is this a quirk of the board or does it work fine without this address being set?

Thanks
James

**Comment by hjmcnew** [comment]
> Thank you for submitting a PR, I have just one question why do you have a uart_address for each driver when they all use different uart pins, Is this a quirk of the board or does it work fine without this address being set?

Quirk of the board (I guess). If one comments out the uart_address and attempts to home they get `!! Unable to read tmc uart 'stepper_x' register IFCNT`

**Review by JamesH1978 — APPROVED** [review]
Thank you for confirming that uart_address is needed

Looks good to me,

thanks,
James

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
