### PR TITLE
scripts: Migrated shaper calibration scripts to Python3

### PR DESCRIPTION
**Pull request by dmbutyugin**
Also updated instructions to install python3-numpy and
python3-matplotlib Python packages.

Signed-off-by: Dmitry Butyugin <dmbutyugin@google.com>

### CODE REVIEW

**Comment by dmbutyugin** [comment]
Recent versions of Raspbian no longer provide Python2 versions of numpy and matplotlib packages. At the same time, Python3 versions of numpy and matplotlib were provided since at least stretch:
https://packages.debian.org/stretch/python3-numpy

So, this migration goes in line with a general direction of migrating Klipper to Python3.

FWIW, this change may break existing installations, for which the users will have to run the required installation commands
```
sudo apt update
sudo apt install python3-numpy python3-matplotlib
```

Unfortunately, I do not know a good way of notifying users about this change, since Config_Changes.md are, supposedly, for breaking changes in the config.

**Comment by emersonsc** [comment]
I had already tried to force the Python 3 versions using the commands above.

pi@exocube:~ $ sudo apt update
sudo apt install python3-numpy python3-matplotlib
Hit:1 http://archive.raspberrypi.org/debian bullseye InRelease
Get:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease [15.0 kB]
Fetched 15.0 kB in 1s (17.7 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-matplotlib is already the newest version (3.3.4-1).
python3-numpy is already the newest version (1:1.19.5-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

How ever, I still get this error:

pi@exocube:~ $ ~/klipper/scripts/calibrate_shaper.py /tmp/resonances_x_*.csv -o /tmp/shaper_calibrate_x.png
~/klipper/scripts/calibrate_shaper.py /tmp/resonances_y_*.csv -o /tmp/shaper_calibrate_y.png
Traceback (most recent call last):
  File "/home/pi/klipper/scripts/calibrate_shaper.py", line 11, in <module>
    import numpy as np, matplotlib
ImportError: No module named numpy
Traceback (most recent call last):
  File "/home/pi/klipper/scripts/calibrate_shaper.py", line 11, in <module>
    import numpy as np, matplotlib
ImportError: No module named numpy

Also tried the following, and got this error:

pi@exocube:~ $ python3 ~/klipper/scripts/calibrate_shaper.py /tmp/resonancesx.csv -o /tmp/shaper_calibrate_x.png
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "/home/pi/klipper/scripts/calibrate_shaper.py", line 11, in <module>
    import numpy as np, matplotlib
  File "/home/pi/.local/lib/python3.9/site-packages/matplotlib/init.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "/home/pi/.local/lib/python3.9/site-packages/matplotlib/rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "/home/pi/.local/lib/python3.9/site-packages/matplotlib/colors.py", line 56, in <module>
    from matplotlib import _api, cbook, scale
  File "/home/pi/.local/lib/python3.9/site-packages/matplotlib/scale.py", line 23, in <module>
    from matplotlib.ticker import (
  File "/home/pi/.local/lib/python3.9/site-packages/matplotlib/ticker.py", line 136, in <module>
    from matplotlib import transforms as mtransforms
  File "/home/pi/.local/lib/python3.9/site-packages/matplotlib/transforms.py", line 46, in <module>
    from matplotlib._path import (
ImportError: numpy.core.multiarray failed to import

**Comment by emersonsc** [comment]
pi@exocube:~ $ pip install numpy --upgrade
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (1.19.5)
Collecting numpy
  Using cached https://www.piwheels.org/simple/numpy/numpy-1.21.4-cp39-cp39-linux_armv7l.whl (12.2 MB)
Installing collected packages: numpy
Successfully installed numpy-1.21.4
pi@exocube:~ $ python3 ~/klipper/scripts/calibrate_shaper.py /tmp/resonancesx.csv -o /tmp/shaper_calibrate_x.png
Traceback (most recent call last):
  File "/home/pi/klipper/scripts/calibrate_shaper.py", line 174, in <module>
    main()
  File "/home/pi/klipper/scripts/calibrate_shaper.py", line 153, in main
    datas = [parse_log(fn) for fn in args]
  File "/home/pi/klipper/scripts/calibrate_shaper.py", line 153, in <listcomp>
    datas = [parse_log(fn) for fn in args]
  File "/home/pi/klipper/scripts/calibrate_shaper.py", line 19, in parse_log
    with open(logname) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/resonancesx.csv'
pi@exocube:~ $ ~/klipper/scripts/calibrate_shaper.py /tmp/resonances_x_*.csv -o /tmp/shaper_calibrate_x.png
~/klipper/scripts/calibrate_shaper.py /tmp/resonances_y_*.csv -o /tmp/shaper_calibrate_y.png
Traceback (most recent call last):
  File "/home/pi/klipper/scripts/calibrate_shaper.py", line 11, in <module>
    import numpy as np, matplotlib
ImportError: No module named numpy
Traceback (most recent call last):
  File "/home/pi/klipper/scripts/calibrate_shaper.py", line 11, in <module>
    import numpy as np, matplotlib
ImportError: No module named numpy

**Comment by KevinOConnor** [comment]
Thanks.  In general it seems fine to me.  However, can we make this change without breaking python2?  That is, can we leave the `from __future__ import print_function` line in the code.

-Kevin

**Comment by dmbutyugin** [comment]
> Thanks. In general it seems fine to me. However, can we make this change without breaking python2? That is, can we leave the `from __future__ import print_function` line in the code.

OK, I will do that. However, since this is a breaking change (changing the default python for the script, which may result in missing packages import error), it will require a user to explicitly run the script with python2, or to install missing packaged. And do you think it makes sense to add any notice about the changes into Config_Changes.md?

**Comment by KevinOConnor** [comment]
I don't see a harm in adding a note to Config_Changes.md .  If you don't want to add the note, I think that is also okay (as this procedure is done manually and I think it is reasonable to expect users to consult the documentation the next time they attempt the procedure).  So, I'll defer to your judgement on this.

-Kevin

**Comment by dmbutyugin** [comment]
Thanks! I've made the suggested changes, and I also added a note to Config_Changes.md

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
