### PR TITLE
thermocouple: implement sensor fault tolerance

### PR DESCRIPTION
**Pull request by ReXT3D**
thermocouple: Reworked Xorlev's PR max31865: attempt to recover from faults

This revises Xorlev's PR [thermocouple: max31865: attempt to recover from faults](https://github.com/Klipper3d/klipper/pull/4164) to address comments from @KevinOConnor.

I made the following functional changes to Xorlev's code:
1. Replaced user configurable rtd_consecutive_fault_limit with fixed CONSECUTIVE_FAULT_LIMIT = 3
2. MCU code changed to not transmit consecutive fault count to host
 
Algorithm: The host transmits CONSECUTIVE_FAULT_LIMIT to the MCU. The MCU counts consecutive faults. Host code reinitializes MAX31865 on each fault indication from MCU. If the RTD fault condition persists exceeding CONSECUTIVE_FAULT_LIMIT, the MCU will shutdown.

This modified code works fine in my setup during normal operation and when intentionally inducing intermittent RTD faults.  Code review should emphasize Python and Klipper coding conventions as I have not written any useful code in 12+ years and my experience is primarily in C.

Signed-off-by: Piotr Twarecki <gvvn1200@gmail.com>

### CODE REVIEW

**Comment by ReXT3D** [comment]
I modified `thermocouple.c` to address comments 1 & 3 based on my interpretation of MAX31855 fault flag described earlier.  Revisions to `spi_temperature.py` are pending feedback and guidance.

**Comment by BlackStump** [comment]
I am currently printing with this PR and no issues so far

**Comment by from-nibly** [comment]
Tried this to see if it would solve my RTD is shorted errors I was getting. However I'm getting different errors now. 

Here are my logs as an FYI

MAX31865: recovered from fault: RTD input is shorted
mcu 'mcu': Exception in serial callback
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/serialhdl.py", line 56, in _bg_thread
    hdl(params)
  File "/home/pi/klipper/klippy/extras/spi_temperature.py", line 63, in _handle_spi_response
    self._callback(last_read_time, temp)
  File "/home/pi/klipper/klippy/extras/heaters.py", line 83, in temperature_callback
    self.control.temperature_update(read_time, temp, self.target_temp)
  File "/home/pi/klipper/klippy/extras/heaters.py", line 193, in temperature_update
    temp_diff = temp - self.prev_temp
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
MAX31865: recovered from fault: RTD input is shorted
mcu 'mcu': Exception in serial callback
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/serialhdl.py", line 56, in _bg_thread
    hdl(params)
  File "/home/pi/klipper/klippy/extras/spi_temperature.py", line 63, in _handle_spi_response
    self._callback(last_read_time, temp)
  File "/home/pi/klipper/klippy/extras/heaters.py", line 83, in temperature_callback
    self.control.temperature_update(read_time, temp, self.target_temp)
  File "/home/pi/klipper/klippy/extras/heaters.py", line 193, in temperature_update
    temp_diff = temp - self.prev_temp
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
Unhandled exception during run
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 217, in run
    self.reactor.run()
  File "/home/pi/klipper/klippy/reactor.py", line 292, in run
    g_next.switch()
  File "/home/pi/klipper/klippy/reactor.py", line 340, in _dispatch_loop
    timeout = self._check_timers(eventtime, busy)
  File "/home/pi/klipper/klippy/reactor.py", line 158, in _check_timers
    t.waketime = waketime = t.callback(eventtime)
  File "/home/pi/klipper/klippy/extras/statistics.py", line 66, in generate_stats
    stats = [cb(eventtime) for cb in self.stats_cb]
  File "/home/pi/klipper/klippy/kinematics/extruder.py", line 223, in stats
    return self.heater.stats(eventtime)
  File "/home/pi/klipper/klippy/extras/heaters.py", line 130, in stats
    self.name, target_temp, last_temp, last_pwm_value)
TypeError: float argument required, not NoneType
MAX31865: recovered from fault: RTD input is shorted
mcu 'mcu': Exception in serial callback
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/serialhdl.py", line 56, in _bg_thread
    hdl(params)
  File "/home/pi/klipper/klippy/extras/spi_temperature.py", line 63, in _handle_spi_response
    self._callback(last_read_time, temp)
  File "/home/pi/klipper/klippy/extras/heaters.py", line 83, in temperature_callback
    self.control.temperature_update(read_time, temp, self.target_temp)
  File "/home/pi/klipper/klippy/extras/heaters.py", line 193, in temperature_update
    temp_diff = temp - self.prev_temp
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
Transition to shutdown state: Unhandled exception during run

**Comment by ReXT3D** [comment]
> Tried this to see if it would solve my RTD is shorted errors I was getting. However I'm getting different errors now.
> 
> Here are my logs as an FYI

Thanks for your feedback.  Unfortunately I am unable to reproduce your error at all in my setup.  When I simulate an error by shorting the RTD intermittently and then for longer duration I see the following in the logs:

```Stats 190801.4: gcodein=0  mcu: mcu_awake=0.002 mcu_task_avg=0.000005 mcu_task_stddev=0.000006 bytes_write=4626 bytes_read=18529 bytes_retransmit=9 bytes_invalid=0 send_seq=397 receive_seq=397 retransmit_seq=2 srtt=0.000 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=119997878 rpi: mcu_awake=0.001 mcu_task_avg=0.000010 mcu_task_stddev=0.000017 bytes_write=1125 bytes_read=5352 bytes_retransmit=0 bytes_invalid=0 send_seq=162 receive_seq=162 retransmit_seq=0 srtt=0.000 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=49998899 adj=49999834 Duet_Mini: temp=31.8 Raspberry_Pi: temp=46.3  sysload=0.05 cputime=10.554 memavail=3446632 print_time=31.285 buffer_time=0.000 print_stall=0 extruder: target=0 temp=26.1 pwm=0.000
Stats 190802.4: gcodein=0  mcu: mcu_awake=0.002 mcu_task_avg=0.000005 mcu_task_stddev=0.000006 bytes_write=4660 bytes_read=18807 bytes_retransmit=9 bytes_invalid=0 send_seq=400 receive_seq=400 retransmit_seq=2 srtt=0.000 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=119997876 rpi: mcu_awake=0.001 mcu_task_avg=0.000010 mcu_task_stddev=0.000017 bytes_write=1131 bytes_read=5368 bytes_retransmit=0 bytes_invalid=0 send_seq=163 receive_seq=163 retransmit_seq=0 srtt=0.000 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=49998898 adj=49999829 Duet_Mini: temp=31.8 Raspberry_Pi: temp=45.8  sysload=0.05 cputime=10.578 memavail=3446744 print_time=31.285 buffer_time=0.000 print_stall=0 extruder: target=0 temp=26.1 pwm=0.000
MAX31865: recovered from fault: RTD input is shorted
MAX31865: recovered from fault: RTD input is shorted
Stats 190803.4: gcodein=0  mcu: mcu_awake=0.002 mcu_task_avg=0.000005 mcu_task_stddev=0.000006 bytes_write=4714 bytes_read=19063 bytes_retransmit=9 bytes_invalid=0 send_seq=405 receive_seq=405 retransmit_seq=2 srtt=0.000 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=119997873 rpi: mcu_awake=0.001 mcu_task_avg=0.000010 mcu_task_stddev=0.000016 bytes_write=1137 bytes_read=5397 bytes_retransmit=0 bytes_invalid=0 send_seq=164 receive_seq=164 retransmit_seq=0 srtt=0.000 rttvar=0.000 rto=0.025 ready_bytes=0 stalled_bytes=0 freq=49998894 adj=49999809 Duet_Mini: temp=31.5 Raspberry_Pi: temp=44.8  sysload=0.05 cputime=10.604 memavail=3446744 print_time=31.285 buffer_time=0.000 print_stall=0 extruder: target=0 temp=26.1 pwm=0.000
MAX31865: recovered from fault: RTD input is shorted
MAX31865: recovered from fault: RTD input is shorted
MCU 'mcu' shutdown: Thermocouple ADC out of range
```

I am not sure what could be causing the error you are seeing, but it suggests that the reported temperature is not in a 'float' type.  Unfortunately I don't know Python sufficiently to completely understand your error logs.  I am also still waiting for additional feedback relating to Kevin's comment on invoking the `self._callback()` function.  Perhaps this is related.

**Comment by ReXT3D** [comment]
I am closing this since Kevin developed an alternate approach in his referenced PR.

**Pull request closed without merging**
