### PR TITLE
stm32: Fix USART3 ALT pinout on STM32G0

### PR DESCRIPTION
**Pull request by rakosi2**
I have a BTT E3EZ (STM32G0B1) and the UART on the TFT did not work. I have worked out that the ALT mux was not set correctly. This is the only board that I can verify with so I am not sure if this is a typo or if another chip needs it as AF7. I have not looked at the other USARTs since I can not verify it.

This will resolve this issue: https://github.com/bigtreetech/Manta-E3EZ/issues/8

image

Attila Rakosi <rattila5@hotmail.com>

### CODE REVIEW

**Comment by JamesH1978** [comment]
Thank you for submitting a PR, pleas refer to point 3 in "What to expect in a review" in https://github.com/Klipper3d/klipper/blob/master/docs/CONTRIBUTING.md and provide a signed off by line.

Thanks
James

**Comment by JamesH1978** [comment]
As mentioned over in the discord a lot of other stm32 chips use AF7 for this UART, Especially ones used in the 3D printing world like the F4 and the H7 series. You will need to rewrite your code to be specifically for the G0 series using AF0

Thanks
James

**Comment by rakosi2** [comment]
Set it to only change for STM32G0 series to AF0 and all other STM32 will use AF7
I have also fix the [Signed-off-by](https://github.com/Klipper3d/klipper/blob/master/docs/CONTRIBUTING.md#format-of-commit-messages)
Thank you [JamesH1978](https://github.com/JamesH1978)

**Comment by rakosi2** [comment]
I was unaware of it on the first commit, put it on the second commit and edited the first message with the signed-off at the end.

**Comment by KevinOConnor** [comment]
Sorry - I'm still not seeing it.  I need to see a line that says `Signed-off-by: Some Name <some@email.addr>`.  The line can be either in a comment here or in a commit message - I don't see a line like that in either location.

Cheers,
-Kevin

**Comment by rakosi2** [comment]
Signed-off-by: Attila Rakosi <rattila5@hotmail.com>

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
