### PR TITLE
Update Measuring_Resonances.md

### PR DESCRIPTION
**Pull request by tyler-cushing**
Typo correction

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  We'd need a signed-off-by line to commit this bug fix directly though - https://www.klipper3d.org/CONTRIBUTING.html

-Kevin

**Comment by Sineos** [comment]
Thanks @tyler-cushing 

While you are at it:

> Configure MPU-6000/9000 series With PICO
> 
> PICO I2C is set to 400000 on default. Simply add the following to the printer.cfg:
> 
> ```
> [mcu pico]
> serial: /dev/serial/by-id/<your PICO's serial ID>
> 
> [mpu9250]
> i2c_mcu: pico
> i2c_bus: i2c1a
> 
> [resonance_tester]
> accel_chip: mpu9250
> probe_points:
>     100, 100, 20  # an example
> 
> [static_digital_output pico_3V3pwm] # Improve power stability
> pin: pico:gpio23
> ```
> 
`
i2c_bus: i2c1a` should read `i2c_bus: i2c0a` to match the above connection scheme. Reported here: https://klipper.discourse.group/t/config-typo-in-documentation-for-input-shaping-for-pico/6389?u=sineos

**Comment by thijstriemstra** [comment]
This can be closed because PR #6032 fixed it.

> While you are at it:

I'll open a separate PR for this @Sineos

**Review by thijstriemstra — COMMENTED** [review]
This can be closed because PR #6032 fixed it.

**Pull request closed without merging**
