### PR TITLE
Add a configuration example file for the Fly-Gemini board

### PR DESCRIPTION
**Pull request by kluoyun**
config: Add a configuration example file for the Fly-Gemini board

Add a new sample configuration file for Mellow's Fly-Gemini all-in-one motherboard

Signed-off-by: Guanxi  Chen <xiaok@zxkxz.cn>

### CODE REVIEW

**Comment by Sineos** [comment]
Many thanks. Some remarks:
* Your contribution needs a sign off line according to https://github.com/Klipper3d/klipper/blob/master/docs/CONTRIBUTING.md including your full real name.
* Is the custom `step_pulse_duration` needed?
* You might want to cross check with https://github.com/Klipper3d/klipper/pull/4977 with respect to `hold_current`

**Comment by kluoyun** [comment]
> 非常感谢。一些备注：
> 
> * 您的贡献需要根据[https://github.com/Klipper3d/klipper/blob/master/docs/CONTRIBUTING.md 进行](https://github.com/Klipper3d/klipper/blob/master/docs/CONTRIBUTING.md)离线签名，包括您的全名。
> * `step_pulse_duration`需要定制吗？
> * 您可能想与[新的 TMC 文档](https://github.com/Klipper3d/klipper/pull/4977)进行交叉检查[：不要使用 hold_current；](https://github.com/Klipper3d/klipper/pull/4977)[避免对](https://github.com/Klipper3d/klipper/pull/4977)[ #4977](https://github.com/Klipper3d/klipper/pull/4977)进行[插值](https://github.com/Klipper3d/klipper/pull/4977)`hold_current`

Okay, Fly-Gemini needs step_pulse_duration,
I will modify the tmc configuration.
How can I solve the problem of invalid character "\n"
Thank you very much.

**Comment by Sineos** [comment]
Are you using a Windows editor with line ending `\r\n` instead of Unix style `\n`?

**Comment by kluoyun** [comment]
> Are you using a Windows editor with line ending `\r\n` instead of Unix style `\n`?

I edited it with VS Code, and I don’t know-what went wrong

**Comment by kluoyun** [comment]
It still reports an error after changing to LF

**Comment by Sineos** [comment]
Hmm, seems something went wrong here:
* There are modifications to  `config/example-corexz.cfg` 
* Still Windows line endings:
grafik

**Comment by kluoyun** [comment]
> Hmm, seems something went wrong here:
> 
> * There are modifications to  `config/example-corexz.cfg`
> * Still Windows line endings:
>   grafik

Ok thanks, i fixed it

**Comment by KevinOConnor** [comment]
Alas, PRs are on hold pending a new workflow for PRs - https://github.com/Klipper3d/klipper/pull/4939 .

-Kevin

**Pull request closed without merging**
