### PR TITLE
Feature/mixing extruder

### PR DESCRIPTION
**Pull request by konsumverweigerer**
Support for mixing (n-in 1-out) nozzles. It uses the sync to stepper/extruder and adjusts the rotation distance for the affected steppers.

### CODE REVIEW

**Comment by konsumverweigerer** [comment]
Ok I will look into points 1, 2 and 4 ...

Regarding 3.: I need to poll the initial rotation distance on the steppers and for that I need to make a method call on the ExtruderStepper (I added the get/set_rotation_distance in extruder.py for that) and this was the way I saw to get to the ExtruderSteppers having only their names.

Regarding 6.: Thanks for the pointer. I hadn't seen the this move_transform possibility and with that I could add the position hook only when needed: when an gradient is active (you are right this is only needed for gradients)

Regarding 6.: The G1 is only a demo how flexible the basic command is (eg. the duet g-code flavor also supports a "G1 Ennn:nnn:nnn..." command: https://docs.duet3d.com/User_manual/Reference/Gcodes) and it make manual testing much easier

Regarding 7.: The extruder_name is the extruder which is controlled by the G0/G1 commands and the steppers are the steppers I sync with the extruder. An alternative solution would be that the first stepper in the list is the extruder by convention.

for the 8.: when I do some reorganization I will probably remove the multiple mixing_extruders altogether since they are only for convenience to hold some presets for mixings and that could also easily be done with gcode macros if required

**Comment by KevinOConnor** [comment]
Thanks.

> I need to poll the initial rotation distance on the steppers and for that I need to make a method call on the ExtruderStepper (I added the get/set_rotation_distance in extruder.py for that) and this was the way I saw to get to the ExtruderSteppers having only their names.

I think a simpler way would be to add a `get_extruder_stepper()` method call to the extruder.py and extruder_stepper.py .

> The extruder_name is the extruder which is controlled by the G0/G1 commands and the steppers are the steppers I sync with the extruder. An alternative solution would be that the first stepper in the list is the extruder by convention.

I'm a little confused on the naming.  In Klipper today, an "extruder" is the combination of a "hotend heater" and an "extruder stepper".  Given that, wouldn't a "mixing extruder" be the combination of an "extruder" and n "extruder steppers"?  Why would a mixing extruder have multiple hotends?

-Kevin

**Comment by konsumverweigerer** [comment]
> > I need to poll the initial rotation distance on the steppers and for that I need to make a method call on the ExtruderStepper (I added the get/set_rotation_distance in extruder.py for that) and this was the way I saw to get to the ExtruderSteppers having only their names.
> 
> I think a simpler way would be to add a `get_extruder_stepper()` method call to the extruder.py and extruder_stepper.py .

That would be a solution for the extruder.py . But for the extruder_stepper.py that would not help since they are not registered with the printer as far as I see... 

> > The extruder_name is the extruder which is controlled by the G0/G1 commands and the steppers are the steppers I sync with the extruder. An alternative solution would be that the first stepper in the list is the extruder by convention.
> 
> I'm a little confused on the naming.  In Klipper today, an "extruder" is the combination of a "hotend heater" and an "extruder stepper".  Given that, wouldn't a "mixing extruder" be the combination of an "extruder" and n "extruder steppers"?  Why would a mixing extruder have multiple hotends?

exacly so extruder_name is the one extruder (which is used for the sync_to_extruder call target) and the steppers list are extruder steppers (where I set the rotation distance); one of which may be that extruder. Possibly I could figure out the extruder_name from the toolhead ...

**Comment by KevinOConnor** [comment]
> But for the extruder_stepper.py that would not help since they are not registered with the printer as far as I see...

All "extras" modules are registered in the `printer` object via the config name.  For example, `printer.lookup_object("extruder_stepper my_extra_stepper")`.

-Kevin

**Pull request closed without merging**
