### PR TITLE
docs: Updated accelerometer instructions

### PR DESCRIPTION
**Pull request by dmbutyugin**
Signed-off-by: Dmitry Butyugin <dmbutyugin@google.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  It looks good to me.  I'll give a few days for others to comment as well.

-Kevin

**Review by thijstriemstra — APPROVED** [review]
I'm looking into using klipper and was looking for more info on the resonance measurement and these additional docs will certainly help setup the mpu-9250 (i was going to use for a mecanum wheel robot but using it on a 3d printer is much cooler).

**Comment by Sineos** [comment]
I'm running Ubuntu on my Pi 3B and for whatever reason had troubles setting the I2C speed via `config.txt`. I ended up doing it directly in the device tree:
`fdtput --type u /boot/firmware/bcm2710-rpi-3-b-plus.dtb /soc/i2c@7e804000 clock-frequency 400000`

It may be worthwhile to provide an information how to check the actual I2C speed as verification that everything worked. One possible way is:

`echo $((16#$(xxd /sys/class/i2c-adapter/i2c-1/of_node/clock-frequency | awk '{print $2$3}')))`

**Comment by KevinOConnor** [comment]
Thanks.  I merged this PR.  I think we can add additional instructions via another PR on top.

-Kevin

**Pull request merged**
