### PR TITLE
CFG Elegoo Neptune 2S V1.3 with BLTouch and Mesh

### PR DESCRIPTION
**Pull request by oinosme**
This adds the configuration file for the Elegoo Neptune 2S on V1.3 with BLTouch and mesh enabled.

### CODE REVIEW

**Comment by just-trey** [comment]
@oinosme you may be interested in my pr. It covers both the 1.2 and 1.3 board. https://github.com/Klipper3d/klipper/pull/5213

**Comment by oinosme** [comment]
@just-trey thanks!

**Comment by KevinOConnor** [comment]
I'm not sure what the state of this PR is - at a minimum it would need to follow the guidelines at https://www.klipper3d.org/Example_Configs.html and https://www.klipper3d.org/CONTRIBUTING.html .

-Kevin

**Review by Fisheiyy — CHANGES_REQUESTED** [review]
I understand the point of this PR is to add a BLTouch config for the Neptune 2S V1.3 but unless it comes stock on the printer there is no point in adding a whole config for the printer, and this config is also very messy with lots of comments and the whole auto generated stuff at the bottom of the config which could mess up other peoples printers if they didnt know about it since it contains a bed mesh that isnt theirs and a z offset that isnt theirs.

**Comment by just-trey** [comment]
@Fisheiyy  @KevinOConnor  I appreciate the effort here but I believe the pr I submitted that was approved #5213 is sufficient and this config is not needed as I have comments that allow configurations for both board versions. @oinosme would you agree to close this PR?

**Pull request closed without merging**
