### PR TITLE
stats: add fan speed stats to log

### PR DESCRIPTION
**Pull request by CODeRUS**
Signed-off-by: Andrei Kozhevnikov <coderusinbox@gmail.com>

### CODE REVIEW

**Comment by Sineos** [comment]
Can you explain the rationale?
The log output would never reflect all changes and also does not align to any layer information or similar. Additionally, I do not see any diagnostic benefit, but I might be missing something.

**Comment by CODeRUS** [comment]
@Sineos exactly for diagnostic purposes. Most common cases are ADC out of range errors after turning on part cooling fan. Can see if temperature goes down (probably) cause of turning on cooling.

**Comment by CODeRUS** [comment]
then i can check logs to see if there any problems

firefox_2023-12-01_22-02-33
([via](https://coderus.openrepos.net/klipper_logs/2609c8da58a1d73fbf8e27f69845faa4))

**Comment by KevinOConnor** [comment]
Thanks.  As feedback, the code change here doesn't seem correct to me.  The main diagnostic case (that I'm aware of) is reporting the "layer cooling fan" speed, but this change doesn't add a `stats()` callback to the `PrinterFan()` class.  Maybe I'm missing something.  If we do want to add more diagnostic info, I think we should restrict it to just the layer fan, as most other fans (eg, heater_fan) are unlikely to be needed for diagnostics.

-Kevin

**Pull request closed without merging**
