### PR TITLE
Allow bedmeshing at 1mm spaced intervals.

### PR DESCRIPTION
**Pull request by kmobs**
With the advent of newer probes, meshing at 1mm may be something desired by the end user.

### CODE REVIEW

**Comment by theolas** [comment]
yes please

**Comment by Arksine** [comment]
This change looks ok to me.  Please see the [contributing documentation](https://www.klipper3d.org/CONTRIBUTING.html#format-of-commit-messages) for details on how to format the commit message.  Specifically, all commits need a signature with your real name and valid email address.  Thanks.

**Comment by kmobs** [comment]
Done. Thank you @Arksine.

**Comment by KevinOConnor** [comment]
Happy to commit this when it is thought to be ready.

-Kevin

**Comment by kageurufu** [comment]
@KevinOConnor I believe it is ready, and the commit now has a sign-off

**Comment by mental405** [comment]
assigning myself to review so kmobs will stop whining.

**Comment by mental405** [comment]
Seems like a trivial change since presently one could do a mesh at 1.01mm spaced intervals vs 1.00mm spaced intervals without issue. I see it as more or less a bug fix than a feature addition.

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
