### PR TITLE
Change of alias for heater_fan in multiple configs

### PR DESCRIPTION
**Pull request by JamesH1978**
This PR serves to fix a longstanding misnomer in some config files. Many configs state a nozzle_cooling_fan alias for what is usually a "hotend cooling fan". This causes ambiguity and confusion with the parts fan. I have identified all 24 files with this and changed them here.

Signed-off-by: James Hartley <james@hartleyns.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  In general, the change looks fine to me.  However, I wonder if `heatbreak_cooling_fan` may be more descriptive?

-Kevin

**Comment by JamesH1978** [comment]
Makes sense, but a lot of the community may not know what the heatbreak is... but i don't mind either one, its just that current description is just plain wrong or at least ambigous

James

**Comment by qwewer0** [comment]
I think in function it is a cooling fan for the heatbreaks heatsink, so <s>either</s> Kevin's `heatbreak_cooling_fan` idea <s>or heatsink_cooling_fan</s> would be more appropriate.
(`heatsink_cooling_fan` could be mistaken for the boards cooling, as most if not all has heatsinks for the drives)

**Comment by JamesH1978** [comment]
Ok, I agree :) files now changed to reflect `heatsink_cooling_fan`

Thanks
James

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
