### PR TITLE
Adding bed_screws to Ender 3

### PR DESCRIPTION
**Pull request by hatkyinc2**
Adding the bed_screws to Ender 3 by what I could measure mine.
This enables `BED_SCREWS_ADJUST`.

https://github.com/Klipper3d/klipper/blob/master/docs/Manual_Level.md#adjusting-bed-leveling-screws

Signed-off-by: Ofir Petrushka <ofir.petrushka@gmail.com>

### CODE REVIEW

**Comment by ld3300** [comment]
Please add the Signed-off-by: statement as require in the [Contributing Guidlines](https://www.klipper3d.org/CONTRIBUTING.html#format-of-commit-messages)

**Comment by hatkyinc2** [comment]
@ld3300 Thanks for having a look, is this ok now?

**Comment by ld3300** [comment]
Edit your original post comment and add the signed off by statement there.

**Comment by hatkyinc2** [comment]
Added

**Comment by qwewer0** [comment]
I'm not too sure about these values.
On my ender 3, the screws are 32.5mm inwards from the edge of the bed.

**Comment by hatkyinc2** [comment]
I measured it multiple times originally, probably could have taken pics, I don't know if they would always be consistent or this changes at some point (date in time where something in manufacturing changed, "versions" of the bed...) Also note this is original Ender 3 and not derivatives like pro, v2...

Honestly I don't mind if it's changed a few mm to either directions, it's only used for manual leveling and close is better than not having anything set IMHO. This is a template and might need adjusting, I think just having it makes it easier for people starting.

**Comment by rpodgorny** [comment]
is this in correct section? my ender3 config has the screw positions in [screws_tilt_adjust] :-O

**Comment by hatkyinc2** [comment]
As you can read in the referenced doc BED_SCREWS_ADJUST is used with manual leveling

screws_tilt_adjust is for ABL probes

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
