### PR TITLE
config: added stock location of bed_screws for neptune2(s)(d)

### PR DESCRIPTION
**Pull request by dhruvinsh**
This config change adds stock config of the screw location. It can be found [here](https://github.com/NARUTOfzr/ZNP-Robin-Nano-V1.2-V1.3/blob/master/Configuration%20files/Neptune%202/elegoo.txt#L34).

### CODE REVIEW

**Comment by JamesH1978** [comment]
Hi,

Please read https://github.com/Klipper3d/klipper/blob/master/docs/CONTRIBUTING.md and pay particular attention to the signed off by line.

Thanks
James

**Comment by dhruvinsh** [comment]
Thanks @JamesH1978  for notifying it. I have force pushed the commit and updated the commit message.

**Comment by KevinOConnor** [comment]
Thanks.  The change looks fine to me, but does this printer really have 5 screws under the bed?

@just-trey - do you have any comments?

-Kevin

**Comment by dhruvinsh** [comment]
Thank you for looking into this contribution.

No the printer does not have 5 screws. It has 4 physical screws. 5th is to provide a kind of backward compatibility of stock firmware. It serves a purpose to validate the other four screws since its location is set to the middle of the bed. If it does not seem fine then calibration can be started over and in some cases (like minute concave bed) it's very helpful.

**Comment by KevinOConnor** [comment]
Okay - seems a bit unusual to describe a fifth location, but I don't really have a particular preference.  (I don't own this printer.)

-Kevin

**Pull request closed without merging**
