### PR TITLE
WIP stm32h7 port, "Rescheduled timer in the past" error

### PR DESCRIPTION
**Pull request by D4SK**
I'm currently trying to port klipper to stm32h750 mcus and running into a "Rescheduled timer in the past" error.

I think I have most of it implemented, whats missing is SPI, USB and ADC control. I haven't looked much into the timer and irq handeling aspect, so this could be the problem. All the abstractions armcm_timer needs are provided by the cmsis library, and startup/communication works fine, so not sure where to start there. timer_read_time seems correct as well.

[klippy.log](https://github.com/KevinOConnor/klipper/files/5959837/klippy.1.log)
[klippy_shutdown00037.log](https://github.com/KevinOConnor/klipper/files/5959838/klippy_shutdown00037.log)

I already tried running at 200mhz instead of 400, and increasing the timeout in timer_dispatch_many from 1000us to 1000000us, both created the same error.
When connecting with console.py get_config returns is_shutdown=1

What could cause this, are there any other irregularities in the log I should look at?
Other than the clocks, are all times in the log in seconds?

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  Could you try a few things?

1. Go to a more simple setup by removing all the output() calls; don't modify any code outside of the new stm32h7 code (that is revert all the changes to sched.c, armcm_timer.c, etc.) ; disable HAVE_GPIO_ADC and HAVE_GPIO_SPI in Kconfig.  Some of the output() calls themselves are in areas of the code that could be invoked before the output() code itself is initialized.  I'm concerned the debugging itself could be causing problems.
2. Run the console.py code with the simpler binary and run the STATS command a few times and verify the reported mcu_frequency matches what it should.  Similarly run the `get_uptime` command from console.py a few times and verify the clock count is incrementing properly.  Verify the high count in `get_uptime` is properly incrementing every 2**32 ticks.
3. When the mcu reports a shutdown, if you run some other command (such as `end_group`) does the micro-controller always report the reason as "reschedule timer in the past"?
4. If you run `clear_shutdown` from the console.py tool, does the condition clear, or does it immediately go back into shutdown mode?  If it goes back into shutdown mode, what reason does it provide?

-Kevin

**Comment by ArkadiuszRaj** [comment]
@KevinOConnor  @D4SK  general question while porting to new MCPUs.

I have recently ordered from JLCPCB small tool board based on STM32G4, and a full fledge printer board of my desing with STM32H743 with general idea to port there STM32F4 variant of RRF. But RRF requires much more effort than Klipper, so I have turned here. 

For STM32 wouldn't that be beneficial to start using CMSIS/HAL in full respect, just as STM32CubeMX does while generating initialization code? I mean switching towards HAL abstraction?

**Comment by D4SK** [comment]
@KevinOConnor
1.Removed the debugging info. Disabling HAVE_GPIO_ADC or HAVE_GPIO_SPI caused a different error in serialhdl.py so i left it enabled. (compiling without HAVE_GPIO_SPI also required removing sensor_adxl345.c and spi_software.c from the makefile)
[log.log](https://github.com/KevinOConnor/klipper/files/5961387/log.log)

2. Stats returned freq=52505 and then gradually lower values, 27080 after ~20 sec. 
get_uptime returns very slowly rising clock values, doesn't overflow even after a couple of minutes. high stays at 0. I assume clock should be incremented at 400mhz instead. Does this mean the mcu is actually only running at 52505hz? If i run SystemCoreClockUpdate() (of the cmsis library) the SystemCoreClock variable correctly returns 400000000. What part of the code should I look at?

get_uptime
006.509: uptime high=0 clock=26829385
get_uptime
009.468: uptime high=0 clock=26954445
get_uptime
012.060: uptime high=0 clock=27072376
get_uptime
014.900: uptime high=0 clock=27198073
get_uptime
017.628: uptime high=0 clock=27319291
get_uptime
020.300: uptime high=0 clock=27433924
get_uptime
023.004: uptime high=0 clock=27557121
get_uptime
025.412: uptime high=0 clock=27645237

3,4 Mcu always reports "rescheduled timer in the past" as the shutdown reason, and immediately goes back to that state after clear_shutdown

@ArkadiuszRaj Not sure if there is good documentation for the HAL, I think it was used for a different stm32 mcu but got replaced in favour of a native implementation.

**Comment by KevinOConnor** [comment]
@D4SK - Ah, that is the root of the problem then.  The clock is running at such a low rate that the scheduler thinks it can't keep up.

I can think of a couple of reasons for that:
1. Perhaps the stm32h series needs some further initialization of the DWT timer.  (See `armcm_timer.c:timer_init()`.)
2. The clock to the ARM core is not setup correctly, and is actually running at a ~45Khz rate.  It would seem the peripheral clocks are setup as expected, because serial is actually working (if the peripheral clocks were wrong, you would have any communication).  But I guess it is possible the arm clock wasn't set correctly.

-Kevin

**Comment by KevinOConnor** [comment]
> For STM32 wouldn't that be beneficial to start using CMSIS/HAL in full respect, just as STM32CubeMX does while generating initialization code?

We used to use the HAL code and the conclusion I came to was that its code quality was low.  It was more effort and time to use it then to directly access the hardware.

-Kevin

**Comment by KevinOConnor** [comment]
Any further updates on this?

-Kevin

**Comment by D4SK** [comment]
Unfortunately not, but i may give this another shot soon.

Some things I had last tried:
- Initialization code for CYCCNT should really be correct, (some guides specify an additional LAR acces register which I also tried)
- when adding a bunch of periodic output() statements or other work the reported frequency increases to up to 1mhz
- Hard-fault register shows no faults
- Using HSI gives identical results

I didn't try much regarding the clock_setup, based on the assumption that the usart clock should be based on SYSCLK, maybe I should look into that regardless though.

**Comment by D4SK** [comment]
Just found the problem, the WFI instruction in irq_wait() enters CSleep mode, which stops the cpu clock (Reference Manual page. 291), and the cycle counter isn't incremented.

Unfortunately the sleep cycle counter  (DWT->SLEEPCNT) only has 8 bits, and also stays at 0.

Would an 'empty' loop similar to the fix be a viable solution? The current one only works with with optimizations off (frequency is reported correctly, and no errors occur with the mininal config)

**Comment by KevinOConnor** [comment]
If the WFI instruction is a problem, you can test with this code:
```
void
irq_wait(void)
{
    asm volatile("cpsie i\n    nop\n    cpsid i\n" ::: "memory");
}
```

-Kevin

**Comment by D4SK** [comment]
The "asm volatile("cpsie i\n    nop\n    cpsid i\n" ::: "memory");" works.
Thanks for all the help!

Not sure if there is interest in merging this. I'm planning to add spi and adc support within the next couple of months, but probably no i2c and usb support, (I have no way of testing it and it's not needed for my setup)

**Comment by KevinOConnor** [comment]
Seems like useful functionality worth adding.  It would need to pass the build tests though (and any code cleanups applied).

-Kevin

**Comment by D4SK** [comment]
The build tests should pass now, I also changed the base branch to master. Everything seems to work well, however I only tested this on an eval-board with a thermistor attached. From my point of view this is as ready as it will be for a while. I'm happy to answer any questions on how to get it running if anyone wants to try it. This should also run on stm32h743 mcus with minimal to no modifications.

Current limitations include:
  USB: not implemented
  I2C: not implemented
  SPI: not tested

Im using a script like this for flashing the mcu (with rst connected to gpio 23 etc.)
```bash
sudo systemctl stop klipper
make serialflash FLASH_DEVICE=/dev/ttyAMA1 RST=23 BOOT0=24
sudo systemctl restart klipper
```

In a couple of months I might test this in a printer, and make spi communication with TMC261-PA drivers work (hope thats not too much work).

**Comment by kpochwala** [comment]
I've got custom printer board with STM32F7, if H7 is not much different than F7 i can give it a try @D4SK

**Comment by D4SK** [comment]
@kpochwala unfortunately the STM32F7 series seems to have many differences, so this would probably require bigger changes. Could be the basis for another port though.

**Comment by kpochwala** [comment]
@D4SK ok, then I'll get my feet wet and try making a port. Can I catch you at Klipper discord and ask a few questions regarding porting to a new STM MCU?

**Comment by D4SK** [comment]
@kpochwala sure, Konstantin#3476 on discord

**Comment by kpochwala** [comment]
@D4SK Thanks, I've send an invitation (kpo#0834)

**Comment by KevinOConnor** [comment]
Thanks.  FWIW, I'm fine with adding the stm32h7 support to the master branch, but I think the changes would need to be "cleaned up" a little first.  In particular, we'll need to figure out a way to reduce the impact to code outside of the src/stm32/ directory.  Also, it would be good to break up the change into a few actionable commits (for example, one commit that adds the new lib/ code, a commit that makes changes to the generic code, a commit with the new stm32h7 code, spi support for the new stm32h7 code, stm32h7 adc support, etc.).  Breaking the change up is important as it makes it easier to find regressions via `git bisect` (should an issue occur).

Cheers,
-Kevin

**Comment by D4SK** [comment]
I cleaned it up a little, anything more I should look at? I will clean up the commit history later. I assume it is ok if some intermediate commits don't compile when configured for stm32h7.

**Comment by KevinOConnor** [comment]
Each commit really needs to be compilable on its own.  Otherwise, it breaks "git bisect".  It's possible to merge commits together, but ideally the lib changes, any changes outside src/stm32/, and changes in src/stm32/ would at a minimum be in separate commits.

-Kevin

**Comment by D4SK** [comment]
I rebased the commmits, let me know if there is any further changes i should make

**Comment by KevinOConnor** [comment]
Thanks.  Alas, I haven't gotten a chance to review this fully, and I suspect it's likely a week or so out before I will get to review it.

-Kevin

**Comment by D4SK** [comment]
No problem, I think this is also a protocol break, so it might make sense to wait and merge this together with other protocol changes.

**Comment by adelyser** [comment]
Any updates on this work?

I have a Biqu BX I would like to try this port out on, it runs the stm32h743. If I can help contribute do the work, I'd be happy to do so.

**Comment by D4SK** [comment]
@adelyser  you could check if you have a revision V chip / produced after apr. 2019 (a V is printed on the mcu below the part number, not a Y). If thats the case it should work more easily.

Go through 9def05d and check the datasheet if the adc pins match etc. Additionally an stm32h743 option should be added to Kconfig, so that cmsis uses the correct library. If there is a custom bootloader the Bootloader adress offset might also be different.
Not sure if the BIQU board gives access to uart pins. Otherwise you have to try to make communication work with the usb connection.

You should be able to flash the firmware with an st-link adapter. However I used the raspberry pi directly with stm32flash you can do that if you have access to specific uart pins.

**Comment by adelyser** [comment]
@D4SK I am trying to verify the silicon revision, it's likely a V chip, but I want to make sure. I have a heatsink on mine that I haven't removed yet.

I verified the adc pins match and such, so we should be good there. I think there is access to uart pins, but I do want to get the USB working as well as that's the common method of connecting to these printers. That looks like it needs work. It does have a bootloader, so another thing to adjust as well.

I was able to add the stm32h743 to the Kconfig, so that's working now too.

At this point, I have your code compiling and ready to go, so whenever this PR can get merged, I can build off of it. Thanks for doing the work to get it to this point!

**Comment by KevinOConnor** [comment]
Thanks.  Sorry for the delay in responding.

I rebased this branch on top of the latest master and made some minor changes - mostly to avoid changing code outside of the stm32h7 code.

I also changed the stm32h7 ADC code to downscale to 12 bit so that it isn't necessary to alter the current Klipper adc protocol.  There's likely a better way to make this change - in particular, there's no real value in using hardware oversampling.  However, I went with a simple change here as I don't have the hardware to test the changes.

The rebased code is on the work-stm32h7-20210902 branch.  https://github.com/KevinOConnor/klipper/tree/work-stm32h7-20210902

Let me know if you are okay with this new series.  If so, we can commit this to the Klipper master branch.

-Kevin

**Comment by adelyser** [comment]
@KevinOConnor I've been doing a bunch of work getting the BTT-SKR-SE-BX board up and running, so I'll check out your branch as well. There were some consolidation changes I also made, so I'll see what's similar.

**Comment by adelyser** [comment]
@KevinOConnor With your change to stm32h7_adc.c, all my temps are now multiplied by a factor of 10. I'm seeing 233.4C instead of 24.3C

**Comment by D4SK** [comment]
There is an option to put the ADC in 12bit mode, maybe I can look into this sometime next week. 

The issue is probably DECL_CONSTANT("ADC_MAX", 65535); still being the value for 16bit mode.

I'd prefer to keep the hardware-oversampling as it allows for not using a filtering capacitor and still get good readings without additional cpu load.
One thing to simplify could be using a 10us delay (specified in the datasheet) instead of checking the LDORDY register. Thus getting rid of these lines etc.
```
// LDORDY registers are missing from CMSIS (only available on revision V!)
#define ADC_ISR_LDORDY_Pos                 (12U)
#define ADC_ISR_LDORDY_Msk                 (0x1UL << ADC_ISR_LDORDY_Pos)
#define ADC_ISR_LDORDY                     ADC_ISR_LDORDY_Msk
```

**Comment by KevinOConnor** [comment]
Ah - goofed on one of the ADC changes.  Hopefully it is fixed now.  It will be necessary to pull the latest code, recompile, and flash.

`cd ~/klipper ; git fetch ; git checkout origin/work-stm32h7-20210902 ; sudo service klipper stop ; make flash ; sudo service klipper start`

-Kevin

**Comment by KevinOConnor** [comment]
> The issue is probably DECL_CONSTANT("ADC_MAX", 65535); still being the value for 16bit mode.

Yeah - I somehow lost that during one of my local merges.

The only change I made to the ADC code is the above `DECL_CONSTANT()` change and `return (adc->DR >> 4) & 0x0fff;` in `gpio_adc_read()`.

-Kevin

**Comment by adelyser** [comment]
@KevinOConnor Ok, I just pulled the latest and it's working great now.

**Comment by D4SK** [comment]
Unfortunately, I've hit another problem.
Upon testing the heater pwm output (I had only tested the fan pwm and hard_pwm before) I found that a queue_digital_out created another "Rescheduled timer in the past" error.

queue_pwm_out still works. 
I also recreated the same issue on the original PR, so the changes @KevinOConnor made are not the issue.

[2.bug.txt](https://github.com/KevinOConnor/klipper/files/7138268/2.bug.txt)
the log is a result of the following gcode commands
M106
M104 T0 S50 -> error

I will investigate this further.
Any ideas on what could cause this?
@adelyser  Did setting a heater temperature work for you yet?

**Comment by adelyser** [comment]
Hmm, I'm not quite sure why you would be seeing that error, my heaters for both the extruder and bed are working fine without error.

**Comment by D4SK** [comment]
Thanks, i just noticed it works when set to 400mhz. (Increasing the tolerance from 1 to 10ms didn't do anything) I saw that for adelyser the USB also didnt work at 480mhz, so maybe thats the same problem.

**Comment by adelyser** [comment]
@D4SK are you on discord? It might be easier to collaborate there on this.

**Comment by D4SK** [comment]
good idea. Im Konstantin#3476 on discord

**Comment by KevinOConnor** [comment]
The code currently assumes that a time 10 seconds in the future will not overflow a 32bit value.  So, that puts a limit of ~429Mhz for the exported clock rate.  (To be clear, the cpu can run faster, just the timer values shared between host and mcu can't be that fast.)

-Kevin

**Comment by adelyser** [comment]
@KevinOConnor I was digging down into the timers and was finding exactly as you describe. Thanks for the insight on that, however, I'm not clear on how to work around that if the CYCCNT can only run at the system clock speed. I'll post up in Discord to find some assistance with that change, I suspect as processors get faster, this will become more of an issue eventually.

As for your branch for the port, I'm working off that branch and I feel it's good as it is now. I'd be happy if you could submit a PR as I'm close to having changes ready to support the BIQU-BX.

@D4SK Are you also OK with the branch Kevin created so we can get that in?

**Comment by D4SK** [comment]
Thats good to hear! 
Other than that I think the new branch is great. I made a small tweak to it (#4666), and @adelyser is working on the 480mhz issue. So from my point of view it can be merged.

**Comment by KevinOConnor** [comment]
Okay.  I'm inclined to merge this after the v0.10.0 release.

To use 400Mhz mode, is it just a change to Kconfig?
```diff
--- a/src/stm32/Kconfig
+++ b/src/stm32/Kconfig
@@ -108,7 +108,7 @@ config CLOCK_FREQ
     default 84000000 if MACH_STM32F401
     default 168000000 if MACH_STM32F405 || MACH_STM32F407 || MACH_STM32F429
     default 180000000 if MACH_STM32F446
-    default 480000000 if MACH_STM32H750
+    default 400000000 if MACH_STM32H750
 
 config FLASH_SIZE
     hex
```

-Kevin

**Comment by adelyser** [comment]
You should also disable overdrive (VOS0) in stm32h7.c:
```
#if CONFIG_CLOCK_FREQ > 400000000
    RCC->APB4ENR |= RCC_APB4ENR_SYSCFGEN;
    SYSCFG->PWRCR |= SYSCFG_PWRCR_ODEN;
    while (!(PWR->D3CR & PWR_D3CR_VOSRDY))
        ;
#endif
```

**Comment by KevinOConnor** [comment]
> You should also disable overdrive (VOS0)

Okay.  I think it might be a good idea to focus on 400Mhz for the current merge, and then look at adding 480Mhz on top of that at some later point.

-Kevin

**Comment by adelyser** [comment]
I totally agree, I don't have an ETA for when I'll have a fix for the 480MHz right now.

**Comment by KevinOConnor** [comment]
Thanks.  I've committed the work-stm32h7-20210902 branch that was discussed here.

-Kevin

**Comment by KevinOConnor** [comment]
@D4SK , @adelyser - FYI, a user on Klipper Discourse ran into an issue with step rates, and performed some benchmark tests - https://klipper.discourse.group/t/mcu-mcu-shutdown-rescheduled-timer-in-the-past-host-buffer-100/4442/13

Oddly, the benchmarks on the stm32h7 seem worse than an stm32f4 chip.

Have either of you run the benchmarks on your boards?  Any ideas why it would have lower results compared to an f4?  Does the chip have any cache settings that could be optimized?

-Kevin

**Comment by D4SK** [comment]
> Have either of you run the benchmarks on your boards? Any ideas why it would have lower results compared to an f4? Does the chip have any cache settings that could be optimized?

Running the tests I am getting the same slow performance. I added a pr that enables the cache.

**Pull request closed without merging**
