### PR TITLE
Create printer-creality-cr10-max-2020.cfg

### PR DESCRIPTION
**Pull request by mjruigrok**
Hi there,

I have seen you repository and would like to share my own printer.cfg as my printer type has not been uploaded here before and is very difficult to get all the information correct. But I managed and would like to share with others so they don't spend days figuring out how this works ;-).

### CODE REVIEW

**Comment by JamesH1978** [comment]
Hi @mjruigrok 

Please can you limit your config to only features than come with the printer, and also remove any save_config, {include] sections, macros. config for resonance testing etc. A repo config should describe a printer that is straight out of packaging, otherwise it could confuse other users with this printer.

You should also include a header with board flash information, as per other example configurations.

Thanks
James

**Comment by mjruigrok** [comment]
I have changed the file. I hope this is better. Sorry for the earlier file. I am very new to this (3d printing, klipper and github). So please bear with me.

The printer is straight out of the box and added with a creality sonic pad which adds klipper functionality. In the config there is an addition specifically for this printer that shows up on the creality sonic pad display (even thought it is commented out). It shows the printers printing dimensions.

I changed the file in the request but I am unsure I did this correct on github.

**Comment by JamesH1978** [comment]
@mjruigrok thanks for the changes, can you also review https://github.com/Klipper3d/klipper/blob/master/docs/Example_Configs.md and make sure you add the regression test additions and https://github.com/Klipper3d/klipper/blob/master/docs/CONTRIBUTING.md paying attention to the signed off line

Thanks
James

**Comment by mjruigrok** [comment]
I do not understand any of what you are asking ;-(.  " add the regression test additions" reading up on this I find a lot of unix/linux command's. I do not run linux or unix. Maybe on the creality sonic pad but it is not something I need or use. And I am unsure if I have access to it's prompt. I tried a putty one time but am clueless to the required password/ username. I know klipper likes to use linux to create a firmware file. However the creality sonic pad does this for you and upload's it to the printer. All in a nice GUI in a wizard style for dummy's like myself. In your message when clicking on stuff I found something about white spaces (line 7) and extra line ends On line 121. If this is what you talk about I fixed that as well. 

On the second request. "paying attention to the signed off line" I found something that you might be referring to but do not understand what it means. I read something under the heading "Format of commit messages" but am clueless to what is meant here, or better what is asked of me. Also I do not like to share my email adres to the general public. It is not a wise thing to do nowadays (spam and stuff). I think the intention is to give some sort of free use license to the configuration file to the open public. And this is the primary reason I am doing this for others to benefit and not struggle like I did, so giving permission is not an issue. And it giving an email adres to a private party is also not a problem as long as it is not shared to the public. And I do not understand what text is requested of me and where to put it or what it does and who it is shared with. 

If you can help me in what to do I can give it a try. But I am not a developer, not a linux user and very new to contributing. Ussualy I just pay for a license or hardware ;-). And creating a working printer.cfg file is already beyond my scope of capabilities. But I did and it worked. But I start to get into the realm beyond my capabilities ;-). 

With kind regards,
Maarten Ruigrok

**Comment by JamesH1978** [comment]
unfortunately we do not accept any submissions without a real name and email address, this is to conform with our DCO https://github.com/Klipper3d/klipper/blob/master/docs/developer-certificate-of-origin and to comply with our open source licences. This is non negotiable.

In terms of the regression tests, all you have to do is push a line to [test/klippy/printers.test](https://github.com/Klipper3d/klipper/blob/master/test/klippy/printers.test) in alphabetical order in the right chip section with your new file name. See the file for syntax.

Thanks
James

**Review by JamesH1978 — COMMENTED** [review]
Initially the code looks fine but you also need to add regression tests as per point 4 in https://github.com/Klipper3d/klipper/blob/master/docs/Example_Configs.md

Thanks
James

**Pull request closed without merging**
