### PR TITLE
config: Add BigTreeTech boards config

### PR DESCRIPTION
**Pull request by bigtreetech**
* add PB12/PB13 FDCAN2 support STM32G0B1
* add BigTreeTech `EBB V1.2`, `EBB SB V1.0(TMC2240 & TMC2209 for Voron-Stealthburner)`, `Manta E3 EZ`, `Manta M5P`, `Manta M8P V1.1`, `Octopus Max EZ`

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  In general, it looks fine to me.  I did notice a couple of minor things:
1. For what it is worth, I find the pin names in lines like `cs_pin: EBBCan: PB12` to be confusing.  I think it's more clear without the space in the middle of the pin:  `cs_pin: EBBCan:PB12`
2. Just for your information, I don't think the adxl345 results will have high quality if using software spi.  The adxl345 is a high-bandwidth device that software spi is likely to struggle with.

If there are no further comments, I'll look to commit in a few days.

-Kevin

**Comment by bigtreetech** [comment]
> Thanks. In general, it looks fine to me. I did notice a couple of minor things:
> 
> 1. For what it is worth, I find the pin names in lines like `cs_pin: EBBCan: PB12` to be confusing.  I think it's more clear without the space in the middle of the pin:  `cs_pin: EBBCan:PB12`
> 2. Just for your information, I don't think the adxl345 results will have high quality if using software spi.  The adxl345 is a high-bandwidth device that software spi is likely to struggle with.
> 
> If there are no further comments, I'll look to commit in a few days.
> 
> -Kevin

1.  I'll clean it up later
2. I will add a new hardware spi port for EBB spi to the G0B1 spi code. However, many `ifdef` will be added at present, and I am further cleaning up

**Comment by JamesH1978** [comment]
@bigtreetech you include a section for [tmc2240 extruder] in config/sample-bigtreetech-ebb-sb-canbus-v1.0, this is not a valid tmc section in klipper. Is this something you intend to commit too? We are starting to see users on our support platforms asking why they cannot connect and receiving invalid section errors.

Thanks
James

**Comment by fiferboy** [comment]
BigTreeTech has a branch of klipper with TMC2240 support here: https://github.com/bigtreetech/klipper/tree/tmc2240

I haven't tested it yet and there is no merge request - so it might not be ready for use. I'll probably try it out on my EBB SB2240 this weekend if I have a chance.

**Comment by KevinOConnor** [comment]
Thanks.  I merged this branch with a couple of minor changes:
1. When using regular can.c, only stm32f4 should have support for PB12/PB13 (Kconfig should read `(HAVE_STM32_CANBUS && MACH_STM32F4) || HAVE_STM32_FDCANBUS`).
2. I renamed `sample-bigtreetech-ebb-sb-canbus-v1.0` to sample-bigtreetech-ebb-sb-canbus-v1.0.cfg`
3. I removed the comment containing tmc2240 - we can add that comment back in once the main Klipper branch support the tmc2240 drivers.

Commits 1979c9d0 and f250bdfd.

-Kevin

**Pull request closed without merging**
