### PR TITLE
board_defs.py: Add Fysetc Cheetah V2 to spi_flash

### PR DESCRIPTION
**Pull request by JamesH1978**
As discussed with user HiitsameAsh on discord, he has confirmed this addition will flash a Fysetc Cheetah V2

Thanks
James

Signed-off-by: James Hartley james@hartleyns.com

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  It's fine with me.  Looks like there is an unrelated whitespace change though.

Maybe @Arksine has some comments?

-Kevin

**Comment by JamesH1978** [comment]
Thanks Kevin,

unintended white space removal has been rectified. I will await input from @Arksine 

James

**Comment by Arksine** [comment]
Looks good to me.

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
