### PR TITLE
Fix building for "Linux Process" in non-FHS environments

### PR DESCRIPTION
**Pull request by MadnessASAP**
This PR addresses building the Klipper "Linux Process" MCU on filesystem layouts that don't adhere to the FHS standard (i.e. NixOS) . It replaces the absolute include paths in `main.c` and `gpio.c` with relative paths. It also adjusts CFLAGS to use `-iquote` to prevent conflicts when resolving quoted "includes" and <includes>.

The finest of "builds for me" testing was carried out successfully.

### CODE REVIEW

**Comment by MadnessASAP** [comment]
> Thanks, I just looked into setting up the host MCU and ran into this issue. This PR fixed compilation for me :)

Glad it helped, are you also running on NixOS by chance? I'm also putting some TLC into the nixpkg module.

**Comment by CRTified** [comment]
> are you also running on NixOS by chance?

Yes, I am. Feel free to ping me on matrix (@crtified:crtified.me), I got the host mcu working on NixOS already :)

**Comment by cnf** [comment]
[Discord Link](https://discord.com/channels/431557959978450984/801826273227177984/1222244082152116307) to a discussion about this.

**Comment by KevinOConnor** [comment]
Thanks.  It seems fine to me.  Could you split the line in the Makefile so it does not exceed 80 characters though?

-Kevin

**Comment by MadnessASAP** [comment]
Thanks! Makefile corrected for the non-ultrawide proletariat.

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
