### PR TITLE
ci: update dependencies

### PR DESCRIPTION
**Pull request by thijstriemstra**
Signed-off-by: Thijs Triemstra <info@collab.nl>

### CODE REVIEW

**Comment by thijstriemstra** [comment]
There are a few dependencies that have newer versions but breaking backwards incompatible changes so I didn't update those but I can take a look at those as well if wanted.

**Comment by hcet14** [comment]
> There are a few dependencies that have newer versions but breaking backwards incompatible changes so I didn't update those but I can take a look at those as well if wanted.

What could go wrong?

**Comment by thijstriemstra** [comment]
> What could go wrong?

Alright.

> There are a few dependencies that have newer versions but breaking backwards incompatible changes so I didn't update those 

After another review I couldn't find any incompatible changes and all dependencies should now be using their latest version.

**Comment by KevinOConnor** [comment]
Thanks.  We can certainly update the dependencies.  I'd like to understand if this is a proactive change or if there is a particular reason to make a change now?

-Kevin

**Comment by thijstriemstra** [comment]
@KevinOConnor sorry for the late response.

>  I'd like to understand if this is a proactive change or if there is a particular reason to make a change now?

If you check a random ga build, e.g. https://github.com/Klipper3d/klipper/actions/runs/5828773956, it shows the following warning:

```
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2, actions/cache@v2, actions/upload-artifact@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
```

So I try to keep these actions up to date for all my projects.

**Comment by KevinOConnor** [comment]
Okay, thanks.

-Kevin

**Comment by KevinOConnor** [comment]
This PR introduced a regression that resulted in actions/stale@v8 closing several PRs.  I committed c9aa7ac8 in an attempt to fix the regression.

-Kevin

**Comment by thijstriemstra** [comment]
sorry @KevinOConnor, that's a pretty shitty regression. i hope it got solved with your additional changes.

**Pull request merged**
