### PR TITLE
Improve json encoding error handling

### PR DESCRIPTION
**Pull request by jschuh**
Json encoding errors currently force a shutdown with no context as to why. This can be verified by adding the following to a config, which triggers a silent TypeError:

```
[gcode_macro crasher]
variable_crash: {(1, 1): 1}
gcode:
    # empty
```

This change just logs the error (including a console message) so it's easier to diagnose what went wrong. In the case of the above error, the message is:

```
json encoding error: keys must be str, int, float, bool or None, not tuple
```

_**Edit:** Also added code to prevent setting bad variables inside `gcode_macro.py`._

### CODE REVIEW

**Comment by jschuh** [comment]
@Arksine, would you mind taking a look at this when you have a chance? It's a small logging addition that would have saved me quite a few hours of macro debugging (that turned into Klipper webhooks debugging).

**Comment by Arksine** [comment]
In general the change looks ok to me.  I suspect we would want to return in the exception handler as well since there is no additional data to send.  I'm also not sure if we want to invoke a shutdown, that is something Kevin could provide better feedback on.

An alternative option may be to verify that a variable can be encoded to json in `gcode_macro.py`.  If it fails we could raise a config error which would provide more details on exactly what went wrong.

**Comment by jschuh** [comment]
After thinking about it I decided that catching early in gcode_macro is the best solution for the problem I hit, so I added a second commit to this PR.

I also kept the first commit with the logging in webhooks because there are other paths that can get there, so it still seems useful for tracking down errors.

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
