### PR TITLE
docs: Add document for RP2040 spi bus

### PR DESCRIPTION
**Pull request by ChipCE**
Add document for the pins configuration of RP2040 microcontroller.

Signed-off-by: John Smith <chip@snakeoildev.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  The information looks useful, however I'm not sure if we should add a new document for it.  What would you think about adding this as a section under "Common SPI settings" in docs/Config_Reference.md ?

-Kevin

**Comment by ChipCE** [comment]
@KevinOConnor Thank for the feed back!
I think about that before but it is device specified. So instead of flooding the common config, I made a new file for it. 
I will move it to Config_Reference.md if you think that it the better place.

**Comment by ChipCE** [comment]
@KevinOConnor Does this location sound good to you?
Screenshot_2021-10-10_14-01-47

**Comment by KevinOConnor** [comment]
I would add it to that page but under the existing "Common spi settings" section.

-Kevin

**Comment by KevinOConnor** [comment]
Thanks.  What is the state of this PR?

-Kevin

**Comment by ChipCE** [comment]
> Thanks. What is the state of this PR?
> 
> -Kevin

Sorry, I found out not just the RP2040 but there are no document about the bus name for other MCU. I will submit other PR include document for all supported MCU later. 
I will close this PR for now.
Thank you!

**Pull request closed without merging**
