### PR TITLE
"static_value" in [output_pin enable_pin] is deprecated

### PR DESCRIPTION
**Pull request by 1coderookie**
As the title says, "static_value" is deprecated, so I removed it and replaced it with "value".

### CODE REVIEW

**Comment by JamesH1978** [comment]
Thank you for submitting a PR, pleas refer to point 3 in "What to expect in a review" in https://github.com/Klipper3d/klipper/blob/master/docs/CONTRIBUTING.md and provide a signed off by line.

But yes it is deprecated, but we don't remove deprecations until a certain amount of time has passed then Kevin will make the decision to remove them completely.

Please read https://github.com/Klipper3d/klipper/blob/master/docs/Config_Changes.md Which explains this.

Thanks
James

**Comment by 1coderookie** [comment]
Sorry for the missing sign-off-line - since I don't really get how/where to add that now and since I don't understand the first line in that doc (with that "module:" example - like would it be "printer: Replaced deprecated `static_value` with `value`?), would it be sufficient if I just add that line here now? If so:   
Signed-off-by: Ulf Dieckmann <1coderookie@quantentunnel.de>  

I've read that doc about the config changes, that's actually why I thought it might be good to change it here in that example printer.cfg already. Because I thought better I remove it right now in that file and make a PR instead of forgetting to do so later and then a user has problems once it's finally being removed - but if you don't want to merge, it's totally fine with me! ;)

**Comment by JamesH1978** [comment]
Apologies I may have jumped the gun on this one I thought you were actually trying to change the base code, and not a printer configuration...

In that case I will approve this.

Sorry about that,

James

**Review by JamesH1978 — APPROVED** [review]
This looks fine to me.

Thanks
James

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
