### PR TITLE
Add rp2040 to MCUs with internal temp sensors

### PR DESCRIPTION
**Pull request by RazorSh4rk**
Small change, came up in a discord thread and I wanted to add it since the skr pico is so popular

Signed-off-by: Levi Szabo <iamrazorshark@gmail.com>

### CODE REVIEW

**Comment by JamesH1978** [comment]
Thank you for submitting a PR, pleas refer to point 3 in "What to expect in a review" in https://github.com/Klipper3d/klipper/blob/master/docs/CONTRIBUTING.md and provide a signed off by line.

Thanks
James

**Comment by RazorSh4rk** [comment]
Added, thanks

**Review by JamesH1978 — APPROVED** [review]
Can't see any issues in adding that to the documentation. I can confirm the temperature is readable from those mcu's.

Thanks
James

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
