### PR TITLE
docs: Improve Doc Consistency

### PR DESCRIPTION
**Pull request by dingyifei**
gcode/g-code/Gcode -> G-Code
`.  ` -> `. `
`_x_` -> `*x*`
pwm -> PWM
github/Github -> GitHub
klipper -> Klipper
and various little fixes like some improper formatting and typos

Signed-off-by: Yifei Ding<yifeiding@protonmail.com>

### CODE REVIEW

**Comment by dingyifei** [comment]
I'll try to apply these

https://github.com/dingyifei/klipper/runs/3353679324?check_suite_focus=true#step:4:124

**Comment by KevinOConnor** [comment]
Thanks.  I agree it is worthwhile to unify terms where we can.

Is there a technical reason to change the `.<space><space>` to `.<space>` ?  It's a large change and I'm not sure it's worthwhile to make such a widespread change.  In general, I think it's okay to use either style as long as the document is internally consistent (either always use two spaces or always use one).

Similarly, what's the reasoning behind changing from _abc_ to *abc* ?

@Arksine - there are a number of changes to docs/Bed_Mesh.md here - are you okay with the changes?

-Kevin

**Comment by Arksine** [comment]
Looks like its just formatting changes, I'm ok with it.  I agree that consistency in the documentation is a good idea.

**Comment by dingyifei** [comment]
> Is there a technical reason to change the `.<space><space>` to `.<space>` ? It's a large change, and I'm not sure it's worthwhile to make such a widespread change. In general, I think it's okay to use either style as long as the document is internally consistent (either always use two spaces or always use one).

The `.<space><space>` is rendered as `.<space>` for most markdown engines. Emphasis using `_` is not allowed in words but using `*` is allowed, so using `*` is preferable for reducing confusion.

The awkwardly long [Commonmark standard](https://spec.commonmark.org/0.30/#emphasis-and-strong-emphasis) might be helpful in explaining this.

 (And ... it is an itchy thing to spot extra spaces in the Weblate suggestions) 

I'll make a few more commits following the markdown-lint suggestion to improve the rendering quality of fenced code blocks, equations(using LaTeX and possibly need [mathjax](https://squidfunk.github.io/mkdocs-material/reference/mathjax/) plugin), and lists.

**Comment by dingyifei** [comment]
I'm trying to address the render affecting and non-render affecting formatting issues in the current documentation.

This screenshot from Klipper3d.org is showing a render affecting formatting issue.
图片

**Comment by dingyifei** [comment]
some MD026 and M033 are not addressed in the recent commit. 

Known issue:

- `Hallfilamentwidthsensor.md` need wording improvements.
- Should parameters of G-Code commands be rendered as `code`?
- Kinematics equation LaTeX looks kinda bad (as much I tried, my physics class memory is not saving me...)
- readme.md has an MD041, currently leaving it as-is.

This PR will fix several incorrect renders and add code highlighting for most fenced code blocks with the closest language code.

**Comment by KevinOConnor** [comment]
Okay.  I'm not sure I understand the rendering issues you are pointing out.  In any case, I think it's fine to unify the formatting of the documentation.

One thing I think will be needed, though, is to have separate commits for each issue being resolved.  For example, one commit for capitalization issues, one commit for `*` vs `_` usage, etc.  A single commit (or series of commits with various changes) will be difficult to review and will cause merge issues with other PRs.  I know splitting the commits is additional work, but I think it will result in less work in the long run.

Thanks.
-Kevin

**Comment by dingyifei** [comment]
> One thing I think will be needed, though, is to have separate commits for each issue is resolved. 

I'll generate another PR that contains the same changes but in separate commits. 

> I'm not sure I understand the rendering issues you are pointing out. In any case, I think it's fine to unify the formatting of the documentation.

The problem in the screenshot above is the "see the configuration..." is mentioning the entire list of parameters but is incorrectly rendered in an item of the list. It missed an empty line that resulted in this text being displayed differently in raw v.s. rendered.

The raw text:
```
It is possible to specify mesh parameters to modify the probed area.  The
following parameters are available:
- Rectangular beds (cartesian):
  - `MESH_MIN`
  - `MESH_MAX`
  - `PROBE_COUNT`
- Round beds (delta):
  - `MESH_RADIUS`
  - `MESH_ORIGIN`
  - `ROUND_PROBE_COUNT`
- All beds:
  - `RELATIVE_REFERNCE_INDEX`
  - `ALGORITHM`
See the configuration documentation above for details on how each parameter
applies to the mesh.
```

An two extra empty lines fix the raw text

```
It is possible to specify mesh parameters to modify the probed area.  The
following parameters are available:

- Rectangular beds (cartesian):
  - `MESH_MIN`
  - `MESH_MAX`
  - `PROBE_COUNT`
- Round beds (delta):
  - `MESH_RADIUS`
  - `MESH_ORIGIN`
  - `ROUND_PROBE_COUNT`
- All beds:
  - `RELATIVE_REFERNCE_INDEX`
  - `ALGORITHM`

See the configuration documentation above for details on how each parameter
applies to the mesh.
```

**Comment by KevinOConnor** [comment]
> The problem in the screenshot above is the "see the configuration..." is mentioning the entire list of parameters but is incorrectly rendered in an item of the list. It missed an empty line that resulted in this text being displayed differently in raw v.s. rendered.

Thanks.  I understand.  Yeah, if we can put those types of things into separate commits I think we can merge them rapidly.

-Kevin

**Comment by dingyifei** [comment]
WIP: https://github.com/KevinOConnor/klipper/pull/4599

**Comment by dingyifei** [comment]
I will open separate PRs addressing different issues to replace #4599 and this repo, I'm currently really busy with college(probably shouldn't take too many classes...)

**Pull request closed without merging**
