### PR TITLE
Create printer_Creality_ender-3s1.cfg

### PR DESCRIPTION
**Pull request by KimRay2015**
Add Creality Ender-3s1 config example

### CODE REVIEW

**Comment by Sineos** [comment]
See https://github.com/Klipper3d/klipper/pull/5332

This was found to be working by some testers. What is the reason for the additional changes?

**Comment by KimRay2015** [comment]
add fan running with Nozzle temp ,
when Nozzle temp over 60,the fan start




At 2022-05-20 17:52:31, "Sineos" ***@***.***> wrote:

See #5332

This was found to be working by some testers. What is the reason for the additional changes?

**Comment by Sineos** [comment]
Nozzle fan is the reason to add 140k lines of code?

**Comment by KimRay2015** [comment]
Nozzle fan is the reason to add 140k lines of code?
  meantime add stm32h723 mcu config files ,




At 2022-05-20 18:08:20, "Sineos" ***@***.***> wrote:

Nozzle fan is the reason to add 140k lines of code?

**Comment by Sineos** [comment]
See https://github.com/Klipper3d/klipper/pull/5208#issuecomment-1072631346 this answer

Please do not respond by mail, this is just cluttering the entire thread

**Comment by KevinOConnor** [comment]
There is now an ender 3 s1 config in Klipper.

-Kevin

**Comment by KimRay2015** [comment]
Thanks;










--

 






At 2022-06-08 23:11:47, "KevinOConnor" ***@***.***> wrote:

There is now an ender 3 s1 config in Klipper.

-Kevin

**Comment by Fisheiyy** [comment]
@KimRay2015 Close this PR its irrelevant now.

**Comment by mm108** [comment]
> There is now an ender 3 s1 config in Klipper.
> 
> -Kevin

hi @KevinOConnor, a Klipper newbie here; Will this ender 3 s1 config work well for the S1 Pro without any mods? Mine is a stock S1 Pro.

**Comment by Fisheiyy** [comment]
> > There is now an ender 3 s1 config in Klipper.
> > 
> > -Kevin
> 
> hi @KevinOConnor, a Klipper newbie here; Will this ender 3 s1 config work well for the S1 Pro without any mods? Mine is a stock S1 Pro.

1. Don't ping Kevin
2. Yes
3. Don't go digging through PRs to find a config, it will be in the configs folder and you can search there, yes it will work with the s1 pro because the s1 and pro are the exact same except for all metal heatbreak which allows you to go to 300*C which can be easily changed.

**Pull request closed without merging**
