### PR TITLE
Update printer-creality-ender5-2019.cfg to add instructions for silent boards

### PR DESCRIPTION
**Pull request by GhostDog98**
Recently tested on my ender 5 pro that came from creality with a v1.1.5 board. Works.

### CODE REVIEW

**Comment by JamesH1978** [comment]
Thankyou for submitting a change, to submit a valid PR please refer to point 3 in the "what to expect" section in https://github.com/Klipper3d/klipper/blob/master/docs/CONTRIBUTING.md and add a signed-off-by line.

Thanks
James

**Comment by GhostDog98** [comment]
> Thankyou for submitting a change, to submit a valid PR please refer to point 3 in the "what to expect" section in https://github.com/Klipper3d/klipper/blob/master/docs/CONTRIBUTING.md and add a signed-off-by line.
> 
> Thanks James

Added a new commit with that signoff message. Let me know if there's any other issues. 

Thanks,
GhostOverFlow

**Comment by KevinOConnor** [comment]
@JamesH1978 - did you have any further comments on this PR?

-Kevin

**Comment by JamesH1978** [comment]
Look mainly informational to me, which is fine, i will review

Thanks
James

**Review by JamesH1978 — COMMENTED** [review]
Cant see an issue, seems mostly informational for those with a slightly different board.

Thanks
James

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
