### PR TITLE
mkdocs: Replace TOC in Translations

### PR DESCRIPTION
**Pull request by dingyifei**
Signed-off-by: Yifei Ding<yifeiding@protonmail.com>

### CODE REVIEW

**Comment by dingyifei** [comment]
Changes to klipper-translations are already merged

**Comment by KevinOConnor** [comment]
Thanks.  Alas, I'm not sure I understand what this change does.  Can you give a high-level overview?  What's the problem being solved and how the solution works?

-Kevin

**Comment by dingyifei** [comment]
> Thanks.  Alas, I'm not sure I understand what this change does.  Can you give a high-level overview?  What's the problem being solved and how the solution works?
> 
> 
> 
> -Kevin

A part of the table of content is not translatable because they are not automatically generated from corresponding xxx.md. They are in the mkdocs.yml. I made Navigation.md and Navigation.po in killer-translations to make it translatable. Then this script basically read the specific lines of Navigation.md for languages and replace the strings in mkdocs.yml with the line read.

**Comment by KevinOConnor** [comment]
Okay, I understand.  Thanks.

-Kevin

**Pull request merged**
