### PR TITLE
kinematics: add duplication/mirror modes to idex_mode

### PR DESCRIPTION
**Pull request by Tircown**
Add duplication and mirror modes to idex_modes.
Allows hybrid-corexy and hybrid-corexz to use these modes.

Idex_mode avoids collisions if the user correctly sets the position_min and position_max for stepper_x and dual_carriage.

Do not merge before PR ~~#4445~~ #4489. I will add a sample configuration and a document on how to set the IDEX parameters.

Signed-off-by: Fabrice GALLET tircown@gmail.com

### CODE REVIEW

**Comment by DrumClock** [comment]
This video shows the functionality of IDEX mods on a test device for Cartesian printers. 

https://youtu.be/UbeUd0DCNsc

I used this files for configuraation: **IDEX_mode.cfg** 
and for testing: **M605 test all mode.gcode**

[used files.zip](https://github.com/KevinOConnor/klipper/files/6818209/used.files.zip)

Test description:

**AUTO-PARK - M605 S1** test of automatic exchange of T0 / T1 including z-hop and switching of fan X1 / X2 for print cooling.

**DUPLICATION - M605 S2** test of setting carriages offset and synchronization T0 / T1 including both fans X1 and X2

**MIRRORED - M605 S3** test of setting carriages offset and synchronization T0 / T1 including synchronization of both fans X1 and X2

**FULL-CONTROL - M605 S0** test of functionality of full control T0 / T1 including and switching of fan X1 / X2 for print cooling.

Everything has run several times and I haven't notice any bug in the mods and functionality.

For my part, I recommend adding these modes to FW Klipper.

**Comment by KevinOConnor** [comment]
Thanks.  Sorry for the delay in responding.  In general, it looks fine to me.

Some high-level questions:
1. Is there a reason to add a new `SET_DUAL_CARRIAGE_MODE` command instead of adding a parameter to the existing `SET_DUAL_CARRIAGE` command?
2. What is the intent of the `a == b == c` statements?  (For example, `self.dc[0].is_active() == self.dc[1].is_active() == True`)  I'm not sure what this does in Python.
3. I'm not sure it's a good idea to use `value is False` directives, as that would cause confusing results if the value got assigned to a literal `0` (or similar) for some reason.
4. Does this PR stand on its own, or does it require #4489 to be useful?

Thanks again,
-Kevin

**Comment by Tircown** [comment]
Thank you for your comments. No problem for the delay.
> Is there a reason to add a new SET_DUAL_CARRIAGE_MODE command instead of adding a parameter to the existing SET_DUAL_CARRIAGE command?

The only reason is that duplication and mirroring mode always activate the carriage 0. So if one set the parameter MODE, the parameter CARRIAGE is automatically ignored or must raise an error if the value is not 0.

> What is the intent of the a == b == c statements? (For example, self.dc[0].is_active() == self.dc[1].is_active() == True) I'm not sure what this does in Python.

A shorter syntax than `self.dc[0].is_active() == True and self.dc[1].is_active() == True`. It's probably more confortable to do `self.dc[0].is_active() and self.dc[1].is_active()`

> I'm not sure it's a good idea to use value is False directives, as that would cause confusing results if the value got assigned to a literal 0 (or similar) for some reason.

Ok. For `if positive_dir is False` I will turn it as it is in the kinematics: ` if hi.positive_dir`. The function `is_active()` and `is_reversed` are in the same file as idex_mode and returns a boolean. Do you suggest to change the condition too?

> Does this PR stand on its own, or does it require Add sync_extruder_steppers #4489 to be useful?

This PR only adds the duplication and mirroring modes which are not usable without synchronisation of the extruders but this PR stand on it's own code wise.

The documentation I want to produce interferes in some way with #4508. As the config sample does.
The most practical thing for me would be to merge this PR without documentation first, wait for #4508 to be merged (or cancelled), then I'll do a PR to complete the documentation with the implementation of carriages limits (anti-collision system), etc.

**Comment by KevinOConnor** [comment]
> The function is_active() and is_reversed are in the same file as idex_mode and returns a boolean. Do you suggest to change the condition too?

FWIW, I find the comparisons to True/False (eg, `A == True` or `A is False`) to be confusing.  I fear different versions of Python may do different things and/or slight value differences could lead to surprising results.  I suggest using the more common syntax of `if A` and `if not A`.

> The most practical thing for me would be to merge this PR without documentation first, wait for #4508 to be merged (or cancelled), then I'll do a PR to complete the documentation with the implementation of carriages limits (anti-collision system), etc.

That's fine with me.  One thing we need to figure out, though, is if we want to merge this prior to v0.10.0 release or after.  I'm fine with merging before the release, but then we should also have a solution for #4489 before the release.  Alternatively, we can look to merge this after the release - in October/November.

Thanks.
-Kevin

**Comment by Tircown** [comment]
> [...] but then we should also have a solution for #4489 before the release.

I would consider the bypass with the `[extruder_stepper]` as a temporary but working solution to not block the PR. That would let time to rework the extruder architecture. Anyway, those who want to print in dupe/mirrors mode use #4489 files; they are not "blocked".

**Comment by KevinOConnor** [comment]
I'm not sure what you're proposing.

-Kevin

**Comment by DrumClock** [comment]
Hi @KevinOConnor
it would be really good to add duplication / mirror modes to Klipper.
If IDEX printing machines already allow it, why not use it.

Unfortunately, I'm not a programmer, but I offer you help with testing just like I offered @Tircown, with which I work hard to tune the macro configuration for the Klipper.

Thanks
-Petr Forejt

**Comment by charlespick** [comment]
Concerning the conflicting documentation, 

I say we should merge in the code in this pr with it's appropriate documentation. I am still working on my pr, specifically a mechanism for easily adjusting the alignment of the extruders. Since my PR mainly focuses on files, samples, and documentation for *calibrating* an IDEX printer, it shouldn't interfere to much with whatever work is introduced here. 

I will make whatever adjustments are necessary to my pr to after this one is merged.

**Comment by grigi** [comment]
@Tircown I just realised that this won't work for Cartesian IDEX printers (like the one I am building).

Reason I'm saying this is:
https://github.com/KevinOConnor/klipper/blob/4d559633e3a3f9e4aba585c30422c8f5772f2b46/klippy/kinematics/cartesian.py#L35

Cartesian handles the dual carriage stuff separately, and doesn't use the `idex_modes.DualCarriages` object to manage it.
Hence a cartesian IDEX doesn't even have a `printer.dual_carriage` variable.

**Comment by KevinOConnor** [comment]
I do think it would be useful to merge this support into Klipper.  If there is still interest in working on this then please update it to the latest code and I will prioritize a review of this work.

Thanks,
-Kevin

**Comment by Tircown** [comment]
Thank you. I will do the changes in the next days.

**Comment by DrumClock** [comment]
Hi @KevinOConnor 
I tested the new "phyton" files from Tircown on FIRMWARE_VERSION: v0.10.0-225-g6e6ad7b5-dirty.

For these IDEX modes: 
**M605 S1 - AUTO-PARK** test of automatic exchange of T0 / T1 including z-hop and switching of fan X1 / X2 for print cooling.
**M605 S2 - DUPLICATION** test of setting carriages offset and synchronization T0 / T1 including both fans X1 and X2
**M605 S3 - MIRRORED** test of setting carriages offset and synchronization T0 / T1 including synchronization of both fans X1 and X2
**M605 S0 - FULL-CONTROL** test of functionality of full control T0 / T1 including and switching of fan X1 / X2 for print cooling.

### I did not find any printing error.
I can also provide very sophisticated macros for dual_carriage and M605 mods.

**Comment by Tircown** [comment]
Ready for a new revision step.
(it is the version tested by DrumClock)
Thanks.

**Comment by KevinOConnor** [comment]
Thanks.  In general, it looks good to me and I think it would be useful to merge this functionality into the Klipper master branch.  I have some high-level comments and questions:
1. I think we should enhance the low-level stepper class so that it is possible to reverse a stepper motor without requiring new "reverse" kinematic code.  I will try to put together some sample code for this in the next couple of days.
2. I'm uncertain on adding a `SET_DUAL_CARRIAGE_MODE` command.  I think the documentation and usage would be more clear if a new mode parameter was added to the existing `SET_DUAL_CARRIAGE`.
3. What is the intent of the new `toolhead.manual_move()` code in `restore_idex_state()`?
4. Can you provide a high-level overview of your plans for cartesian idex "mode" support (if any)?

Cheers,
-Kevin

**Comment by Tircown** [comment]
Thanks.
1. That's a good point and would be a lot more clean. If it can include the extruder stepper then it would solve some issues for the tilting toolheads. kin_cartesian already has the reverse kinematics (#4296).
2. Ok. If one set the mode parameter in SET_DUAL_CARRIAGE then the carriage parameter must not be set and vice-versa. For duplication and mirrored modes, the carriage 0 is always the master. So there will be 4 valid G-code commands:
`SET_DUAL_CARRIAGE CARRIAGE=0`
`SET_DUAL_CARRIAGE CARRIAGE=1`
`SET_DUAL_CARRIAGE MODE=DUPLICATION`
`SET_DUAL_CARRIAGE MODE=MIRRORED`
I can make this change quite quickly if it meets your expectations.
3. To not block the G28 [X] when the both carriages are synchronized, the home function in the kinematics temporarily desynchronizes and home each carriages. For duplication mode especially, the carriage_1 must be positioned in the middle of the axis range before set the synchronization back. In some case it's possible to start a duplication print with the carriage_1 positioned closer to the carriage_0 - e.g nested PEE face shields. In some case it's possible to start a mirrored print with a carriage slightly shifted - e.g. unsymmetrical toolheads. Whatever the user sets as initial positioning of each tool, it is restored and the move is accomplish with the `toolhead.manual_move()`.
4. The cartesian.py file compatible with the idex modes is ready and tested by few beta testers with success. Until now I was waiting to know how much the idex_mode code has to change following your feedback and then if I was still able to adapt the cartesian kinematics myself . I can include the file in this PR, create a separate one now or after this PR merge.

**Comment by KevinOConnor** [comment]
FYI, I added some preliminary support for reversing stepper direction in PR #5120 .  (It's pretty raw right now as I don't have a good way to test it.)

> If one set the mode parameter in SET_DUAL_CARRIAGE then the carriage parameter must not be set and vice-versa.

I think that makes sense.

> Whatever the user sets as initial positioning of each tool

I'm not really understanding this.  Are you saying that a `SET_DUAL_CARRIAGE` command can move the toolhead?  If so, that sounds unexpected.  Could the code recalculate the toolhead's current location and allow the user to move it where they wish?  I fear I may not be understanding this functionality though.

> The cartesian.py file compatible with the idex modes is ready and tested by few beta testers with success. 

Thanks.  I agree that we should leave that work until after this is complete.

Cheers,
-Kevin

**Comment by Tircown** [comment]
Thanks,

No `SET_DUAL_CARRIAGE` doesn't move the toolhead. The user position the [dual_carriage] before calling the `SET_DUAL_CARRIAGE` command. The positions of both carriages are stored for the following reasons:
1- When [dual_carriage] stepper is synchronized to to [stepper_x] stepper, the printer volume is basically half the initial range of the x axis. The new limits depends on each carriage position at the beginning of the synchronisation. The new limits are calculated in `activate_dc_mode` function.
2- During the synchronization, the [dual_carriage] stepper loose his positioning. When the printer back to the full-control mode, [dual_carriage] stepper position must redefined. The position can be calculated as the module stored the initial at the synchronisation and keep tracks on the [stepper_x] stepper position. This is the purpose of the `_calc_dual_carriages_positions` function.
3- When [dual_carriage] stepper is synchronized to [stepper_x] stepper, the homing of x axis is no longer possible if we don't unsynchronize carriages. The idex_modes can save the `save_idex_state` before homing and restore it after the homing with `restore_idex_state`. During this step the toolhead is moved to replicate the initial position set when `SET_DUAL_CARRIAGE` is called the first time with dupe or mirror modes. And here is the only move initiated by the module; during G28 X only.

**Comment by KevinOConnor** [comment]
Okay, I think I understand - the manual_move() occurs during a `G28` when the toolhead is in DUPLICATION or MIRROR mode.

This seems like very subtle behavior.  Are there alternatives?  Could a `G28` issued when in DUP or MIRROR mode just return to "primary carriage mode" instead?

FWIW, past history with Klipper has shown that commands that take a complex action in an attempt to do the "right thing" end up causing more pain than benefit.  (For example, Klipper used to implement `T1`, but we could never do it well due to the large number of different multi-extruder printers.)  The general experience is that users often don't expect the subtle behavior and then they have to spend even more time working around the workaround to get the actual behavior they need.

-Kevin

**Comment by Laker87** [comment]
@Tircown Hi. I tried these commits, but the SET_DUAL_CARRIAGE_MODE command is not recognized for cartesian kinematics. For example, if I change the kinematics to hybrid-corexy, it is recognized successfully.

**Comment by novarlynx** [comment]
I'd really like this feature to not get buried and forgotten about. I've got an IDEX printer and i'd really like this feature.

**Comment by apphead** [comment]
It's a pity that the additional modes are not implemented. Icing on the cake....
I have cartesian IDEX and could help testing (I know [this branch only supports CoreXY](https://github.com/Tircown/klipper/tree/work-hybrid-corexyz-merge))

**Comment by JediRAMA** [comment]
We have made IDEX printer. And Laker made working idex klipper. Can someone check it? there used code from here, and added cartesian kinematics. All IDEX works. Mirror, duplaication and 2 color printing. Input shaping also works for 2 heads. pls check it.
im very noob with coding. but want to help.
https://github.com/Laker87/klipper

**Comment by izlat** [comment]
I join JediRAMA. First of all, you need to check what is already working. And this is the work of Laker87.

**Comment by ujastic** [comment]
it would be interesting to see support for duplication and mirroring in idex klipper

**Comment by gbkwiatt** [comment]
From what I am aware @Laker87  is still working on proper support.

**Comment by apphead** [comment]
We need testers for Lakers fork. I'll do it as soon as possible, anyone else?

**Comment by gbkwiatt** [comment]
> We need testers for Lakers fork. I'll do it as soon as possible, anyone else?

Is it officially ready for testing ? 
I have Cartesian IDEX I can do some tests on. (Sovol SV04)

**Comment by nick-parker** [comment]
Aon3D has been running a bunch of machines on a fork I made from @Tircown 's branch over the last several months without much trouble.

I'll look into rebasing our custom stuff onto Laker's and have our test eng. put it through paces if it's ready for testing. I've been putting off polishing my own code well enough to upstream so I'd love to draft off Laker's efforts

**Comment by Laker87** [comment]
> > We need testers for Lakers fork. I'll do it as soon as possible, anyone else?
> 
> Is it officially ready for testing ? I have Cartesian IDEX I can do some tests on. (Sovol SV04)

Cartesian kinematics support was added by me and it works fine. Already tested by many people.

**Comment by apphead** [comment]
@Laker87 thanks a lot for your time and efforts. I hope your pull request gets implemented in the main branch!

**Comment by DrumClock** [comment]
Hi @Laker87 
Cartesian kinematics was created by @Tircown, you just added it to your repo,

I tested her for @Tircown already in 2021 here:
https://github.com/Klipper3d/klipper/pull/4464#issuecomment-880115393

Otherwise, I can confirm that it works without problems.
@Tircown just needs to tweak a few things that @KevinOConnor n needs for better compatibility.

We all have to wait.

-Cheers  
Petr

**Comment by DrumClock** [comment]
I have created a macro for sync carriage exchange, just using idex_modu duplication.
https://youtu.be/lQxptT_Pz28

**Comment by apphead** [comment]
@DrumClock what fork should I use to test / use it? I was under the impression that Tircown's fork only supports coreXY, not cartesian.

**Comment by DrumClock** [comment]
Test files for cartesian kinematics provided directly by @Tircown and I don't have permission to redistribute them.
You must contact him directly.
I am still working with us and we are testing it so that everything is error free.

**Comment by Laker87** [comment]
> Test files for cartesian kinematics provided directly by @Tircown and I don't have permission to redistribute them. You must contact him directly. I am still working with us and we are testing it so that everything is error free.

I don't have Tircown's cartesian implementation, I added it by myself.

**Comment by gbkwiatt** [comment]
Is there any PR on a horizon then ?  Not sure if I should checkout other branches/repos or just wait and test when there is PR opened.

**Comment by DrumClock** [comment]
> > Test files for cartesian kinematics provided directly by @Tircown and I don't have permission to redistribute them. You must contact him directly. I am still working with us and we are testing it so that everything is error free.
> 
> I don't have Tircown's cartesian implementation, I added it by myself.

**Hi, I'm sorry. So in that case there are two different versions.**
I can provide my macros that I have tried files from Tircown.

https://github.com/DrumClock/my_config

Hopefully they will be useful to someone.

**Comment by Bully85** [comment]
Is there anything new or a working version to test?

**Comment by Scanner001** [comment]
Is there any update on the Cartesian duplication and mirror modes. I have 4 IDEX waiting on Klipper and at least one manufacturer.

**Comment by Nathan22211** [comment]
@Laker87 did you happen to add examples to your fork as to how to add mirror and duplicate modes into your config?

**Comment by Laker87** [comment]
> @Laker87 did you happen to add examples to your fork as to how to add mirror and duplicate modes into your config?

Use SET_DUAL_CARRIAGE_MODE MODE=DUPLICATION for duplication mode or SET_DUAL_CARRIAGE_MODE MODE=MIRRORED for mirrored mode in your start g-code.

**Comment by TheOnlyBeardedBeast** [comment]
Any update on this?

**Comment by DrumClock** [comment]
Klipper already supports IDEX mode

**Comment by TheOnlyBeardedBeast** [comment]
@DrumClock my mistake, not the idex mode, but the dual gantry mode which I am interested in. Sorry

**Comment by zruncho3d** [comment]
@TheOnlyBeardedBeast I'm not aware of those modes being tested for Dual Gantry kinematics in Klipper. 

My patch with the base DG kins lives here:
https://github.com/zruncho3d/klipper/tree/dual_gantry_main

**Comment by TheOnlyBeardedBeast** [comment]
@zruncho3d thanks, in the second half of this year I am planning to build a dual gantry trident based on the dual zero, can I contact you in need of any advice / help?

**Comment by zruncho3d** [comment]
Great!  In that case, post on the Dueling-X user project thread in the DoomCube discord.  A few people are building Dueling Tridents using the parts from https://github.com/zruncho3d/DuelingX (the generalization of Dueling Zero).  

Let's move any conversation there, given this is a closed GitHub thread, for a different kind of kinematics.

**Pull request closed without merging**
