### PR TITLE
src/linux/i2c: additional busses

### PR DESCRIPTION
**Pull request by florian-senn**
More busses to add multiple sensors with same address.
To activate additional busses /boot/config.txt should contain something like

dtoverlay=i2c-gpio,bus=4,i2c_gpio_delay_us=1,i2c_gpio_sda=23,i2c_gpio_scl=24
dtoverlay=i2c-gpio,bus=3,i2c_gpio_delay_us=1,i2c_gpio_sda=27,i2c_gpio_scl=22
dtoverlay=i2c-gpio,bus=2,i2c_gpio_delay_us=1,i2c_gpio_sda=5,i2c_gpio_scl=6

Signed-off-by: Florian Senn <github@senn.bz>

### CODE REVIEW

**Comment by ld3300** [comment]
Hi @florian-senn,
I can't comment on the code itself, but before your commit will be accepted you need to add "Signed-off-by:" as illustrated [here](https://www.klipper3d.org/CONTRIBUTING.html#format-of-commit-messages)
Best,
David

**Comment by florian-senn** [comment]
Hi @ld3300 

something like this or on the commit itself?

Greetings

Florian

**Comment by ld3300** [comment]
yep, that's it.  Wish I could be more helpful on the actual code commit.

**Comment by ld3300** [comment]
I'm not sure who would be best.  I know the approvers are back logged.  I'm trying to help as much as possible with the limited ability I have.  I would try to ping in Klipper Development in the discord channel

**Comment by Blinker73** [comment]
Rpi 4 has up to 6 busses, see commit https://github.com/Klipper3d/klipper/pull/5295

**Pull request closed without merging**
