### PR TITLE
tmc: DUMP_TMC optional REGISTER parameter

### PR DESCRIPTION
**Pull request by leptun**
Add an optional REGISTER parameter to DUMP_TMC so that the output is more filtered/cleaner for manual TMC calibration.
This is a follow-up of #6136.

### CODE REVIEW

**Comment by masterxq** [comment]
Hi, I have mixed drivers, `tmc5160` and `tmc2209`. With the version including this patch I get the following error when I try to move the stepper with the tmc2209 driver or calling `dump_tmc stepper=stepper_z`:

```'Unable to read tmc uart 'stepper_z' register GCONF'```

Downgrading below this patch fixes the issue. So maybe it is related. (Did only check once)

Sadly this is just what I remember from the tests I did 2 days ago, but possibly it is easy to trace it down, and it helps to prevent other users from running into this issue.

If additional testing is needed I can try to reproduce this in some days.

**Comment by leptun** [comment]
I don't see how the change could cause the driver to fail to read the GCONF register. That register exists and is readable, so it should not error out. Can you please try switching to before and after this change a few more times to confirm that the issue indeed only happens after this PR? To me this sounds a lot like an intermittent connection issue with the driver caused by hardware, not software.

**Comment by masterxq** [comment]
> I don't see how the change could cause the driver to fail to read the GCONF register. That register exists and is readable, so it should not error out. Can you please try switching to before and after this change a few more times to confirm that the issue indeed only happens after this PR? To me this sounds a lot like an intermittent connection issue with the driver caused by hardware, not software.

Ok, this may have many other reasons. This patch was just one that seems likely, as on repo top level was no other patches touching TMC driver at all expect this one. But a Hardware issue is at least unlikely, but it still possible that my drivers was in a bad state or something similar.

You don't need to use more time on this, I will report back the next time I updated. If the issue remains I will **double**-check your patch (go just below it and include this patch only), and tell you what I found or not found ^^

Best regards

**Comment by masterxq** [comment]
I updated to the latest version, and I could not reproduce the problem. So I think my previous comment can be ignored. Sorry for wasting your time.

**Pull request merged**
