### PR TITLE
Add spi0e bus for rp2040, used on pitb v2 by fysetc

### PR DESCRIPTION
**Pull request by KoiosLabs**
I purchased the fysetc PITB v2 board, which is not functioning via software spi, and I'm not 100% sure why.  

The issue with hardware spi, is that this board is wired such that:
SCK: gpio2
MOSI: gpio3
MISO: gpio4

however, the spi0 configuration currently in the klipper codebase, only allows an spi permutation of:
SCK: 2
MOSI: 3
MISO: 0

However, that said, I've seen a few cases around the internet in troubleshooting this, that show people using the rp2040 spi bus configured this way, as well as the PITB v2 board.  The rp2040 datasheet (page 13: [here](https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf)) shows it as a supported configuration, so I added spi0e as an option, and everything now started up and works.   

I'd almost suggest perhaps a more configurable way of managing these spi buses for this chip, as many gpio can be used for spi0 for example, but I'm not familiar enough with the klipper code to realize it. This solved my immediate issue so I offer it up for the masses to accept or not :)

Once this is done, the config looks like this for that board:
```
[stepper_x]
step_pin: PITB:gpio6
dir_pin: PITB:gpio5
enable_pin: !PITB:gpio20
rotation_distance: 40
microsteps: 16
full_steps_per_rotation:200  #set to 400 for 0.9 degree stepper
endstop_pin: EBB:PB8
position_min: 0
position_endstop: 350
position_max: 350
homing_speed: 25   #Max 100
homing_retract_dist: 5
homing_positive_dir: true

[tmc5160 stepper_x]
spi_bus: spi0e
cs_pin: PITB:gpio1
interpolate: False
diag1_pin: PITB:gpio7
run_current: 0.800 

[stepper_y]
step_pin: PITB:gpio13
dir_pin: PITB:gpio23
enable_pin: !PITB:gpio22
rotation_distance: 40
microsteps: 16
full_steps_per_rotation:200  #set to 400 for 0.9 degree stepper
endstop_pin: PG6
position_min: 0
position_endstop: 350
position_max: 350
homing_speed: 25  #Max 100
homing_retract_dist: 5
homing_positive_dir: true

[tmc5160 stepper_y] 
spi_bus: spi0e
cs_pin: PITB:gpio21
diag1_pin: PITB:^gpio14
interpolate: False
run_current: 0.8

```

### CODE REVIEW

**Comment by KoiosLabs** [comment]
Good catch, totally didnt even see that,  I'll add a fix shortly :)

**Comment by ejhoness** [comment]
S2, 
Thanks.
for changes and update mcu if i get this.
[klippy (1).log](https://github.com/user-attachments/files/16956298/klippy.1.log)
Captura de tela de 2024-09-10 21-28-48

**Comment by KoiosLabs** [comment]
I'm far from a klipper expert, mostly just stumbling around until i got it working, buut, with that said, I think you need to make sure you've got the PR checked out, and flashed to the PITB for this to work, for example, mine the version looks like this: 
image
image


Take a look at this: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally guide for how to get the pr locally if your unfamiliar, and ignore all this if you did that already and I'm just missing something because it worked fine for me

**Comment by ejhoness** [comment]
Thanks for your attention.

I'm a bit flawed, I must have missed something, I updated everything including the linux process, to "new version" but... I'll do it again based on your git.

Captura de tela de 2024-09-10 23-15-28

**Comment by JamesH1978** [comment]
Thankyou for submitting a PR, please can you sign off your as mentioned in point 3 in https://github.com/Klipper3d/klipper/blob/master/docs/CONTRIBUTING.md#what-to-expect-in-a-review

Thanks
James

**Comment by KoiosLabs** [comment]
> Thankyou for submitting a PR, please can you sign off your as mentioned in point 3 in https://github.com/Klipper3d/klipper/blob/master/docs/CONTRIBUTING.md#what-to-expect-in-a-review
> 
> Thanks James

Hi James,

I think I got that message in there properly, and squashed all my non-sense, so the upstream repo stays clean :)

**Comment by KoiosLabs** [comment]
I think my code should meet all the stuff in the contributing doc.

1) It works, I'm running it on my v2.4 without issue. It passed the regression testing.

2) I've identified the real world benefit (fixing the fysetc PITB board, and enabling hardware spi on this combination of pins on the rp2040).

3) I've signed the commit, and my contribution is fine to be released as public domain, or whatever license klipper is using, no worries.  Its my original work, I just followed the existing code style.

4) see # 3 above (not pr 3 lol, silly git), I matched the code style as best I could with the existing spi bus definitions.

5) I originally went down this rabbit hole, as the various spi bus to pinouts dont seem to have documentation I could find?  If it exists, please let me know and I'll update it accordingly, but I also dont really have time to document everything from scratch, sorry :(

6) I've reduced my work to one squashed commit with the matching commit message format per the documentation.  Its a relatively small change so this seemed appropriate.

**Comment by mboyer85** [comment]
Have you try sensorless ?

**Comment by KoiosLabs** [comment]
I have not, but this is more about the communication bus than the tmc driver implementation, so I cant see why it wouldnt work.  I have no use for sensorless homing on my printer.

**Comment by ejhoness** [comment]
I don't want to abuse it, I know you've already done a lot, and I thank you, I would like to ask you for the pinout.cfg file, so I can make it as similar as possible, because I may be making a mistake in something, like before when there was no pitb update, shameful, but...

Otherwise, I thank everyone for everything. Long life and prosperity. S2

I don't know if it's relevant, but the pin configurations are very similar to fysetc stridemax_dual, with the exception of the endstops, which together with the temperatures are the only ones that worked for me.

**Comment by KoiosLabs** [comment]
> I don't want to abuse it, I know you've already done a lot, and I thank you, I would like to ask you for the pinout.cfg file, so I can make it as similar as possible, because I may be making a mistake in something, like before when there was no pitb update, shameful, but...
> 
> Otherwise, I thank everyone for everything. Long life and prosperity. S2

Hi @ejhoness 

I did post my config for the motors above in the original PR, but if you read through your log, it will start connecting the various MCU's you have on your printer.  In that look for your PITB, and it should list the various SPI and I2C busses it has, if it isnt listing the spi0e bus, then something went wrong with compiling and flashing this change to the mcu.  You shouldnt need to reflash all your mcu's if your on a recent klipper version otherwise, but make sure the PITB is flased with this.  

I basically made sure my klipper/src/rp2040/spi.c had the 6-7 lines updated if you look on the files changed tab here, you can match it up, its a fairly small code file.  Then in the main klipper folder I did:
```
sudo service klipper stop
make clean
make menuconfig
make -j4
python3 ~/katapult/scripts/flashtool.py -i can0 -u eda86b2923a2 -f ~/klipper/out/klipper.bin
sudo service klipper start
```

This assumes you have it setup with katapult as your bootloader already (following something like esoterical's canbus guide for example), so you can flash over canbus.  You obviously need to setup the menuconfig properly for the PITB, like this (again assuming katapult!):

image

Finally you need to make sure the canbus ID in my snippet above is accurate mine is **eda86b2923a2**

Once youve done this all, then check your klipper log for something like:
```
Loaded MCU 'PITB' 121 commands (v0.12.0-293-gde93322de-dirty-20240910_171339-Voron24 / gcc: (15:12.2.rel1-1) 12.2.1 20221205 binutils: (2.39-8+rpi1+18) 2.39)
MCU 'PITB' config: ADC_MAX=4095 BUS_PINS_i2c0a=gpio0,gpio1 BUS_PINS_i2c0b=gpio4,gpio5 BUS_PINS_i2c0c=gpio8,gpio9 BUS_PINS_i2c0d=gpio12,gpio13 BUS_PINS_i2c0e=gpio16,gpio17 BUS_PINS_i2c0f=gpio20,gpio21 BUS_PINS_i2c0g=gpio24,gpio25 BUS_PINS_i2c0h=gpio28,gpio29 BUS_PINS_i2c1a=gpio2,gpio3 BUS_PINS_i2c1b=gpio6,gpio7 BUS_PINS_i2c1c=gpio10,gpio11 BUS_PINS_i2c1d=gpio14,gpio15 BUS_PINS_i2c1e=gpio18,gpio19 BUS_PINS_i2c1f=gpio22,gpio23 BUS_PINS_i2c1g=gpio26,gpio27 BUS_PINS_spi0a=gpio0,gpio3,gpio2 BUS_PINS_spi0b=gpio4,gpio7,gpio6 BUS_PINS_spi0c=gpio16,gpio19,gpio18 BUS_PINS_spi0d=gpio20,gpio23,gpio22 BUS_PINS_spi0e=gpio4,gpio3,gpio2 BUS_PINS_spi1a=gpio8,gpio11,gpio10 BUS_PINS_spi1b=gpio12,gpio15,gpio14 BUS_PINS_spi1c=gpio24,gpio27,gpio26 CANBUS_FREQUENCY=1000000 CLOCK_FREQ=12000000 INITIAL_PINS=gpio15 MCU=rp2040 PWM_MAX=255 RECEIVE_WINDOW=192 RESERVE_PINS_CAN=gpio9,gpio8 STATS_SUMSQ_BASE=256 STEPPER_BOTH_EDGE=1
Configured MCU 'PITB' (1024 moves)
```
the really important key here is:
`BUS_PINS_spi0e=gpio4,gpio3,gpio2`

if that's not listed, then it didnt include this code change, and thus, you cant use the hardware spi configuration that is needed for the mcu processor to actually talk to the TMC drivers to control your motors.  Software spi should work, but I didnt dig into why it actually doesnt, I could probe it and figure it out, but really hardware spi seems superior to me in every way I can think of, why emulate it in software if I dont need to...


Hopefully that helps, I know this is pretty nitty gritty embedded programming stuff that even I dont deal with often, as I'm more an enterprise software dev in my daily life.

**Comment by KevinOConnor** [comment]
Thanks.  We can add this, but we've given up on introducing names like "spi0e".  The new scheme is to use names like "spi0_gpio4_gpio3_gpio2" - see src/stm32/spi.c for examples.

Separately, I agree the spi (and i2c) interface would be better if the pins were passed as parameters explicitly from the host (instead of using these weird bus names).  (Something like what src/atsamd/sercom.c does.)  Something to look at refactoring in 2025.

Cheers,
-Kevin

**Comment by VORONENTHUSIAST** [comment]
Thanks for this - got mine working, appreciate the effort undertaken

**Comment by KoiosLabs** [comment]
I can look in a day or two at renaming the buses using the 'current' ("spi0_gpio4_gpio3_gpio2")  format, but I definitely dont have the cycles to refactor it like the atsamd example sadly.  

I'd be somewhat worried about this breaking a bunch of config files though, a least the approach i used is backwards compatible...  whereas if its renamed, anyone using spi0d etc would need to update to the new name, and they seem rather poorly documented imo, I had to come to the spi source to figure it out, and why it wasnt working.

**Comment by KevinOConnor** [comment]
> or were you suggesting I just add the new spi0e bus as the new format, and leave the existing ones named as is?

Introduce new using the new format.  It'd be nice to also *add* new definitions for the existing buses *in addition* to the existing definitions.  See `src/stm32/stm32f0_i2c.c` for examples of how one would go about declaring both old and new definitions.

-Kevin

**Comment by KoiosLabs** [comment]
I will take a look when I have a few minutes, that sounds like a reasonable approach!

**Comment by KoiosLabs** [comment]
I've started working on using the new naming convention, I was going to look at all the permutations of buses, but i think its unwieldy, and without re-writing to a more dynamic approach, doesnt seem appropriate, its fairly easy to add a new bus as needed, if a board is released using something new and odd.

**Comment by OldGuyMeltsPlastic** [comment]
Hey there, can you confirm if this Katapult config looks correct, or did I miss anything. When I make this and flash it to my PITB v2.0 over USB, it flashes successfully. Then I power off and disconnect USB, connect the CAN Bus cable, and when I power up, all three red LEDs on the PITB light up solid, and the PITB isn't found when I run the CAN Bus query from the command line.
image

**Comment by OldGuyMeltsPlastic** [comment]
Figured out why. I hadn't jumpered the pins that switch the PITB between CAN FD and CAN operations, and so it was defaulting to CAN FD. Once I jumpered those pins, the CAN query was able to return the UUID, and I was able to flash Klipper.

**Comment by jakep82** [comment]
> Hey there, can you confirm if this Katapult config looks correct, or did I miss anything. When I make this and flash it to my PITB v2.0 over USB, it flashes successfully. Then I power off and disconnect USB, connect the CAN Bus cable, and when I power up, all three red LEDs on the PITB light up solid, and the PITB isn't found when I run the CAN Bus query from the command line.
> 
> image
> 
> 

Please don't make help requests in a PR. The correct place to ask questions like this is the Klipper Discourse forum.

**Comment by KoiosLabs** [comment]
I did update this with the new bus name styles, but I want to do a bit more testing, however my printer had a hardware failure, so until I get parts I'm stuck. Hopefully the slow boat gets here soon :)

**Comment by KoiosLabs** [comment]
I've been running this now for a week without any issues, and other than the change below needed in the config I'm happy with how its working.   

`[tmc5160 stepper_y]
spi_bus: spi0_gpio4_gpio3_gpio2
cs_pin: PITB:gpio1
sense_resistor: 0.05 #pitb 
interpolate: False
diag1_pin: PITB:gpio7
run_current: 0.800 

[tmc5160 stepper_x] 
spi_bus: spi0_gpio4_gpio3_gpio2
sense_resistor: 0.05 #pitb 
cs_pin: PITB:gpio21
diag1_pin: PITB:^gpio14
interpolate: True
run_current: 0.8`

**Comment by KevinOConnor** [comment]
Thanks.  In general it seems fine, but I don't think we should add a new old-style "spi0e" name.  The new mapping should be available solely as "spi0_gpio4_gpio3_gpio2".

-Kevin

**Comment by KoiosLabs** [comment]
Sorry, that was a oversight!  Should be removed now.  had it on a couple printers and hadn't changed everyone's config file ;)

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
