### PR TITLE
Fix i2c on stm32g0

### PR DESCRIPTION
**Pull request by KevinOConnor**
This is an alternate approach to PR #5592 - it fixes i2c on stm32g0, but uses less compile time `#ifdefs`.

@retsamedoc - FYI.

-Kevin

### CODE REVIEW

**Comment by retsamedoc** [comment]
Looks good and solves my problem.

**Comment by DrumClock** [comment]
I'm currently testing it with a 0.96 OLED display, still error

image

[klippy (i2c).log](https://github.com/Klipper3d/klipper/files/9430640/klippy.i2c.log)

**Comment by retsamedoc** [comment]
I have tested this on a BTT SKR Mini E3 V3.0 and a 0.96 OLED display without issue. I have to change my i2c_bus from i2c1a (my patch) -> i2c1b (Kevin's) but otherwise it is fine.

Attempting to use 12c1a with that board causes Klipper to fail with: `error: Pin PF1 reserved for crystal - can't reserve for i2c1a` which is what started me down the path of PR #5592 in the first place.

**Comment by DrumClock** [comment]
> I have tested this on a BTT SKR Mini E3 V3.0 and a 0.96 OLED display without issue. I have to change my i2c_bus from i2c1a (my patch) -> i2c1b (Kevin's) but otherwise it is fine.
> 
> Attempting to use 12c1a with that board causes Klipper to fail with: `error: Pin PF1 reserved for crystal - can't reserve for i2c1a` which is what started me down the path of PR #5592 in the first place.

What I describe above is an OLED 0.96 connected via I2C on the EBB 42 CAN V1.2 board and not on the main mcu board!
There it is with OLED and I2C in perfect order.

**Comment by DrumClock** [comment]
### If I connect the OLED to PB6 and PB7, communication and the display are functional. On this connector, in the EBB CAN V1.1 version (STM32G0B1), Endstop sensors are output, not I2C.

**Comment by retsamedoc** [comment]
@DrumClock While I believe adding support for what is marked as I2C on the EBB v1.1 is somewhat trivial, the pinout of each board is up to the manufacturer. I believe what you are asking for is to add the definition of PB3/PB4 as i2c2 to this PR.

I would think it best if this PR were merged and a new one created to add in the support you seek after it can be tested. I do not have an EBB v1.1 to test it out. Otherwise, we might as well scour the datasheet and define i2c2 as:
- PB3/PB4
- PB6/PB7
- PB10/PB11
- PB13/PB14
- PA9/PA10

But that's only coverage for the STM32G0B1xx. Not sure if @KevinOConnor wants to do all permutations or just as the need arises.

**Comment by DrumClock** [comment]
Hi @retsamedoc Yes, it is as you describe.
I don't know why BTT changed the I2C bus to pins PB3, PB4 (designation SMT32 ... i2c2) for EBB V1.1 and V1.2. 
It is probably due to a different STM32 chip. I believe that other pins will also be changed between EBB versions.

@KevinOConnor - FYI.

**Comment by DrumClock** [comment]
HI
below a comparison of I2c and SPI versions and buses.
In my opinion, "`make menuconfig"` will cause a wrong setting. I will still try others like **ADXL** and **MAX31865**.

EBB42 CAN

**Comment by DrumClock** [comment]
Hi,
Yes, if I enable **MAX31865** it reports pin collision due to  **STM32G0B1** misconfiguration,

```
 sensor_type:MAX31865
 sensor_pin: EBBCan0: PA4
 spi_bus: spi1
 rtd_nominal_r: 100
 rtd_reference_r: 430
 rtd_num_of_wires: 2

```
image

**Comment by KevinOConnor** [comment]
FYI, this PR doesn't do what I initially intended it to do.  I thought the stm32g0 didn't have PF0/PF1 pins and it was just a matter of not supporting buses on pins that do not exist.  However, the stm32g0 does have PF0/PF1 pins, and just doesn't define i2c for those pins.  So, it really shouldn't be defining the bus for those pins.  I'll try to update this PR with an appropriate fix.

Separately, yes, the stm32g0 will need to define additional bus definitions so that it can support PB3/PB4.

-Kevin

**Comment by KevinOConnor** [comment]
I have reworked this branch.  Hopefully it is working now.  For i2c on PB3/PB4 use this branch with the i2c bus name of `i2c3_PB3_PB4`.

Sorry for the confusion.
-Kevin

**Comment by DrumClock** [comment]
> 
HI @KevinOConnor 
**NO** , neither the original `i2c1` nor the new `i2c3_PB3_PB4` work.
Only setting  `i2c_bus: i2c1_PB6_PB7` works.


**my working configuration**

image

mcu constants:
```
printer['mcu EBBCan_0'].mcu_constants = 
{ u'PWM_MAX': 255,
 u'BUS_PINS_i2c1_PB6_PB7': u'PB6,PB7',
 u'BUS_PINS_spi2a': u'PC2,PC3,PB10',
 u'BUS_PINS_i2c2_PB10_PB11': u'PB10,PB11',
 u'BUS_PINS_spi3': u'PB4,PB5,PB3',
 u'BUS_PINS_spi2': u'PB14,PB15,PB13',
 u'STEPPER_BOTH_EDGE': 1,
 u'ADC_MAX': 4095,
 u'RESERVE_PINS_USB': u'PA11,PA12',
 u'CLOCK_FREQ': 64000000,
 u'BUS_PINS_spi1': u'PA6,PA7,PA5',
 u'BUS_PINS_i2c1_PB8_PB9': u'PB8,PB9',
 u'BUS_PINS_i2c2_PB13_PB14': u'PB13,PB14',
 u'RESERVE_PINS_crystal': u'PF0,PF1',
 u'MCU': u'stm32g0b1xx',
 u'BUS_PINS_i2c1_PA9_PA10': u'PA9,PA10',
 u'BUS_PINS_i2c3_PB3_PB4': u'PB3,PB4',
 u'BUS_PINS_spi1a': u'PB4,PB5,PB3',
 u'STATS_SUMSQ_BASE': 256 }
```

image

klippy log:   [klippy.log](https://github.com/Klipper3d/klipper/files/9493915/klippy.log)

**Comment by KevinOConnor** [comment]
> NO , neither the original i2c1 nor the new i2c3_PB3_PB4 work.

If you pull the latest code from this branch (commit 289a3076) does that work with `i2c3_PB3_PB4`?

-Kevin

**Comment by DrumClock** [comment]
**i did "git pull" and "make" ....and it works**

image

**Comment by ReXT3D** [comment]
I can also confirm that this PR applied to the current mainline works perfectly well with BTT EBB42 i2c connector.  I am successfully running Adafruit BME680 connected to the EBB42 with the following configuration:

```
[temperature_sensor bme680]
sensor_type: BME280
i2c_address: 119
i2c_mcu: can
i2c_bus: i2c3_PB3_PB4
```

image

**Comment by KevinOConnor** [comment]
Thanks for testing.  I committed this change.

-Kevin

**Pull request merged**
