### PR TITLE
docs:  List/Table/Title Indentation Correction

### PR DESCRIPTION
**Pull request by dingyifei**
- Aligned some tables
- Added blank line to before and after some lists to match most lists
- Changed some bold text to titles
- Added blank line before and after some titles
- Removed some extra blank lines
- use fenced code block instead of the indented code block to match other docs
- Corrected some indentation errors on the title and lists

Signed-off-by: Yifei Ding <yifeiding@protonmail.com>

### CODE REVIEW

**Comment by dingyifei** [comment]
Any updates?

**Comment by KevinOConnor** [comment]
Sorry - I didn't see that the commits were updated.

-Kevin

**Comment by dingyifei** [comment]
Should I separate them into smaller commits each targeting one file?

**Comment by KevinOConnor** [comment]
I need to review your current set of commits.  Unfortunately, I'm behind on PRs and it'll still be some time before I can take a closer look.

-Kevin

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
