### PR TITLE
src/linux/main: Lock Memory and Increase Priority

### PR DESCRIPTION
**Pull request by mattaw**
Real-time programming best practice is to lock real-time processes memory to prevent paging under memory pressure.
As The Linux MCU process has well bounded memory and a small RAM footprint locking the entire process' current and
future memory has no downsides. (See bootlin training and Linux Foundation documentation linked below.) Additionally, RT 
process priority ranges from 0-99 (although POSIX only requires 32), boost MCU process priority to half the max/2 to improve behavior when the system is considering real-time kernel processes or user processes.

Reference links:
bootlin: https://bootlin.com/doc/training/preempt-rt/preempt-rt-slides.pdf Linux Foundation: https://wiki.linuxfoundation.org/realtime/documentation/howto/applications/application_base#howto_build_a_simple_rt_application

Signed-off-by: Matthew Swabey <matthew@swabey.org>

### CODE REVIEW

**Comment by mattaw** [comment]
I have an improvement to the MPU-* accelerometers that I will be submitting after more testing on more platforms which builds on this improvement, but this seems a nice standalone PR with no downsides so I am submitting it separately.

**Comment by Jookia** [comment]
It might be better to consider changing from SCHED_FIFO to SCHED_DEADLINE which is meant for real-time use cases

**Comment by mattaw** [comment]
I believe both SCHED_FIFO, SCHED_RR & DEADLINE are all real time schedulers. https://wiki.linuxfoundation.org/realtime/documentation/technical_basics/sched_policy_prio/start

**Comment by Jookia** [comment]
SCHED_FIFO and SCHED_RR just give the tasks much higher priority, they don't actually guarantee you get time to run. See https://man7.org/linux/man-pages/man7/sched.7.html

**Comment by mattaw** [comment]
@Jookia your suggestion works a lot better than what I was doing, and is likely to work properly for the widest range of klipper hosts. I'll submit a deadline scheduled version tomorrow.

**Comment by Jookia** [comment]
That's super cool to hear! If I had a Linux board I'd test it. Good luck :)

**Pull request closed without merging**
