### PR TITLE
Anycubic Vyper

### PR DESCRIPTION
**Pull request by mneuhaus**
This adds support and example config for the Anycubic Vyper.

Discussion is happening in Discord (#misc-mainboard)

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  However, due to time constraints on my side, it's difficult for me to track lots of open PRs.  If you want to discuss a config, the Klipper Discourse server may be a better option - https://community.klipper3d.org/

-Kevin

**Comment by mneuhaus** [comment]
Hey,

yea, we're already talking about it in the #misc-mainboard section for a while.
So far everything seems to work now, i mostly need to clean the config up and add some instructions to compile, etc. at the top.

MOGOS#5704 on Discord already verified as well, that these Changes work.

Cheers
Marc

**Review by Thatcooldevguy — APPROVED** [review]
Looks great to me, all it needs is some docs, and its good to go :)

**Comment by mneuhaus** [comment]
@Thatcooldevguy i've updated the PR with some Cleanup and Docs in the Example.
i've also added the config to the printer.test file but now that fails with the Error ```Error: Pin 'PB12' is not a valid pin name on mcu 'mcu'```.
i only have the PB12 pin in the Probe, do you have an idea what the test fails because of that?

**Comment by mneuhaus** [comment]
@Thatcooldevguy i found and fixed he issue, i had the test included unter the other anycubic tests, but the vyper is a stm32 instead of atmega 🙈

**Comment by KevinOConnor** [comment]
Thanks.  In general, the config looks fine, but I did see a couple of things:
1. Commits need to have a signed-off-by line containing your real full name - https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md
2. The `PID_Kx` lines should use `value: ` instead of `value = ` syntax - https://www.klipper3d.org/Example_Configs.html
3. It would be nice if a `gear_ratio` was specified for the extruder (by counting the gears in the extruder mechanism), as it's generally preferable to use a `rotation_distance` corresponding to the circumference of the hobbed bolt that engages the filament.

-Kevin

**Comment by Dexter4637** [comment]
Hello,
any updates on this pr? @mneuhaus

**Comment by Crykor90** [comment]
good news @mneuhaus  will open a new request and fix the small form errors. He is currently just a little busy and therefore it may take some time. Let's hope he can spare a few minutes soon so we can have the Vyper officially in klipper.

**Comment by Crykor90** [comment]
# This file contains a configuration for the Anycubic Vyper printer from 2021.
# It uses a clone of the STM32F103 chip named GD32F103.
# There are 2 Mainboard versions out there v0.0.5 and v0.0.6, this config has
# been tested with the v0.0.6 only. It should probably work for v0.0.5 as well
# since there are no different changes in the Anycubic Marlin firmware.
# The LCD is not supported yet (might work, but didn't try yet).
#
# To create the Firmware you need to use the following configuration:
#     - Micro-controller: STM32
#     - Processor model: STM32F103
#     - Bootloader offset: 32KiB
#     - Communication interface: Serial (on USART1 PA10/PA9)
#
# To install the Firmware rename the klipper bin to `main_board_20xxxxxx.bin`
# and copy it to an SD Card.
# Power off the Printer, insert the SD Card and power it on.
# It should beep several times and the LCD should be stuck on the Splash screen.
# Now you should be able to connect to the Printer, you might need to change
# the mcu/serial setting in this config according to your set up.
#
# If you want to revert the Firmware back to Marlin you simply need to flash it
# with a anycubic firmware through the SD Card

[stepper_x]
step_pin: PC2
dir_pin: PB9
enable_pin: !PC3
microsteps: 16
rotation_distance: 40
endstop_pin: !PA7
position_min: -3
position_endstop: -3
position_max: 245
homing_speed: 30.0

[stepper_y]
step_pin: PB8
dir_pin: PB7
enable_pin: !PC13
microsteps: 16
rotation_distance: 32
endstop_pin: !PC5
position_min: -17
position_endstop: -17
position_max: 245
homing_speed: 30.0

[stepper_z]
step_pin: PB6
dir_pin: !PB5
enable_pin: !PC14
microsteps: 16
rotation_distance: 8
endstop_pin: PB2
position_endstop: 0.0
position_max: 260
position_min: -3
homing_speed: 5.0

[stepper_z1]
step_pin: PC0
dir_pin: !PC1
enable_pin: !PC15
microsteps: 16
rotation_distance: 8
#endstop_pin: PC6

[extruder]
step_pin: PB4
dir_pin: !PB3
enable_pin: !PA15
microsteps: 16
rotation_distance: 22.4408158
gear_ratio: 50:17
full_steps_per_rotation: 200
nozzle_diameter: 0.400
filament_diameter: 1.750
heater_pin: PA1
sensor_type: ATC Semitec 104GT-2
sensor_pin: PC4
control: pid
pid_kp: 28.937
pid_ki: 1.295
pid_kd: 161.688
min_temp: 0
max_temp: 260
pressure_advance: 0.678400
pressure_advance_smooth_time: 0.040000

[heater_fan extruder_fan]
pin: PB1

[heater_bed]
heater_pin: PA4
sensor_type: EPCOS 100K B57560G104F
sensor_pin: PB0
#control: pid
#pid_kp = 67.648
#pid_ki = 1.044
#pid_kd = 1095.893
min_temp: 0
max_temp: 110

[fan]
pin: PA0

[probe]
pin: !PB12
z_offset: 0
activate_gcode:
    probe_reset

[output_pin probe_reset_pin]
pin: PB13

[bed_mesh]
mesh_min: 15,15
mesh_max: 230, 230
probe_count: 6,6

[filament_switch_sensor runout]
pause_on_runout: True
switch_pin: PA5

[mcu]
serial: /dev/ttyUSB0
restart_method: command

[safe_z_home]
home_xy_position: -3,-17
z_hop: 10

[printer]
kinematics: cartesian
max_velocity: 300
max_accel: 3000
max_z_velocity: 10
max_z_accel: 100

[gcode_macro probe_reset]
gcode:
    SET_PIN PIN=probe_reset_pin VALUE=0
    G4 P300
    SET_PIN PIN=probe_reset_pin VALUE=1
    G4 P100

[gcode_macro wipe_nozzle]
gcode:
    # intro line
    G92 E0
    G1 X0 Y-10 Z0.2 F3000
    G1 E15 F100
    G92 E0
    G1 X60 E15 F600 ; Print a line
    G1 X120 E0 F1000 ; Wipe
    G92 E0 ; reset extruder

[gcode_macro START_PRINT]
gcode:
    {% set BED_TEMP = params.BED_TEMP|default(60)|float %}
    {% set EXTRUDER_TEMP = params.EXTRUDER_TEMP|default(190)|float %}
    # Start bed heating
    M190 S{BED_TEMP}
    # Start nozzle heating
    M109 S{EXTRUDER_TEMP}
    # Home the printer
    G28
    # Bed Mesh Calibration
    #BED_MESH_CALIBRATE
    # Reset the G-Code Z offset (adjust Z offset if needed)
    SET_GCODE_OFFSET Z=0.2
    # Wipe the nozzle
    wipe_nozzle
    # Go to start position
    G90
    G1 Z10 F3000
    G1 X0 Y0 F3000

[gcode_macro END_PRINT]
gcode:
    # Turn off bed, extruder, and fan
    M140 S0
    M104 S0
    M106 S0
    # Move nozzle away from print while retracting
    G91
    G1 X-2 Y-2 E-3 F300
    # Raise nozzle by 10mm
    G1 Z30 F3000
    G90
    G1 X245 Y245 F6000
    # Disable steppers
    M84

[include mainsail.cfg]

**Comment by Crykor90** [comment]
[extruder]
step_pin: PB4
dir_pin: !PB3
enable_pin: !PA15
microsteps: 16
rotation_distance: 22.4408158
gear_ratio: 50:17
full_steps_per_rotation: 200
nozzle_diameter: 0.400
filament_diameter: 1.750
heater_pin: PA1
sensor_type: ATC Semitec 104GT-2
sensor_pin: PC4
control: pid
pid_kp: 28.937
pid_ki: 1.295
pid_kd: 161.688
min_temp: 0
max_temp: 260
pressure_advance: 0.678400
pressure_advance_smooth_time: 0.040000



Added Pressure Advance (should be calibrated by everyone himself)

Fully tested works great!!!

**Pull request closed without merging**
