### PR TITLE
Fixed typo in config option name

### PR DESCRIPTION
**Pull request by usrhere**
I believe I've found typo in docs

Signed-off-by: Joseph Vilimas 4to5@protonmail.com

### CODE REVIEW

**Comment by usrhere** [comment]
Ok, thanks, now it's fully signed.

**Comment by dmbutyugin** [comment]
Sorry to nag, but I think the commit itself should follow that format. You can use `git commit --amend` to update it (please format the first line as `docs: fixed typo in config option name`, blank line, then Signed-off-by line). Thanks!

**Comment by usrhere** [comment]
Hope it's ok now :) Thanks for the guidance!

**Review by dmbutyugin — APPROVED** [review]
Thanks, looks good!

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
