### PR TITLE
printer-anycubic-predator-2020.cfg

### PR DESCRIPTION
**Pull request by lorenzing**
module: Anycubic-Predator configuration

Hello everyone, I share with you the configuration file of the Anycubic Predator printer, with original Trigorilla Pro board.

Signed-off-by: Lorenzo Franco (lorenzo.franco@lorenzing.com)

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  However, this config would need to follow the guidance at https://www.klipper3d.org/Example_Configs.html - at a minimum point 4 and 7e.

It's also a good idea to set the appropriate gear_ratio for the extruder file (point 7e).

Also, all known Klipper boards work with the default baud of 250000, so a config should not recommend setting a different baud rate.

-Kevin

**Comment by lorenzing** [comment]
> Thanks. However, this config would need to follow the guidance at https://www.klipper3d.org/Example_Configs.html - at a minimum point 4 and 7d.
> 
> It's also a good idea to set the appropriate gear_ratio for the extruder file (point 7e).
> 
> Also, all known Klipper boards work with the default baud of 250000, so a config should not recommend setting a different baud rate.
> 
> -Kevin

Thanks @KevinOConnor, I made the required changes except the baud rate. 
The trigorilla pro is a problematic board (there are other issues regarding it, for example:  #3379 ).
Unfortunately, the maximum baudrate at which I managed to obtain stable operation is 115200. If you want I can still put 230400 which is the theoretical maximum for pl2303.
To help other users I can create a generic file on the trigorilla pro.

Thanks so much
Lorenzo

**Comment by lorenzing** [comment]
I have a problem, the printer works correctly but after entering the configuration in test / klippy / printers.test I see that for this mcu the pins are reserved by default for the usb: RESERVE_PINS_USB = PA11, PA12
The problem is that on the trigorilla pro the pin PA12 is dedicated to the endstop of the Y axis while for the USB Serial communication it uses the USART1
- USART1 TX = PA9 (to RX pin of the PL2303)
- USART1 RX = PA10 (to TX pin of the PL2303)

How can I solve? Thanks

**Comment by lorenzing** [comment]
I am attaching the klippy log of the working printer:
[klippy.log.txt](https://github.com/Klipper3d/klipper/files/8603652/klippy.log.txt)

**Comment by KevinOConnor** [comment]
> I have a problem, the printer works correctly but after entering the configuration in test / klippy / printers.test I see that for this mcu the pins are reserved by default for the usb

If the board uses serial, then you would add it to the section in printers.test for `Printers using the stm32f103 via serial`.  But, the example config file instructs users to enable USB, while it seems you want to instruct them to use UART on PA10/PA9?

> Unfortunately, the maximum baudrate at which I managed to obtain stable operation is 115200.

Okay, can you provide more detail on what occurs when you use the default of 250000 baud?  Can you provide a Klipper log file from the test?

Otherwise, the config looks fine to me.

Thanks,
-Kevin

**Comment by lorenzing** [comment]
> If the board uses serial, then you would add it to the section in printers.test for Printers using the stm32f103 via serial. But, the example config file instructs users to enable USB, while it seems you want to instruct them to use UART on PA10/PA9?

The problem is that, on this board the usb is mapped to the UART on PA10 / PA9 through a pl2303. I have seen several users with communication problems between klipper and this board ( #2822 #3379 ).
When I compile the firmware I go to indicate the UART on PA10 / PA9 but this corresponds to the USB port in reality.
The pin scheme that I was able to partially verify is that: https://3dmixers.com/m/123405-trigorilla-pro-schematics-and-reverse-engineering

> Okay, can you provide more detail on what occurs when you use the default of 250000 baud? Can you provide a Klipper log file from the test?

Yes sure, I've recompiled and flashed the board with firmware at 250000 baudrate (it does the same even if I put 230400 baud):
```
[display_status]
=======================
Delta max build height 454.51mm (radius tapered above 391.31mm)
Delta max build radius 209.65mm (moves slowed past 188.70mm and 205.20mm)
Extruder max_extrude_ratio=0.266081
Starting serial connect
Timeout on serial connect
Wait for identify_response
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/serialhdl.py", line 68, in _get_identify_data
    params = self.send_with_response(msg, 'identify_response')
  File "/home/pi/klipper/klippy/serialhdl.py", line 188, in send_with_response
    return src.get_response(cmd, self.default_cmd_queue)
  File "/home/pi/klipper/klippy/serialhdl.py", line 242, in get_response
    self.serial.raw_send_wait_ack(cmd, minclock, minclock, cmd_queue)
  File "/home/pi/klipper/klippy/serialhdl.py", line 180, in raw_send_wait_ack
    raise error("Serial connection closed")
error: Serial connection closed
Timeout on serial connect
```
[klippy.log_250000.txt](https://github.com/Klipper3d/klipper/files/8604770/klippy.log_250000.txt)

**Comment by KevinOConnor** [comment]
Thanks.  Two comments here:
1. I'm confused by the comments at the top of this config file.  It says to use "usb for communications" in "make menuconfig", but clearly that can't be correct as one would need to select "uart for communication" on this board.
2. I'd like to see a few others confirm that this board does not work at a baud of 250000.  It is possible this is the first board that requires a baud of 115200.  However, without exaggeration, I've seen well over 100 claims that various boards needed a particular baud rating that were not correct (every board Klipper supports to date works at 250000 baud).  So, given the prevalent amount of misinformation on baud rate I feel getting confirmation is important.

Cheers,
-Kevin

**Comment by lorenzing** [comment]
Thanks Kevin and sorry for the delay!
> 
> 1. I'm confused by the comments at the top of this config file.  It says to use "usb for communications" in "make menuconfig", but clearly that can't be correct as one would need to select "uart for communication" on this board.
>
Sorry I made a copy and paste mistake.

> 2. I'd like to see a few others confirm that this board does not work at a baud of 250000.  It is possible this is the first board that requires a baud of 115200.  However, without exaggeration, I've seen well over 100 claims that various boards needed a particular baud rating that were not correct (every board Klipper supports to date works at 250000 baud).  So, given the prevalent amount of misinformation on baud rate I feel getting confirmation is important.
> 
I found a person who seems to have the same problem (issue #3379), unfortunately she never showed up again. 
I ask you if possible to keep this pull request open and in the meantime I write on the facebook group of this printer if someone can do some tests at different baudrates.

Best regards,
Lorenzo

**Comment by lorenzing** [comment]
I don't know if I can post the link to an external site but here they talk about the same problem, always trigorilla pro but on another printer. If you can't, delete the comment.
[https://drucktipps3d.de/forum/topic/i3-mega-trigorilla-pro-und-klipper/](url)

**Comment by rubydesign** [comment]
Sorry to see this closed. It is the best config for a predator that i've seen.
Unfortunately i can't confirm now because i installed an octopus even before finding this.

But @lorenzing what did you do with the bed levelling probe? Did i just miss that?

**Pull request closed without merging**
