### PR TITLE
Adding Hardware PWM support for the STM32F4 processors

### PR DESCRIPTION
**Pull request by jrhelbert**
This expands the work done by @1am3r and adds the HW PWM definitions for the STM32F466. Pin mappings and alternate function definitions pulled from https://www.st.com/resource/en/datasheet/stm32f446mc.pdf (starting on page 57.)

About a half dozen of these pins have been confirmed working on a BTT Octopus. It would be considerable work to test everything defined here, so hopefully this is sufficient.

Signed-off-by: Jerome Helbert <jerome@helbert.net>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  In general, the change looks fine to me, but commits need to have a signed-off-by line containing your real full name - see: https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md .

Separately, out of an abundance of caution, this is something that I'd look at merging after the Klipper v0.10.0 release.

-Kevin

**Comment by jrhelbert** [comment]
Missed that, thanks. I updated my pull request text, do I also need to go in and push a commit with that and update the pull request?

**Comment by KevinOConnor** [comment]
No, you're all set now.  I can update the commit message from your sign-off in the comments above.

Thanks,
-Kevin

**Comment by jrhelbert** [comment]
Thanks, added in a little cleanup for redundant pins for better timer utilization.

As for waiting till after v0.10.0, that's no problem

**Comment by ShohninDmitriy** [comment]
Partially tested the HARD_PWM pin chip on the OCTOPUS V1.1 motherboard

https://github.com/ShohninDmitriy/klipper/blob/master/src/stm32/hard_pwm.c

**Comment by jrhelbert** [comment]
> Partially tested the HARD_PWM pin chip on the OCTOPUS V1.1 motherboard
> 
> https://github.com/ShohninDmitriy/klipper/blob/master/src/stm32/hard_pwm.c

Looking at your comment about the duplicate A7 pin entries, I must have missed that one. I tried to cut out all the duplicates, but looks like I missed one.

As for which timer was being used when you tested it, the code iterates through the list and uses the first timer that it finds that matches the pin requested. So in my code HW PWM on A7 would use Timer 3 (and that is likely how I tested it), whereas in your code it would use Timer 14.

I don't have my test setup together anymore to verify, so if you were able to successfully test A7 on Timer 14 then I would recommend your approach and we drop the A7 reference in Timer 3.

**Comment by ShohninDmitriy** [comment]
> 
> 
> > Partially tested the HARD_PWM pin chip on the OCTOPUS V1.1 motherboard
> > https://github.com/ShohninDmitriy/klipper/blob/master/src/stm32/hard_pwm.c
> 
> Looking at your comment about the duplicate A7 pin entries, I must have missed that one. I tried to cut out all the duplicates, but looks like I missed one.
> 
> As for which timer was being used when you tested it, the code iterates through the list and uses the first timer that it finds that matches the pin requested. So in my code HW PWM on A7 would use Timer 3 (and that is likely how I tested it), whereas in your code it would use Timer 14.
> 
> I don't have my test setup together anymore to verify, so if you were able to successfully test A7 on Timer 14 then I would recommend your approach and we drop the A7 reference in Timer 3.

I checked almost everything I could, now you can clean up the broken ones

**Comment by jrhelbert** [comment]
> > > Partially tested the HARD_PWM pin chip on the OCTOPUS V1.1 motherboard
> > > https://github.com/ShohninDmitriy/klipper/blob/master/src/stm32/hard_pwm.c
> > 
> > 
> > Looking at your comment about the duplicate A7 pin entries, I must have missed that one. I tried to cut out all the duplicates, but looks like I missed one.
> > As for which timer was being used when you tested it, the code iterates through the list and uses the first timer that it finds that matches the pin requested. So in my code HW PWM on A7 would use Timer 3 (and that is likely how I tested it), whereas in your code it would use Timer 14.
> > I don't have my test setup together anymore to verify, so if you were able to successfully test A7 on Timer 14 then I would recommend your approach and we drop the A7 reference in Timer 3.
> 
> I checked almost everything I could, now you can clean up the broken ones

You commented and removed a large number of pins, what's the reasoning there? Was it something you needed to run everything, or just cleaning things up for your specific build?

**Comment by ShohninDmitriy** [comment]
> You commented and removed a large number of pins, what's the reasoning there? Was it something you needed to run everything, or just cleaning things up for your specific build?

No, I checked everything that works and there is still something to remove, since some pins have the same timer and register and a function, which leads when using both signals to symmetrically change on both pins. Eg

```
 {TIM2,  GPIO('A',  5),  **1**, GPIO_FUNCTION(**1**)}, //  EXP2_2  Working
//    {TIM2,  GPIO('A', 15),  **1**, GPIO_FUNCTION(**1**)}, //SPI3    Working
```

```
//    {TIM3,  GPIO('A',  7),  **2**, GPIO_FUNCTION(**2**)}, // EXP2_6          
//    {TIM3,  GPIO('B',  5),  **2**, GPIO_FUNCTION(**2**)}, // SPI3             
```
Analog signals conflict
```
 {TIM10, GPIO('B',  8),  **1**, GPIO_FUNCTION(**3**)}, //   I2C_SCL       
//    {TIM10, GPIO('F',  6),  **1**, GPIO_FUNCTION(**3**)}, // T2

{TIM11, GPIO('B',  9),  **1**, GPIO_FUNCTION(**3**)}, //   I2C_SDA         
//    {TIM11, GPIO('F',  7),  **1**, GPIO_FUNCTION(**3**)}, // T3

  {TIM13, GPIO('A',  6),  **1**, GPIO_FUNCTION(**9**)}, //   EXP2_1          
//    {TIM13, GPIO('F',  8),  **1**, GPIO_FUNCTION(**9**)}, // PT100
    {TIM14, GPIO('A',  7),  **1**, GPIO_FUNCTION(**9**)} //    EXP2_6         
//    {TIM14, GPIO('F',  9),  **1**, GPIO_FUNCTION(**9**)} //  STEP_DRIVER4

   {TIM4,  GPIO('B',  6),  **1**, GPIO_FUNCTION(**2**)}, // PWM_BL_TOUCH     
    {TIM4,  GPIO('D', 12),  **1**, GPIO_FUNCTION(**2**)}, //   FAN2            
//    {TIM4,  GPIO('B',  7),  **2**, GPIO_FUNCTION(**2**)}, // END_BL_TOUCH     
    {TIM4,  GPIO('D', 13),  **2**, GPIO_FUNCTION(**2**)}, //   FAN3  
```

**Comment by ShohninDmitriy** [comment]
Returned duplicates with marks on them

**Comment by ShohninDmitriy** [comment]
https://github.com/ShohninDmitriy/klipper/blob/master/src/stm32/hard_pwm.c
Added a comparison of 4 motherboards

**Comment by dewi-ny-je** [comment]
Aren't all STM32F4xx processors supporting that feature? I searched quickly for stm32f407 pwm and I got
https://stm32f4-discovery.net/2014/05/stm32f4-stm32f429-discovery-pwm-tutorial/
and other pages which treat equally the various f4xx boards.
The number of channels differs, but the hardware pwm is there.

Maybe the commit could introduce the feature in all supported f4xx boards, for completeness.

**Comment by joaobarros** [comment]
> Aren't all STM32F4xx processors supporting that feature? I searched quickly for stm32f407 pwm and I got https://stm32f4-discovery.net/2014/05/stm32f4-stm32f429-discovery-pwm-tutorial/ and other pages which treat equally the various f4xx boards. The number of channels differs, but the hardware pwm is there.
> 
> Maybe the commit could introduce the feature in all supported f4xx boards, for completeness.

Like the 429 on the newly released Octopus Pro :)

**Comment by Ramalama2** [comment]
@jrhelbert Sorry to annoy, but is it possible that you implement hardware_pwm for the stm32f042 either? :-)
Thats a much simpler block diagram as the 446/429/407 xD
https://www.st.com/resource/en/datasheet/stm32f042.pdf

I would do this, but my understanding is utterly limited xD

**Comment by Ramalama2** [comment]
I found out that this should be correct according to the PDF sheet, but it doesn't work, can anyone give me a hint :-(
`    {TIM2,  GPIO('A',  0),  1, GPIO_FUNCTION(2)},
    {TIM2,  GPIO('A',  1),  2, GPIO_FUNCTION(2)},
    {TIM2,  GPIO('A',  2),  3, GPIO_FUNCTION(2)},
    {TIM2,  GPIO('A',  3),  4, GPIO_FUNCTION(2)},
    {TIM3,  GPIO('A',  7),  1, GPIO_FUNCTION(1)}
`
Thats for example only for these pins: PA0, PA1, PA2, PA3, PA7
The reson is simply, that i want to make the "Klipper Expander" hardware_pwm capable, to control leds with it.

Thanks in advance!

**Pull request merged**
