### PR TITLE
Anycubic 4 Max Pro 2.0: Added two internal systems (beeper and PSU control).

### PR DESCRIPTION
**Pull request by int-0x03**
Hello there! I have added to klipper config for Anycubic 4 Max Pro 2.0 two internal stock systems. First one is internal beeper, and I created M300: "Play Tone" G-Code macro, according to Marlin G-Codes.
Second one, I added M81: "Power Off" G-Code macro, according to Marlin G-Codes. This command will be wait until hotend cool down, and then power off printer. Stock firmware do the same things. 

-- Signed-off-by: Usachev Alexander Valer'evich <int_0x21@protonmail.com>

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  It looks okay to me.  I'll give a couple of days to see if others have comments, and otherwise commit.

-Kevin

**Comment by int-0x03** [comment]
Demo video :)

**Comment by mental405** [comment]
Looks ok to me since it is just replicating stock firmware functionality.

**Comment by int-0x03** [comment]
@mental405 It's a good question! Possible you can help me to improve this feature. Just give some advice. Let's deep down to marlin code. In Marlin autopoweroff code for this printer looks like:

```c++
void DwinTFTClass::PowerDown()
{
  //marlin PSU_OFF() don't work
  #if PIN_EXISTS(PS_ON)
    #ifdef DWIN_TFT_DEBUG
      SERIAL_ECHOLNPGM("TFT Serial Debug: Power down");
    #endif
    for(unsigned char i = 0; i < 3; i++)
    {
      WRITE(PS_ON_PIN, LOW);
      delay(10);
      WRITE(PS_ON_PIN, HIGH);
      delay(10);
    }
  #endif
}
```

I just made some calculations, and got 0.02 duty_cycle and pulse width 50%. Just do the same thing, but use PWM. I don't know, maybe this implementation may cause some performance problems, or any other type of problems, but I used it for a long time (about 1 year) and have no problems.

**Comment by mental405** [comment]
I am thinking that is so the PS pin cycles between high and low a few times depending on how the relay is triggered. (Active HIGH vs Active Low) idk, its kind of confusing to me. I would try taking the relay pin and just pulling it low and see what happens. It might turn the thing off without needing the other tomfoolery.

**Comment by int-0x03** [comment]
@mental405 Unfortunately when I was making this functionality for myself I tried HIGH on a pin and I tried LOW.  This does not work.  Only after I repeated the behavior of the Marlin code did I get the result.  Inside is a relay module from Anycubic.

**Comment by KevinOConnor** [comment]
Alas, I don't see a signed-off-by line.  I'll need that to commit - see https://www.klipper3d.org/CONTRIBUTING.html .

-Kevin

**Comment by int-0x03** [comment]
> Alas, I don't see a signed-off-by line.  I'll need that to commit - see https://www.klipper3d.org/CONTRIBUTING.html .
> 
> 
> 
> -Kevin

Ok, I will fix it, soon

**Comment by int-0x03** [comment]
Sorry for late feedback. Done.

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
