### PR TITLE
bed_mesh: behavior fixes

### PR DESCRIPTION
**Pull request by Arksine**
This includes two minor fixes to the behavior of bed_mesh.

1) Avoid probing additional points for the `zero_reference_position` and `faulty_regions` when the user chooses the "manual" method.  Those options aren't useful when probing manually.

2) Fix a reporting regression introduced by the adaptive mesh change.  Since we avoid saving the mesh, the value reported in the `profile_name` field will be whatever was previously stored in `ProfileManger.current_profile`.   This is often an empty string, which is leading some frontends to believe that no mesh is loaded.  This patch moves profile name tracking to the ZMesh class and generates a placeholder name for adaptive meshes.

Kevin, this is likely going to cause a merge conflict with #6459, so if you would like we can hold this PR until its merged and I will resolve the conflicts.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
Thanks.  I don't think we should wait for #6459 - I'll rebase that PR as needed.  Let me know when you'd like me to commit this PR.

-Kevin

**Comment by kyleisah** [comment]
Wow awesome work @Arksine with the quick fix!

**Comment by Arksine** [comment]
Sounds good.  I have tested the changes here and everything works as expected.  You can commit when ready.

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
