### PR TITLE
Add Artillery Sidewinder X2 2022 stock printer.cfg

### PR DESCRIPTION
**Pull request by freakydude**
Hey guys, 

after many hours of testing I like to add my Artillery Sidewinder X2 printer config, because there is no example in this repository. 
Its for the unmodified stock model, buyed in 2022. 

For the Mainsail stack the mainsail.cfg and pause/resume/cancel g-code macros must be configured in addition.
See also my klipper with sidewinder intro article [here](https://blog.freakydu.de/posts/2022-10-01-klipper_with_artillery_sidewinderx2/)

Anyway. Great work, great software. Thanks for Klipper (and friends ;-) ). Please keep up the good work.
freakyDude

Signed-off-by: Frank Roth <developer@freakydu.de>

### CODE REVIEW

**Comment by igox** [comment]
Used this configuration file to flash my Sidewinder X2.
Went smooth and work perfectly.

For what it worth, I up vote for merging this PR ;-)

**Comment by freakydude** [comment]
> Thanks. I think it is fine to add this printer config file, but it will need to follow the guidelines at https://www.klipper3d.org/Example_Configs.html . At a minimum point 7, point 7f, point 7d, and point 4.
> 
> -Kevin

Hi Kevin,

I did update the printer configuration according to the guideline. I had to add a new section for *stm32f401* to the `printers.test`. Now the CI build misses the linked dict for this controller. 

I did not found, how that works - or whats going on. So maybe you could advise me what is to-do or fix that for me?

Thank you. 

Best regards, Frank

**Comment by KevinOConnor** [comment]
Thanks.  Add an additional file named `test/configs/stm32f401.config` with the following contents:
```
# Base config file for STM32F401 ARM processor
CONFIG_MACH_STM32=y
CONFIG_MACH_STM32F401=y
```

-Kevin

**Comment by freakydude** [comment]
@KevinOConnor - Thank you, the checks are now successful.

Best Regards,
Frank

**Comment by freakydude** [comment]
Just changed the z_offset to zero for people who did not calibrate z before first print.

Last build run though the brownout time [https://github.com/actions/runner-images/issues/6002](https://github.com/actions/runner-images/issues/6002) of the github ubuntu 18.04 image and it will pass if someone reruns the build. I'm not allowed to do this.

If so, its ready to be merged.

Best Regards
Frank

**Comment by KevinOConnor** [comment]
Thanks.  In general, it looks fine.  However, I'm a little confused by the initial comment block.  How about we word it in a way that is more similar to other example config files:
```
# This file contains pin mappings for the Artillery Sidewinder X2 (2022)
# with a Artillery_Ruby-v1.2 board. To use this config, during "make menuconfig"
# select the STM32F401 with "No bootloader" and USB (on PA11/PA12)
# communication.

# To flash this firmware, set the physical bridge between +3.3V and Boot0 PIN
# on Artillery_Ruby mainboard. Then run the command:
#   make flash FLASH_DEVICE=/dev/serial/by-id/usb-Klipper_stm32f401xc_*-if00

# See docs/Config_Reference.md for a description of parameters.
```

In keeping with point 7h of the docs, I think it would be preferable to avoid http references in the example configs (unless they contain critical information that can't reasonably be added to the config documentation itself).

-Kevin

**Comment by freakydude** [comment]
Done

**Comment by freakydude** [comment]
Hi Kevin, 

I was inspired by this https://github.com/Klipper3d/klipper/blob/master/config/printer-creality-cr10-smart-pro-2022.cfg 

But, I am totally fine with your suggestion. 

Frank

**Comment by KevinOConnor** [comment]
Thanks!

-Kevin

**Pull request merged**
