### PR TITLE
Add Ender 3 S1 Plus config & Fix max temp for S1

### PR DESCRIPTION
**Pull request by Fisheiyy**
Signed-off-by: Rob Casper [myallneedsemail@gmail.com](mailto:myallneedsemail@gmail.com)

The [Ender 3 S1 Plus](https://www.creality3dofficial.com/products/ender-3s1-plus-3d-printer-us-direct) has been released although I have yet to see any reviews over it or much talk but thought I might as well get the config added for when people do start to review it and talk about it (hopefully soon), I also fixed the max temperature for the hotend and bed for the S1 non-pro based off the [official diagram](https://www.creality3dofficial.com/files/goods/20220531/s1vsprovsPlus11.jpg) on the Creality website.

### CODE REVIEW

**Comment by Fisheiyy** [comment]
@KevinOConnor

**Comment by KevinOConnor** [comment]
Configs need to be tested before merged into the master branch.  It did not appear this PR was tested on the actual hardware.

-Kevin

**Comment by Fisheiyy** [comment]
> Configs need to be tested before merged into the master branch. It did not appear this PR was tested on the actual hardware.
> 
> -Kevin

Its the exact same config as the Ender 3 S1/S1 Pro configs with just a larger build volume so it shouldn't need testing, but eventually someone could probably test it, if you could re-open this PR and make sure the bot doesn't close it again that would be nice.

**Comment by Sungray** [comment]
I have a S1 Plus and I'd love a correct configuration. The one committed above doesn't seem right though, the Y cannot reach that high, it does a scary noise when calibrating like that. How can I help establish a correct configuration?

**Comment by Fisheiyy** [comment]
> I have a S1 Plus and I'd love a correct configuration. The one committed above doesn't seem right though, the Y cannot reach that high, it does a scary noise when calibrating like that. How can I help establish a correct configuration?

You can add me on discord so we can communicate quicker, and we can find the maximum movement of X and Y, salmon man#1676

**Comment by Fisheiyy** [comment]
Did a new commit, but PR is closed so it wont appear here, @KevinOConnor reopen this PR please.

**Pull request closed without merging**
