### PR TITLE
add support for creality sermoon D1 printer

### PR DESCRIPTION
**Pull request by peterpanstechland**
created a config support for creality sermoon D1 printer with option of adding bltouch.

### CODE REVIEW

**Comment by peterpanstechland** [comment]
this printer come with a Creality-4.3.1 board.

**Comment by KevinOConnor** [comment]
Thanks.  In general, the config looks good to me.  However, commits need to have a signed-off-by line containing your full real name - https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md

Also, all the configs are added to the regression test case (as describe at https://www.klipper3d.org/Example_Configs.html ) and so the PID parameters need to be defined in the heater sections.

-Kevin

**Comment by peterpanstechland** [comment]
Thanks Kevin,

I think the latest commit should have fixed all the requirements and followed the contributing guide lines, hopefully this config file could finally get merged.😉

-Peter

**Comment by KevinOConnor** [comment]
Thanks, but this doesn't look like it will pass the regression test cases as the pid parameters aren't defined in the heater_bed config section.  Also, the PID parameters should use `option: value` instead of `option = value` syntax (as described in the document above).

-Kevin

**Comment by peterpanstechland** [comment]
> Thanks, but this doesn't look like it will pass the regression test cases as the pid parameters aren't defined in the heater_bed config section. Also, the PID parameters should use `option: value` instead of `option = value` syntax (as described in the document above).
> 
> -Kevin

Sorry, I think I've used someone's sample fork, didn't pay attention on the format, will fix that by next commit.

-Peter

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
