### PR TITLE
Add missing I2C interfaces for Bigtreetech GTR1.0

### PR DESCRIPTION
**Pull request by StoneColdCrazy**
I added 2 missing  i2c interfaces for the bigtreetech gtr 1.0. The main part is i2c3, with this option you can use the external i2c header for extra devices, eg bme280. 

Existing but already closed Tickets  for this request #4434

### CODE REVIEW

**Comment by KevinOConnor** [comment]
I'm not sure what the state of this PR is.  At a minimum, commits need to have a signed-off-by line containing your full real name ( https://www.klipper3d.org/CONTRIBUTING.html ).

-Kevin

**Comment by StoneColdCrazy** [comment]
Signed-off-by: Robert Stein [derstone@hotmail.de](mailto:derstone@hotmail.de)

**Comment by StoneColdCrazy** [comment]
> I'm not sure what the state of this PR is. At a minimum, commits need to have a signed-off-by line containing your full real name ( https://www.klipper3d.org/CONTRIBUTING.html ).
> 
> -Kevin

Hello Kevin,
the main problem here was the connection of an I2C device to the Bigtreetech GTR board. This was not possible because the appropriate I2C interface was not operable via Klipper. It is only a small but crucial change to be able to operate the interface on the GTR. 

I have added the requested "Signed-off-by". 

Greetings
Robert

**Comment by KevinOConnor** [comment]
Thanks.  At a high-level, it looks fine, but I think the definition should be:

```
#if CONFIG_MACH_STM32F2 || CONFIG_MACH_STM324
DECL_ENUMERATION("i2c_bus", "i2c3", 3);
DECL_CONSTANT_STR("BUS_PINS_i2c3", "PA8,PC9");
  #if CONFIG_MACH_STM32F2 || CONFIG_MACH_STM32F4x5
DECL_ENUMERATION("i2c_bus", "i2c2a", 4);
DECL_CONSTANT_STR("BUS_PINS_i2c2a", "PH4,PH5");
DECL_ENUMERATION("i2c_bus", "i2c3a", 5);
DECL_CONSTANT_STR("BUS_PINS_i2c3a", "PH7,PH8");
  #endif
#endif

...
```

-Kevin

**Comment by StoneColdCrazy** [comment]
> Thanks. At a high-level, it looks fine, but I think the definition should be:
> 
> ```
> #if CONFIG_MACH_STM32F2 || CONFIG_MACH_STM324
> DECL_ENUMERATION("i2c_bus", "i2c3", 3);
> DECL_CONSTANT_STR("BUS_PINS_i2c3", "PA8,PC9");
>   #if CONFIG_MACH_STM32F2 || CONFIG_MACH_STM32F4x5
> DECL_ENUMERATION("i2c_bus", "i2c2a", 4);
> DECL_CONSTANT_STR("BUS_PINS_i2c2a", "PH4,PH5");
> DECL_ENUMERATION("i2c_bus", "i2c3a", 5);
> DECL_CONSTANT_STR("BUS_PINS_i2c3a", "PH7,PH8");
>   #endif
> #endif
> 
> ...
> ```
> 
> -Kevin

If desired, I can add something similar. However, the suggested line "#if CONFIG_MACH_STM32F2 || CONFIG_MACH_STM32F4x5" would not match the F407. I'll look at it again tomorrow, especially in relation to the other processors. Then I will update the current state on my branch, if there are any changes in these lines.

**Comment by StoneColdCrazy** [comment]
I adjusted it according to Kevin's suggestion and also brought my branch up to the current master.

**Comment by KevinOConnor** [comment]
Thanks.  However, the latest changes do not look correct to me.  I made some changes that I think should handle this (commit 38e82e8d).

-Kevin

**Comment by StoneColdCrazy** [comment]
Hello Kevin,
too bad, my efforts were in vain, due to the changes the problems are still present and do not contribute to a BTT GTR to the success as desired. 
The pins PH7 and PH8, which are urgently needed here, are enabled by the flags ONLY for STM32F2xx and STM32F4x5 processors. 
I have already written and emphasized several times that it is mandatory that here the STM32F407 is in use on the GTR. 


Translated with www.DeepL.com/Translator (free version)

**Comment by KevinOConnor** [comment]
Despite the name, `CONFIG_MACH_STM32F4x5` is an alias for the F405, F407, and F429 chips.  See src/stm32/Kconfig for the definition.  If the latest code does not work, we'll need to know the details of how it was tested and what is not working with it.

-Kevin

**Pull request closed without merging**
