### PR TITLE
Update install-debian.sh

### PR DESCRIPTION
**Pull request by tekweaver**
apt packages:
python-dev -> python-dev-is-python3
libusb-1.0 -> libusb-1.0.0

python virtual environment:
python2 -> python3

### CODE REVIEW

**Comment by JamesH1978** [comment]
Thank you for submitting a PR, please be aware that you need to sign off to accept the developer certificate of origin, please see point 3 in https://github.com/Klipper3d/klipper/blob/master/docs/CONTRIBUTING.md#what-to-expect-in-a-review

Thanks
James

**Comment by tekweaver** [comment]
I would like to start by first apologizing. This is the first time I have submitted a pull request and still new to all git has to offer. Python 2 has been EoL since 2020/01/01. I thought to myself "since I HAVE to edit the debian install script every time I download klipper I can contribute a solution to a problem.

The debian install script has not been updated for 2 years.... Python2 went EOL in 2020... FOUR years ago... I was trying to be kind... But fk off trying to get me to sign a legal document for tying to be kind to my fellow human beings.... something to benefit all of us.

THIS RIGHT HERE is a reason to NEVER CONTRIBUTE and just keep an updated fork with my own edits.

**Comment by jakep82** [comment]
Did you read the document?  It effectively just states that you certify you have the right to submit the code.

The only goal is to prevent people from submitting code they didn't write and for which they have no legal copyright.

**Comment by tekweaver** [comment]
Yes I read the legal document.
"Submitters must provide a [Signed-off-by line] using **_their full real name_**. It indicates the submitter agrees with the [developer certificate of origin]."

FOR A BATCH SCRIPT EDIT.... Its the fucking principle of it... FULL REAL NAME is something that holds up in court, earth forbid, it came to that.... Look at what the fuck is going on with Bambo Labs and Stratasys... come on now..

**Pull request closed without merging**
