### PR TITLE
Added the possibility to get where the "cone shape" of the build volume starts from Macros

### PR DESCRIPTION
**Pull request by Hywelmartin**
Added the possibility to get where the "cone shape" of the build volume starts from Macros

Signed-off-by: Martin Malmqvist Volcomosq@gmx.com

### CODE REVIEW

**Comment by mental405** [comment]
On first inspection this does not appear to be a major or problematic addition. You do, however, need to provide a developer sign off line in your PR before it can be merged.

**Comment by Hywelmartin** [comment]
sorry forgot about that

**Comment by KevinOConnor** [comment]
Thanks.  However, any "printer status" variables that are exported will require a corresponding change to docs/Status_Reference.md .  Also, I'm not sure "limit_z" is a public facing name for this variable.

-Kevin

**Comment by Hywelmartin** [comment]
limit_z was the expression in delta.py so I kept it... Now it's cone_start_z if that's a more viable name.. mentioned in status_references as well. Thanks for your time

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
