### PR TITLE
Allow release info changes when installing on Octoprint

### PR DESCRIPTION
**Pull request by shadow7412**
Follow on from issue #4623, to make installation a little more seamless from a fresh octopi image.

### CODE REVIEW

**Comment by KevinOConnor** [comment]
I'm not sure what this change does, but it hasn't been needed for me.  I'm inclined to say that this isn't currently a good match for the master Klipper repository.

Separately, commits need to have a signed-off-by line - https://github.com/KevinOConnor/klipper/blob/master/docs/CONTRIBUTING.md

-Kevin

**Comment by zellneralex** [comment]
@KevinOConnor the change is needed as buster changed state to old-stable. It’s already added to the moonraker updater.
@Arksine can confirm that

**Comment by shadow7412** [comment]
@KevinOConnor I've edited the commit to include the line.

It's mentioned in the description - but you should be able to see what this does by installing a fresh octopi image then attempting to run `./klipper/scripts/install-octopi.sh` (after cloning of course). Without it, the script errors.

If you don't want this included in the klipper install I understand - but the docs would need to be updated to include this instruction.

**Comment by shadow7412** [comment]
@zellneralex I've confirmed this - it's [here](https://github.com/Arksine/moonraker/blob/master/scripts/install-moonraker.sh#L44).

**Comment by guysoft** [comment]
Hey, just found this, had the same issues.
Related:
https://github.com/guysoft/CustomPiOS/issues/143
https://github.com/RPi-Distro/pi-gen/issues/546

**Comment by KevinOConnor** [comment]
Thanks.  I understand that this is an issue for installations.  However, am not comfortable with the Klipper installation scripts silently making an OS level change.  So, this isn't a change I'm comfortable making.

-Kevin

**Comment by KevinOConnor** [comment]
Thanks.  I understand that this is an issue for installations.  However, I am not comfortable with the Klipper installation scripts silently making an OS level change.  So, this isn't a change I'm comfortable making.

-Kevin

**Comment by shadow7412** [comment]
Understandable. Please consider updating the documentation instead.

**Comment by guysoft** [comment]
Hey, I suggest that instead changing the OS, you can switch an OS, its also much easier to install this way, I made a dedicated distro.
https://github.com/Klipper3d/klipper/pull/4895

**Pull request closed without merging**
