### PR TITLE
bed_mesh: relative_reference_index range check

### PR DESCRIPTION
**Pull request by shiftingtech**
Added a simple range check to the relative_reference_index,
so that having it set too large leads to a reasonable error
instead of a confusing index out of range message.

Signed-off-by: Ben Eastep <shifting@shifting.ca>

### CODE REVIEW

**Comment by zellneralex** [comment]
Why not even enhance the message further like 
`Invalid relative_reference_index. Value must be within 0 and x`
where x is the length-1 value

**Comment by KevinOConnor** [comment]
Thanks.  Could we just move the `getint('relative_reference_index', None)` to after `_generate_points()` and use `getint('relative_reference_index', None, minval=0, maxval=len(self.points)-1)`?

Maybe @Arksine has some thoughts?

-Kevin

**Comment by shiftingtech** [comment]
That would essentially silently discard an invalid value,  correct?

My fear there, would be that it would lead to somebody suddenly getting a
mesh that's shifted shifted down, resulting in them driving the toolhead
into the bed with little warning.

**Comment by Arksine** [comment]
Kevin's suggestion will work, it takes advantage of the range checking built in to the `configfile` implementation.  A value outside the specified range would result in a config error.

It would also be necessary to move `self.orig_config['rri'] = self.relative_reference_index` below the `getint` method.

**Comment by shiftingtech** [comment]
Ah, okay.   I'll revisit it when I get a minute then

**Pull request closed without merging**
