### PR TITLE
spi_flash_add mks_monster8,robin_v3

### PR DESCRIPTION
**Pull request by BOAndy1985**
sd update tested and working mks_monster8

Signed-off-by Andreas Fröhlke boandy1985@googlemail.com

### CODE REVIEW

**Comment by Arksine** [comment]
Thanks Andy.  I do have a question, however first I should point out that all commit should be signed off per the [contributing documentation](https://www.klipper3d.org/CONTRIBUTING.html#format-of-commit-messages).

With regard to the additions, it appears to me that PC11, PC12, and PC10 are hardware pins, specifically on the `spi3a` bus.  Is there a specific reason you chose software SPI?  It would be preferable to use the hardware bus if it works correctly.

**Comment by BOAndy1985** [comment]
hey yes I had it with spi3 try config that didn't work.  If you tell me that would be possible with spi3a, I'll test it right away and change it again

**Comment by BOAndy1985** [comment]
just tested it with spi3a it works too.  Unfortunately, English is bad, so I don't understand what else we need for someone to integrate it

**Comment by Sineos** [comment]
grafik


See above screenshot as example: Your real name and a valid email address.

**Comment by Arksine** [comment]
As Sineos mentioned, edit the pull request with your signature.  The signature should include your real name and a valid email address.  This indicates that you accept the [Developer Certificate of Origin](https://github.com/Klipper3d/klipper/blob/master/docs/developer-certificate-of-origin).  Generally this should be in the commit, however it its in the pull request Kevin can squash merge it and add the signature.

**Comment by BOAndy1985** [comment]
I have added my email address to my profile and my real name

**Comment by Arksine** [comment]
That is good, however the pull request needs your signature in order to affirm acceptance of the DCO.  See the [last PR I submitted](https://github.com/Klipper3d/klipper/pull/5584) for an example of the signature.

**Comment by BOAndy1985** [comment]
I hope it's not missing now, what else I give it up

**Comment by Arksine** [comment]
You got it, thanks.

**Review by Arksine — APPROVED** [review]

**Comment by BOAndy1985** [comment]
thank you my english is not good i always have to work with google trandlator

**Comment by Arksine** [comment]
FWIW, it looks like this PR accidentally got changed to draft status.  I think that needs to be removed for Kevin to merge.

I also reviewed and approved the changes prior to the review request, so I'm guessing that was unintentional as well.

**Comment by BOAndy1985** [comment]
what do I have to do now to continue?

**Comment by Arksine** [comment]
When Kevin gets around to it he will see the PR and merge it.

**Comment by KevinOConnor** [comment]
Thanks.

-Kevin

**Pull request merged**
